### ISSUE TITLE
Two sensor optimizing the same transform - How to handle it?

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#120]
Discussed this with @eupedrosa this today ... should be possible

**Comment by miguelriemoliveira** [comment]
First attend was done in eye_to_base ... #123 

Using parameter names derived from the transformations, rather than from the sensors. Here is an excel with the sparse matrix ... seems to be ok ... @eupedrosa does it make sense to you?

https://docs.google.com/spreadsheets/d/1ysUhEgy7xfSNev5M95eXON0_1amHUuk3hQkSB5Z3fCI/edit#gid=0

**Comment by eupedrosa** [comment]
Yes they make sense. Did you test it?

**Comment by miguelriemoliveira** [comment]
This is handled already since we go from sensors to a set of transforms when creating the parameters.
