### ISSUE TITLE
Unite chessboard and charuco visualization

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#170]
Must find a way to draw both correctly.

Also, line and point markers should be added overlaying the textured mesh, since those are more useful for assessing the objective function.

**Comment by miguelriemoliveira** [comment]
Hi @aaguiar96 and @eupedrosa ,

help me out here: which information exactly do we need to have for each pattern:

First question is: we should have the same parameters regardless of whether we are using a chessboard or a charuco, right?

From what  I see, we use the following:

 - evaluation points
    - the actual corners of the pattern
    - how do we make robust to partial detections? (@eupedrosa how is this handled?)
 - limit points
    - A list of points from the outer boundary of the (physical pattern object)
    - Should these be separate in top, bottom, left and right points?
    - Compared against the extrema of the 2D lidar measurements, or the convex hull of 3D Point clouds
 - inner points
   - transitions  from black to white squares (right now we only use vertical)
   - Compared agains edges detected in 2D lidars
 - corners of the physical pattern
    - do we need this?

Am I missing something?

**Comment by miguelriemoliveira** [comment]
Given the above I propose that the calibrate generates, for the calibration pattern a dictionary like this:

```json

                # All coordinates in the pattern's local coordinate system. Since z=0 for all points, this coordinate is ommited.

                # Corners
                'corner': [{'idx': 0, 'x': 3, 'y': 4}, ..., {'idx': ncorners, 'x': 30, 'y': 40}]
                    },
                # Physical outer boundaries of the calibration pattern
                'frame': {
                    'top':    [{'x': 3 , 'y': 4 }, ... , {'x': 30 , 'y': 40 }]},
                    'right':  [{'x': 3, 'y': 4}, ..., {'x': 30, 'y': 40}]},
                    'bottom': [{'x': 3, 'y': 4}, ..., {'x': 30, 'y': 40}]},
                    'left':   [{'x': 3, 'y': 4}, ..., {'x': 30, 'y': 40}]
                         }
                # Transitions from black to white squares
                'transition': {
                         'vertical': [{'x': 3, 'y': 4}, ..., {'x': 30, 'y': 40}]},
                         'horizontal':  [{'x': 3, 'y': 4}, ..., {'x': 30, 'y': 40}]},
                }
                # Should we put here the physical corners?

            }
```

The goal is to standarize what we have (generate) for each calibration pattern. Objective functions would use (some of ) this informaiton, and visualization must be able to plot it.
Any comments?

**Comment by eupedrosa** [comment]
> how do we make robust to partial detections? (@eupedrosa how is this handled?)

Each corner has an ID, from 0 to N-1, where N is the number of corners. This is the same as an index number of an array.  The detector gives us an array of IDs, and that same ID is used as a selector for the *grid of corners*, for examnple:
```python
grid=np.array([0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.6]) # example of a corner grid (1D)
ids= [0,3,5]
usefull_grid = grid[ ids ]
print(usefull_grid)
```
It will output `[0.  0.3 0.5]`

**Comment by miguelriemoliveira** [comment]
> Each corner has an ID, from 0 to N-1, where N is the number of corners. This is the same as an index number of an array. The detector gives us an array of IDs, and that same ID is used as a selector for the grid of corners, for examnple:

Great! One less problem.

**Comment by eupedrosa** [comment]
You proposal for the calibration pattern is very verbose...  Why so many "x" and "y"s ??
I know that you like dictionaries all the way ... but we have a lot of code to do conversions from this format to something usable by *numpy*.

**Comment by eupedrosa** [comment]
Are we still pursuing a discrete definition of the pattern border?
```yaml
# Physical outer boundaries of the calibration pattern
'frame': {
    'top':    [{'x': 3 , 'y': 4 }, ... , {'x': 30 , 'y': 40 }]},
   'right':  [{'x': 3, 'y': 4}, ..., {'x': 30, 'y': 40}]},
   'bottom': [{'x': 3, 'y': 4}, ..., {'x': 30, 'y': 40}]},
   'left':   [{'x': 3, 'y': 4}, ..., {'x': 30, 'y': 40}]
   }
```

Again, using dictionaries for defining x's and y's adds extra steps when we need to use this information.

**Comment by miguelriemoliveira** [comment]
Hi @eupedrosa ,

I think the conversion is simple using list compreension:

x = [item.x for item in d['frame]['top']]
y = [item.x for item in d['frame]['top']]

and this philosophy was used elsewhere in the dataset, so it makes sense for consistency.

Concerning the storage of discrete values, it was just to maintain retrocompatibility. The 2D lidar objective function uses these.

We would have to adapt the 2D lidar objective function to use a point to line segment distance, and make all the necessary tests to check that it is working, not just assume it is. Only then we could move on to representing just the two points per line segment.

Another option is to keep the sampled points (this is not so much space), and also keep the two points per line segment. It would be something like this:

# Physical outer boundaries of the calibration pattern
'frame': {
    'top': { { 
                 pi : {'x': 4 , 'y': 7 },                  
                 pf : {'x': 44 , 'y': 37 },
                 sampled:  [{'x': 3 , 'y': 4 }, ... , {'x': 30 , 'y': 40 }],
              }
            },
      (...)
   }

actually this last is my preferred solution since we can use whatever approach we want in the objective function, or even a combination of both. What do you think?

**Comment by eupedrosa** [comment]
For the frame, I think we only need to save 4 points, somehting like 
```yaml
'frame': {
    'corner': [ ... ],
    'top': { sampled_here },
    'left': {sampled_here },
}
```

But there is something I'm not understanding. This is a datastrucure to represent a pattern?

**Comment by miguelriemoliveira** [comment]
Yes, it is used to represent the pattern.

And it will be used to draw the pattern also. 

During optimization, it is important to have visual feedback of what the objective function is doing.

**Comment by miguelriemoliveira** [comment]
> What is the transition needed for? The lidars?

yes, trying to use more information for 2d lidars ...

**Comment by miguelriemoliveira** [comment]
Hi @aaguiar96 ,

yesterday night I started but could not finish this. Will continue today and let you know once its done.

**Comment by aaguiar96** [comment]
> yesterday night I started but could not finish this. Will continue today and let you know once its done.

Ok @miguelriemoliveira 
I'll close today the `limit points` calculation. I'll compute the circle radius in a dynamic manner, using the higher distance between the 2D points. :)

**Comment by miguelriemoliveira** [comment]
OK, so I got the chessboard data creation and visualization up and running ...

I don't draw any mesh because we don't have a mesh file for the chessboard ... any volunteers : - ) ... someone who is very proeficient with blender ?

Now I will expand for the charuco. 

@aaguiar96 will let you know once its working, but I am not sure I will do it now since I have a meeting at 19h.

![image](https://user-images.githubusercontent.com/11350998/84058419-1da6d600-a9b1-11ea-8cd5-d985cc4c01c0.png)

![image](https://user-images.githubusercontent.com/11350998/84058513-416a1c00-a9b1-11ea-8306-95f2608daaa9.png)

**Comment by miguelriemoliveira** [comment]
> I'll close today the limit points calculation. I'll compute the circle radius in a dynamic manner, using the higher distance between the 2D points. :)

good idea!

**Comment by miguelriemoliveira** [comment]
For the charucos the reference system is a bit different (from opencv):

![image](https://user-images.githubusercontent.com/11350998/84059245-277d0900-a9b2-11ea-9d13-8c847c25eb6a.png)

**Comment by miguelriemoliveira** [comment]
Hum ... detection from our code does this

![Uploading image.png…]()

**Comment by aaguiar96** [comment]
> Hum ... detection from our code does this

That means that the size of the mesh is wrong right?...

**Comment by miguelriemoliveira** [comment]
I think so, but before that, we need to agree on an origin for the mesh ...

**Comment by eupedrosa** [comment]
> For the charucos the reference system is a bit different (from opencv):

> Hum ... detection from our code does this

You are looking at two different things. The mesh is correct.

**Comment by aaguiar96** [comment]
> The function `drawAxis` draws an axis considering the full pattern. However, the detection is only the coorners. And that is what we are using as origin.

Still, the drawn corners do not match with the mesh corners.

**Comment by eupedrosa** [comment]
> Still, the drawn corners do not match with the mesh corners.

What image are you refering to, @aaguiar96? I see the corners drawn as expected...

**Comment by aaguiar96** [comment]
> Do not forget, that RViz centers the cubes in the coordinates that you provide.

Right, I was missing that! :)

**Comment by eupedrosa** [comment]
If the objective is to overlap the squares you have add to each coordinate half the size of the square.

**Comment by miguelriemoliveira** [comment]
Hi again,

sorry, I don't get it.  The points are drawn after the computed the corner coordinates (I may have done something wrong there, but I don't think so)

> You are looking at two different things. The mesh is correct. Read the manual!

@eupedrosa, which manual do you refer to? Also, the sphere centers and the corners are noticeably not in the same location. See the image:

![image](https://user-images.githubusercontent.com/11350998/84091255-cffb8f00-a9eb-11ea-8564-832ef617281a.png)

Thus, either:

1) the corner coordinates I compute are wrong or;
2) the mesh is wrong

How can you be so sure the mesh is correct? I don't get it 

Here's my code to draw the corners:

https://github.com/lardemua/atom/blob/d61bdf020d768f9b9a43a4dab9e502f40f96194d/atom_core/src/atom_core/patterns.py#L115-L124

and the code to visualize:

https://github.com/lardemua/atom/blob/d61bdf020d768f9b9a43a4dab9e502f40f96194d/atom_core/src/atom_core/visualization.py#L264-L281

Can you detect something wrong?

My point is: these points that I draw are computed from the pattern description. I should not be adjusting them to fit the mesh. Either the points are wrongly calculated or the mesh is not ok. 

And we have to find which. You agree?

**Comment by miguelriemoliveira** [comment]
> If the objective is to overlap the squares you have add to each coordinate half the size of the square.

Sorry again, I also don't understand this. What do you mean by overlap the squares? Center on the chessboard corners?

**Comment by miguelriemoliveira** [comment]
Also in meshlab

![image](https://user-images.githubusercontent.com/11350998/84091820-801dc780-a9ed-11ea-9a65-f999fe69889d.png)


@eupedrosa , do you still say the mesh is correct?

**Comment by miguelriemoliveira** [comment]
and by the way @eupedrosa , your charuco_5x5.dae has the origin in the proper place

![image](https://user-images.githubusercontent.com/11350998/84091899-c2470900-a9ed-11ea-923a-ddb4bdd88ec1.png)

**Comment by eupedrosa** [comment]
Is that the mesh created by @aaguiar96? I was thinking it was the mesh we used for the hand-eye.. my fault.. If that's the case, then yeh, the texture in the mesh can be wrong or the origin of the mesh can also be wrong.

Sorry, @aaguiar96 and @miguelriemoliveira. 

I was defending the mesh because in the calibrations  that we have, in hand-eye, the mesh was correct. 

Nonetheless, it looks like you are investing a lot of time in this..

**Comment by miguelriemoliveira** [comment]
Hi @eupedrosa ,

ok, so you agree it is not correct. Great. @aaguiar96 , if you also agree with the reasoning above, that means you have to correct the mesh. From my side, I see two things wrong:

1. the origin of the mesh must be centered on the bottom left corner, as @eupedrosa 's mesh above.
2. the XoY plane of the mesh's reference system must lie on the plane where the texture is painted, again as in @eupedrosa 's dae.

> Nonetheless, it looks like you are investing a lot of time in this..

Of course, this is necesary step to get the velodyne calibration up and running.

**Comment by miguelriemoliveira** [comment]
Hi @aaguiar96 ,

something else: Can you verify is the green and red dimensions are equal? Because we assume they are in the code ...

![image](https://user-images.githubusercontent.com/11350998/84093159-59fa2680-a9f1-11ea-8a61-4571968330ab.png)

**Comment by aaguiar96** [comment]
Ok @miguelriemoliveira 

What a pro in Blender I am, ahah! :-)
Tomorrow morning I'll finish this up.

**Comment by miguelriemoliveira** [comment]
Hi @aaguiar96 ,

I could have solved your problem. In meshlab I can move the object and was able to get this

![image](https://user-images.githubusercontent.com/11350998/84163416-628e4380-aa69-11ea-92f5-27d5486866c4.png)

This would have been enough if the size of the squares is correct but it is not.

![image](https://user-images.githubusercontent.com/11350998/84169767-ebf54400-aa70-11ea-9718-53c98a8f5f86.png)

Notice how the spheres are increasingly further away from the corners as we move away from the origin.

**Comment by aaguiar96** [comment]
Nice, thanks @miguelriemoliveira 

So, I'll check all the sizes and update the mesh.
I let you know when I have some news.

**Comment by miguelriemoliveira** [comment]
Hi @aaguiar96 ,

No problem. Don't forget, since you are buildin a new mesh, might as well as check this part while you are at it (check the post above):

> something else: Can you verify is the green and red dimensions are equal? Because we assume they are in the code ...

**Comment by aaguiar96** [comment]
The dimensions:

![dimensions](https://user-images.githubusercontent.com/35901587/84198555-a1d58800-aa9b-11ea-9ee5-d35eb7a250c7.jpg)

The borders have different sizes...

**Comment by aaguiar96** [comment]
@eupedrosa in your case was the size of the margins equal?

The `draw` function [(link](https://docs.opencv.org/3.4/d0/d3c/classcv_1_1aruco_1_1CharucoBoard.html#a5f1b7c91bd8bf8271931d6f06292f1bc)) from `cv::charuco` only accepts one argument for the margin, which means that it considers that both margins are equal right?

**Comment by eupedrosa** [comment]
Yes, they are equal.

You can always change the source code to your needs.

**Comment by aaguiar96** [comment]
I'll try to hardcode it then...

**Comment by miguelriemoliveira** [comment]
Hi @aaguiar96 ,

It is not for visualization purposes. The margin is used to generate the frame points (the old limit points) which are used by the objective function.

The mesh that is drawn is, as you say, just for visualization. But if we can make it the correct dimensions it would be better.

The charuco detection requires a margin, but I am almost sure that the number you give the function is a "minimum border size". As such, you can just use the minimum of the x and y coordinate. 

I would try searching hard for other alternatives before going about changing the opencv code. Also, as said above, in this case I don't think you need it. The detection is working fine, right?

**Comment by aaguiar96** [comment]
Hum... Ok



> The charuco detection requires a margin, but I am almost sure that the number you give the function is a "minimum border size". As such, you can just use the minimum of the x and y coordinate.

Setting the margin to the minimum size, this is the image I obtain 

![board](https://user-images.githubusercontent.com/35901587/84208375-84101f00-aaab-11ea-850a-1d443556327a.png)

The margins are equal...

**Comment by miguelriemoliveira** [comment]
I am sorry, I did not understand that the function you talked about was to generate an image. You could do some math and add a white band of the correct size on the left and right (or top bottom, depending on which is the smallest border). Then, you would use this wider image as texture ...

**Comment by aaguiar96** [comment]
> I am sorry, I did not understand that the function you talked about was to generate an image. You could do some math and add a white band of the correct size on the left and right (or top bottom, depending on which is the smallest border). Then, you would use this wider image as texture ...

Yes, I thought in the same solution! I'm on it :)

**Comment by miguelriemoliveira** [comment]
> The dimensions:
> 
> ![dimensions](https://user-images.githubusercontent.com/35901587/84198555-a1d58800-aa9b-11ea-9ee5-d35eb7a250c7.jpg)
> 
> The borders have different sizes...

Hi @aaguiar96 ,

thanks for this. To solve it I have created #172 and will work on it.

**Comment by aaguiar96** [comment]
No problem @miguelriemoliveira 

Problem solved. I'll remake the mesh now

![board](https://user-images.githubusercontent.com/35901587/84209836-0d752080-aaaf-11ea-95c1-5e7d7d31168f.png)

**Comment by aaguiar96** [comment]
I think this is it:

![Capture](https://user-images.githubusercontent.com/35901587/84210255-27fbc980-aab0-11ea-95a4-2b0e93e308d2.PNG)

I'll commit the mesh. @miguelriemoliveira can you try it out?

**Comment by eupedrosa** [comment]
That is not it.. The origin should be the corner inside...

**Comment by miguelriemoliveira** [comment]
Hello, I moved the origin to be in the inside corner, as @eupedrosa said.

It works:

![image](https://user-images.githubusercontent.com/11350998/84214740-2df7a780-aabc-11ea-9289-b256709b6f9c.png)

Thanks for the help guys. This issue is done! I will erase all other mehes from github and keep just this last one with the original name.

**Comment by aaguiar96** [comment]
Great @miguelriemoliveira 

So, now I can finish the cost function, right?

**Comment by miguelriemoliveira** [comment]
Yes, that's the next step. Do you need to talk about it? You know where to go?

**Comment by aaguiar96** [comment]
Now I have to create a new set of residuals computed by the pairwise difference between the closest limit points of the pattern and the cloud right?

**Comment by miguelriemoliveira** [comment]
yes, right. I would say:

```
for each point in limit_points_detected_in_the_cloud:
    compute minimum distance to all the sampled points in the pattern frame
    use the minimum as the error for that point
```

with all the changes that I was making in the patterns I may have introduced some bug ,,, let me know if the optimizer is doing awkward stuff.

**Comment by miguelriemoliveira** [comment]
This discussion should be in the other issue ...
