### ISSUE TITLE
Bug in charuco detection ...

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#173]
when running:

roslaunch ur10e_eye_in_hand_calibration collect_data.launch bag_rate:=0.4 output_folder:=~/datasets/test overwrite:=true

I get after 15 secs an error in the charuco detector:

> [ERROR] [1591777705.338495, 1579803593.672204]: bad callback: <bound method InteractiveDataLabeler.sensorDataReceivedCallback of <atom_calibration.interactive_data_labeler.InteractiveDataLabeler instance at 0x7f1e3d0d7460>>
> Traceback (most recent call last):
>   File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
>     cb(msg)
>   File "/home/mike/catkin_ws/src/calibration/atom/atom_calibration/src/atom_calibration/interactive_data_labeler.py", line 213, in sensorDataReceivedCallback
>     self.labelData  # label the data
>   File "/home/mike/catkin_ws/src/calibration/atom/atom_calibration/src/atom_calibration/interactive_data_labeler.py", line 335, in labelData
>     result = self.pattern.detect(image, equalize_histogram=True)
>   File "/home/mike/catkin_ws/src/calibration/atom/atom_calibration/src/atom_calibration/patterns.py", line 116, in detect
>     ccorners = cv2.cornerSubPix(gray, ccorners, (5,5), (-1, -1), criteria)
> error: OpenCV(4.2.0) /io/opencv/modules/imgproc/src/cornersubpix.cpp:58: error: (-215:Assertion failed

Do you know what could be wrong? Did we not remove the subpix a couple of weeks ago?

**Comment by miguelriemoliveira** [comment]
dba8c00 fixes it but removes the subpix computation part. We could wrap it around a try catch ... does it really make a difference to have subpixel accuracy for the detection of the corners?

**Comment by eupedrosa** [comment]
> does it really make a difference to have subpixel accuracy for the detection of the corners?

It does, it improves the corner detection. It is always failing?

**Comment by miguelriemoliveira** [comment]
No, in some situations ...

**Comment by miguelriemoliveira** [comment]
@eupedrosa , can you add the try catch wrapper? Do you take this issue?

**Comment by miguelriemoliveira** [comment]
@eupedrosa ,

should we close this one?
