### ISSUE TITLE
Fix agrob description - zed camera not present

### ISSUE THREAD

**Issue by aaguiar96** [lardemua/atom#175]

**Comment by miguelriemoliveira** [comment]
Hi @aaguiar96 ,

the camera is there

![image](https://user-images.githubusercontent.com/11350998/84517262-f446bc80-acc6-11ea-9689-a953f1f82a68.png)

Should I close the issue?

**Comment by aaguiar96** [comment]
Yes, sorry, my bad...

**Comment by miguelriemoliveira** [comment]
No problem.
