### ISSUE TITLE
Create robotic systems for RWHE and Tabb datasets

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#180]
These should be in separate packages.

Will remove them from atom. @eupedrosa , can you do this?

**Comment by eupedrosa** [comment]
I can do that, but first I will finish the paper..

**Comment by miguelriemoliveira** [comment]
Ok. Thanks. The conversion scripts should also be inside de pakcages. I would say you need a:

rwhe_kuka1_calibration
...
rwhe_kukaX_calibration

and a 

tabb_ds1_calibration
...
etc

**Comment by eupedrosa** [comment]
Hi @miguelriemoliveira, do we really need this in ATOM repo? Should we store this in another place?

**Comment by miguelriemoliveira** [comment]
Yes, the idea was another place. The github for the paper datasets?

**Comment by miguelriemoliveira** [comment]
Closing this one. Deprecated.
