### ISSUE TITLE
Relative output path in data collection process goes to ~/.ros/<path>

### ISSUE THREAD

**Issue by eupedrosa** [lardemua/atom#184]
When using `collect_data.launch` with a relative path for `output_folder`, the result is a folder under `~/.ros/`. Is this the desired behavior?

**Comment by miguelriemoliveira** [comment]
No. It should be fixed.

**Comment by miguelriemoliveira** [comment]
This is fixed. Tried it an hour ago like this:

`roslaunch ur10e_eye_to_base_calibration collect_data.launch output_folder:=~/datasets/test overwrite:=true`

and it worked fine.
