### ISSUE TITLE
Configuration dictionary is not robust against missing keys.

### ISSUE THREAD

**Issue by eupedrosa** [lardemua/atom#186]
The commit 1dce8e0a76230afcc74cc07b2ba647f9de77f7d5 is an example of this problem. A simple typo rendered the collector to a stall.

Because the `key` was missing it should had raise an exeption, but for some reason, it failed in silence.
Accessing configuration data should be robust.

**Comment by miguelriemoliveira** [comment]
Ah, just created #187 for this. Will close this one. Please give your opinion and close #187. It is implemented.
