### ISSUE TITLE
Sampling residuals?

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#201]
Hi @eupedrosa and @aaguiar96 ,

I was thinking about the long time it takes to optimize agrob. One simple idea is to sample the residuals.

For the velodyne with 2 cameras + lidar we now have 6000+ residuals ... that may be too much. 

What do you think about a parameter that just samples the total of residuals selecting only 50% or 10% of the total to compute the objetive function?

A more complex idea would be to have this sampling be reduced as the optimization progresses (similar to the effect of the learning rate in deep learning). But for now, a simple sample equal for all could work...

What do you think?

**Comment by eupedrosa** [comment]
Hi @miguelriemoliveira,

I agree with the *sampling* idea. Note that what we previously did is decimation, not sampling. I understand sampling as random selection.

> A more complex idea would be to have this sampling be reduced as the optimization progresses (similar to the effect of the learning rate in deep learning). But for now, a simple sample equal for all could work...

At start we should have more or less samples? And how do we qualify the optimization progress?

**Comment by miguelriemoliveira** [comment]
Hi @eupedrosa ,

thanks for the imput.

> At start we should have more or less samples? 

Less.

> And how do we qualify the optimization progress?

Number of iterations

**Comment by miguelriemoliveira** [comment]
Right now sampling is being done by selecting a step with which to iterate through the labelled points.

This is not interesting because it is not really random. Will try to create a randomized process which occurs at startup, and then only the randomly selected labels are used.

**Comment by miguelriemoliveira** [comment]
@eupedrosa said he will work on this.

**Comment by eupedrosa** [comment]
Hi @miguelriemoliveira.
I already have a working version. But there is a catch. Being "random" the results are not deterministic, it this Ok for you or should I add the possibility to set a *seed* for when a deterministic outcome is desired?

**Comment by miguelriemoliveira** [comment]
Setting the seed is helpfull for debugging purposes.

**Comment by miguelriemoliveira** [comment]
Hi @eupedrosa ,
I tested again several combinations of agrob with varying number of collections and other parameters. It seems to be working fine. I did not observe again 100+ iterations.

Lets not worry about it.
