### ISSUE TITLE
Run tests of agrob calibration with new xacro 

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#203]
After #199, run new tests

**Comment by aaguiar96** [comment]
New agrod dataset for URDF tests.

[datasets.zip](https://github.com/lardemua/atom/files/4897817/datasets.zip)

**Comment by eupedrosa** [comment]
Any new conclusion?

**Comment by aaguiar96** [comment]
Hi @eupedrosa 

We fixed the URDF and add a new parameter to sample the residuals. Then we collected a new dataset with this fix.
We've done several tests and concluded that in almost all the tests, the cloud points start on the left of the patterns. This leads to a solution where the velodyne is always on the right of the ZED camera.
We did not figured out the problem yet.

**Comment by aaguiar96** [comment]
Hi @eupedrosa and @miguelriemoliveira 

@eupedrosa at the end of the last meeting, me and @miguelriemoliveira were a bit lost regarding the next step. What to do to overcome these error of centimeters?...
I think the three of us should schedule a meeting to analyze the results with detail and decide what's the next step.

What do you say?

**Comment by miguelriemoliveira** [comment]
Can we talk in 20 mins?

**Comment by aaguiar96** [comment]
Yes!

**Comment by eupedrosa** [comment]
So. it should start now, right?

**Comment by miguelriemoliveira** [comment]
I need an extra 5 to 8 mins ... sorry.

**Comment by miguelriemoliveira** [comment]
This is done.
