### ISSUE TITLE
Test ILCC and compare with our approach

### ISSUE THREAD

**Issue by aaguiar96** [lardemua/atom#206]
https://github.com/mfxox/ILCC

**Comment by aaguiar96** [comment]
I @miguelriemoliveira  and @eupedrosa 

This is not a ROS package. It requires the pointcloud data as `.pcd` files.
Can you confirm this? Is this a problem?...

**Comment by miguelriemoliveira** [comment]
Hi @aaguiar96 ,

From their readme:

> Make a folder for example named as DATA and make the image and point cloud folders DATA/img and DATA/pcd respectively.
> 
> Put panoramic images into DATA/img and point cloud files into DATA/pcd. The files should be named like 00XX.png or 00XX.csv.
> 
> cd DATA and copy config.yaml to DATA and modify config.yaml according to your situation.
> 
> Corner detection from images.

So I guess they do need the pcd files. If you want I can try to generate them ...

**Comment by aaguiar96** [comment]
It would be interesting to extract the pcd files from our json files. In this way we would have exacly the same data...

I can try to do it. :)

**Comment by miguelriemoliveira** [comment]
OK, I worked on this two weeks ago #155 but abandoned the idea.

But I think me problem was with loading back the point cloud, which you don't need.

You can also think of saving a ply and then run the pcl_ply2pcd executable.

**Comment by aaguiar96** [comment]
So, at the end of the calibration I should generate N .ply /.pcd files right? One for each collection.

**Comment by miguelriemoliveira** [comment]
Right.
*  Miguel Riem de Oliveira                                             *
email:    mriem@ua.pt    |    m.riem.oliveira@gmail.com
office: 22.2.18                 |    ext: 23887
Dep. de Engenharia Mecânica, Universidade de Aveiro
*Campus Universitário de Santiago, 3810-193  Portugal*

**Comment by aaguiar96** [comment]
@miguelriemoliveira  do you know this? https://github.com/cburbridge/python_pcd

**Comment by miguelriemoliveira** [comment]
Hi @aaguiar96 ,

yes. There is a problem with that one which is all point clouds must be xyz only, no rgb.

In any case for the lidar perhaps it is enough.

**Comment by aaguiar96** [comment]
Hi @miguelriemoliveira  and @eupedrosa 

So, ILCC has three main scrips:

1. One to detect the corners of the pattern on images
2. One to detect the corners of the pattern on the pointcloud
3. The optimization script

I already run 1. and 2. with success.
I'm stuck at three... It requires `opengv` but they use python2. I can only install opengv for python3...
Any ideas? Does someone know how to install opengv for python2 or any other workaround?

**Comment by eupedrosa** [comment]
How did you try to install `opengv`, apt or pip?

**Comment by aaguiar96** [comment]
> How did you try to install `opengv`, apt or pip?

None of that, I think it has to be from source.
But I came up with a solution. I made a version of the optimization script for python3, and it works...

**Comment by eupedrosa** [comment]
Great, so ILLC is working, right?

**Comment by aaguiar96** [comment]
> Great, so ILLC is working, right?

It is, but the optimization results are really bad. I am implementing some visualization tools to see what's going on.

**Comment by eupedrosa** [comment]
Try running with their dataset. They have one on GitHub.

**Comment by aaguiar96** [comment]
The marker cannot be found by the pointcloud corner detector...
I think we need a chessboard.

I can try to go to the lab and record the bagfile with the pointcloud of zed for ICP and with both patterns.
I just have to print the chessboard. What do you think?

**Comment by miguelriemoliveira** [comment]
I think @eupedrosa is right. You should try first with their dataset just to see if it runs well.

**Comment by aaguiar96** [comment]
Tested the calibration with ILCC's perspective dataset and it works.
Here's some pictures of the reprojection:

![0002_cal_backproj](https://user-images.githubusercontent.com/35901587/88941330-cd494780-d280-11ea-8b84-f648354c0f71.png)
![0003_cal_backproj](https://user-images.githubusercontent.com/35901587/88941333-cf130b00-d280-11ea-819e-dcd8170c213c.png)
![0004_cal_backproj](https://user-images.githubusercontent.com/35901587/88941342-cfaba180-d280-11ea-892b-59bc97702825.png)

**Comment by aaguiar96** [comment]
So, what should I do next?...

**Comment by eupedrosa** [comment]
This means the algorithm is working. Now you should try making it work with our datasets. If I remember correctly it was not working right? 

@miguelriemoliveira and @aaguiar96, should we meet to discuss this?

**Comment by aaguiar96** [comment]
> If I remember correctly it was not working right?

Yes. I'm almost certain that this is happening because the framework does not support charuco.



> @miguelriemoliveira and @aaguiar96, should we meet to discuss this?

Fine by me!

**Comment by eupedrosa** [comment]
> Yes. I'm almost certain that this is happening because the framework does not support charuco.

This is a problem... We need partial detections to make it work, otherwise it is a pain-in-the-a** to detect the chessboard.

**Comment by aaguiar96** [comment]
> This is a problem... We need partial detections to make it work, otherwise it is a pain-in-the-a** to detect the chessboard.

Eheh :-)

Can't we have a charuco and a chessboard side-by-side simultaneously in the same dataset? I know it is not ideal, but...

**Comment by eupedrosa** [comment]
OpenCVs's chessboard detector works with a charuco board, therefore, the same pattern can be detected by both detectors. The problem is that the chessboard detector needs to detect all corners for a valid detection. Unless, the chessboard detector also returns partial detections.

**Comment by aaguiar96** [comment]
PointCloud loaded from pcd file generated on atom. It has intensity.

![rviz_screenshot_2020_07_30-18_24_58](https://user-images.githubusercontent.com/35901587/88954267-05a55180-d292-11ea-81c6-cf912c447880.png)

So, I'll look into ILCC's code to see what's going one.
@eupedrosa can you send me the 50 collection dataset please?

**Comment by eupedrosa** [comment]
> @eupedrosa can you send me the 50 collection dataset please?

Check your email.

**Comment by aaguiar96** [comment]
> Check your email.

Thanks! :)

**Comment by eupedrosa** [comment]
@aaguiar96, don't forget to update your `OptimizationUtils` repo, it has changes that speeds ups the optimization.

**Comment by eupedrosa** [comment]
@aaguiar96 and @miguelriemoliveira, I believe this solution will not work with the charuco. If it uses the intensity to find the chessboard it will not work, because the white spaces are occupied with aruco markers. It will never detect the corners with the charuco, it has black where it expects white.

**Comment by aaguiar96** [comment]
> , I believe this solution will not work with the charuco. If it uses the intensity to find the chessboard it will not work, because the white spaces are occupied with aruco markers. It will never detect the corners with the charuco, it has black where it expects white.

Makes sense... So, should we use a chessboard?

**Comment by aaguiar96** [comment]
Can we close this for now?

**Comment by miguelriemoliveira** [comment]
Yes
