### ISSUE TITLE
Move all utilities functionalities from atom_calibration to atom_core

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#209]

**Comment by miguelriemoliveira** [comment]
Hi @aaguiar96 ,

I am working on this and to test I would need a recent agrob bagfile. Can you send me the bagfile

bag_file: "$ROS_BAGS/calibration-01-07-2020/calibration_2020-07-01-10-15-43_0.bag"

Thanks

**Comment by miguelriemoliveira** [comment]
Hi @aaguiar96 and @eupedrosa . Just fixed this, but it was a large commit. Pull before working again.

**Comment by aaguiar96** [comment]
> bag_file: "$ROS_BAGS/calibration-01-07-2020/calibration_2020-07-01-10-15-43_0.bag"

Hi @miguelriemoliveira 

Here: https://drive.google.com/file/d/1vJuBApSFSqjgWRJK47A7wwvQBK_ZucPd/view?usp=sharing
