### ISSUE TITLE
Test velo2cam calibration

### ISSUE THREAD

**Issue by aaguiar96** [lardemua/atom#217]
https://wiki.ros.org/velo2cam_calibration

**Comment by aaguiar96** [comment]
Can we close this for now?

**Comment by miguelriemoliveira** [comment]
Sure, please just add some detail as to why it did not work. If the information is in another issue point to it.

**Comment by aaguiar96** [comment]
This framework uses a pattern with circular wholes.
Not compatible with atom calibration.

Closing the issue.
