### ISSUE TITLE
Error visualizing LaserBeams

### ISSUE THREAD

**Issue by aaguiar96** [lardemua/atom#228]
Hi @miguelriemoliveira  and @eupedrosa 

Can you visualize the laser beams on rviz?
I'm getting this error:
```
Points should not be empty for specified marker type.
```

**Comment by miguelriemoliveira** [comment]
Hi @aaguiar96 ,

I think we removed the calculation of the laser beams and replaced it with the orthogonal distance to speed up the objective function. 

Now that we have a much faster objective function we could consider retrieving the beam distance ...

**Comment by miguelriemoliveira** [comment]
Do you want me to work on this?

**Comment by aaguiar96** [comment]
Not exacly what I wanted. 
I just wanted to visualize something like this:
![image](https://user-images.githubusercontent.com/35901587/91546512-76d03700-e91a-11ea-845f-9e9b7b44d826.png)

to show the impact of orthogonal distance before and after calibration on the paper.
But, if it implies too much work, it's not important, I can use other images!

**Comment by aaguiar96** [comment]
By "like this" I only meant adding the blue laser beams to our visualization system.

**Comment by miguelriemoliveira** [comment]
Hi @aaguiar96 ,

To be plotted we need to compute the blue lines first, and these were being computed in the beam distance code.

If your idea is to use the orthogonal distance, then I would use a different plot uniting each lidar data point to the closest point on the plane, i.e. the brown line in this image 

https://mathinsight.org/distance_point_plane

Makes sense?

**Comment by aaguiar96** [comment]
Ok, makes sense.
I'll try to make that code to work on rviz. 

Thank's @miguelriemoliveira, I think we can close the issue right?

**Comment by miguelriemoliveira** [comment]
Yes.
