### ISSUE TITLE
Add agrob videos to atom readme

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#238]
Hi @aaguiar96 ,

its your fault, you made really nice videos : - )

**Comment by miguelriemoliveira** [comment]
Hi @aaguiar96 , can you add these videos to the readme? If not please close the issue.

**Comment by aaguiar96** [comment]
Done!

Closing this.

**Comment by miguelriemoliveira** [comment]
Hi @aaguiar96 ,

They look great. Thanks.
