### ISSUE TITLE
Joint Hand eye bag file

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#239]
Hi @eupedrosa ,

I deleted the bag file for the joint hand eye, and now I need it to configure the calibration package.

Can you share again? This is the one I need ...

> AssertionError: /home/mike/bagfiles/ur10/both_eyes_2_2020-02-05-17-51-24.bag does not exist.

**Comment by eupedrosa** [comment]
Hi @miguelriemoliveira, check your email.

**Comment by miguelriemoliveira** [comment]
Thanks. I am downloading right now.
