### ISSUE TITLE
Problem with calibration visualization

### ISSUE THREAD

**Issue by aaguiar96** [lardemua/atom#252]
Hi @miguelriemoliveira 

I was able to run the entire pipeline (configure, collect data, calibration) but I am having trouble with visualization.

I can only see the pattern labels (etc) in `world` reference frame and not on `base_link`'s. Is this normal?

Also, check these images:

![rviz_screenshot_2021_03_01-11_56_21](https://user-images.githubusercontent.com/35901587/109494628-0b605100-7a86-11eb-9c5e-4b78f7fc0c84.png)
![rviz_screenshot_2021_03_01-11_56_33](https://user-images.githubusercontent.com/35901587/109494630-0c917e00-7a86-11eb-8070-5acf8f6f0ab8.png)

On the first, the patterns are very small, and on the second the tripod is gigantic...

**Comment by miguelriemoliveira** [comment]
Hi @aaguiar96 ,

thanks for working on this. I will try to take a look by this afternoon / night. Until there I wont have time.

The visualization is indeed broken, I did not have time to handle it yet.

The large tripod I know how to solve.

Will get back to you soon,
