### ISSUE TITLE
Initiate Daniela into ATOM

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#254]
Lets use mmtbot as example.

1. Install ATOM
2. Install mmtbot
3. download a bag file
4. Try the steps of the atom calibration pipeline
5. Set intial estimate
6. collect data
7. calibrate

**Comment by miguelriemoliveira** [comment]
Hi @danifpdra ,

I solved all pending issues this weekend. Can you work tomorrow? From 10h30 ou 11h? I am not sure when, but I can call when available ...

**Comment by danifpdra** [comment]
Hi @miguelriemoliveira ,

I can work tomorrow at that time, yes. But I haven't had much time to work this weekend. Is this ok with you or should I work by myself first? I can do it before our meeting.

**Comment by danifpdra** [comment]
@miguelriemoliveira, can you tell me where I can find the bag files?

**Comment by miguelriemoliveira** [comment]
No problem. We can meet anyway. I solved all problems, so I just want to
walk you through all the procedure so you can repeat it later on.

I have some urgency since I will have to start preparing SVPI classes soon,
so if you could meet tonight it would be even better ...

If not we meet tomorrow around 11h.

Thanks,
Miguel
*  Miguel Riem de Oliveira                                             *
Diretor de curso Mestrado Eng. Automação Industrial
email:    mriem@ua.pt    |    m.riem.oliveira@gmail.com
office: 22.2.18                 |    ext: 23887
Dep. de Engenharia Mecânica, Universidade de Aveiro
*Campus Universitário de Santiago, 3810-193  Portugal*

**Comment by miguelriemoliveira** [comment]
> @miguelriemoliveira, can you tell me where I can find the bag files?

Sure, you have some mmtbot bag files in the mmtbot readme page.

https://github.com/miguelriemoliveira/mmtbot

**Comment by danifpdra** [comment]
@miguelriemoliveira, tonight will be difficult for me, can we meet tomorrow morning?

**Comment by miguelriemoliveira** [comment]
Sure. Tomorrow I call you around 11h.

See you,
Miguel
*  Miguel Riem de Oliveira                                             *
Diretor de curso Mestrado Eng. Automação Industrial
email:    mriem@ua.pt    |    m.riem.oliveira@gmail.com
office: 22.2.18                 |    ext: 23887
Dep. de Engenharia Mecânica, Universidade de Aveiro
*Campus Universitário de Santiago, 3810-193  Portugal*

**Comment by danifpdra** [comment]
Fatal error opening the bagfile: [FATAL] [1615307465.689518373]: Error opening file: /opt/ros/noetic/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/daniela/bagfiles/mmtbot/21_02_2021.bag

@miguelriemoliveira, can you help me?

**Comment by miguelriemoliveira** [comment]
Hi @danifpdra ,

which command are you running when you get that error? (please edit the post above to include that information)

Also, do you have that bagfile? Where?

**Comment by danifpdra** [comment]
@miguelriemoliveira , I have the bagfile in the home/daniela/bagfiles/mmtbot folder. I created an env variable $ROS_BAGS pointing to to home/daniela/bafiles .

When I run roslaunch mmtbot_calibration set_initial_estimate.launch it give me a fatal error: FATAL] [1615309043.508660631]: Error opening file: /opt/ros/noetic/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/daniela/bagfiles/mmtbot/21_02_2021.bag

**Comment by miguelriemoliveira** [comment]
Hi @danifpdra ,

just a comment w.r.t. the style of posting. I usually do it like this, it is better to read:

@miguelriemoliveira , I have the bagfile in the **home/daniela/bagfiles/mmtbot** folder. I created an env variable $ROS_BAGS pointing to to **home/daniela/bafiles** (this is wrong, the g in bag is missing. Is it a typo?).

When I run:

`   roslaunch mmtbot_calibration set_initial_estimate.launch` 

it give me a fatal error: 

`FATAL] [1615309043.508660631]: Error opening file: /opt/ros/noetic/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/daniela/bagfiles/mmtbot/21_02_2021.bag`

**Comment by miguelriemoliveira** [comment]
Now about the content:

Which bagfile have you configured in your **mmtbot_calibration/calibration/config.yml**?

https://github.com/miguelriemoliveira/mmtbot/blob/d9fe3efc12f9b0a2ac221fd2c4aeca3b397edcbb/mmtbot_calibration/calibration/config.yml#L35-L39

**Comment by danifpdra** [comment]
Yes, it is a typo. Sorry.

I have the same bag configured in **mmtbot_calibration/calibration/config.yml**:

`bag_file: "$ROS_BAGS/mmtbot/21_02_2021.bag"

**Comment by miguelriemoliveira** [comment]
OK, how about your **$ROS_BAGS** environment variable. If you type  (in the same terminal as you are launching the set initial estimate)

`echo $ROS_BAGS`

what do you get?

Di you try replacing $ROS_BAGS by the absolute path (not a good solution, but just to try)

**Comment by danifpdra** [comment]
It outputs 

`/opt/ros/noetic/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/daniela/bagfiles`

It works when replaced with the absolute path.

**Comment by miguelriemoliveira** [comment]
that's not correct. Mine outputs (as it should):

/home/mike/bagfiles

How did you create this variable?

**Comment by danifpdra** [comment]
Like this:

`ROS_BAGS="/home/daniela/bagfiles"`

**Comment by miguelriemoliveira** [comment]
Where? .bashrc?

Mine is as follows:

export ROS_BAGS="/home/mike/bagfiles"
export ATOM_DATASETS="/home/mike/datasets"

This should be like this in the instructions ...

**Comment by danifpdra** [comment]
Yes, it was not right, it works now. Thank you and sorry for the trouble.

**Comment by miguelriemoliveira** [comment]
No problem.

**Comment by danifpdra** [comment]
Hi @miguelriemoliveira,

The charuco doesn't appear on the image. Am I doing something wrong?

![image](https://user-images.githubusercontent.com/47574905/110617549-bb704100-818d-11eb-9ce4-6a0476485e94.png)

**Comment by miguelriemoliveira** [comment]
Hi @danifpdra ,

lets create one issue for each new topic. It will be easier to find the problems later on. 

This issue should be named something like "problems with $ROS_BAG configuration".

And the last question should be an issue like "Cannot visualize charuco in cameras".

Please create this second issue and then I will respond there.

**Comment by miguelriemoliveira** [comment]
and sorry for being such a nit-picker, but I am really convinced the organization helps, especially in complex projects like this. 
Also, I am trying to teach you my methodologies so please be patient :  - )

**Comment by miguelriemoliveira** [comment]
This could also be closed?
