### ISSUE TITLE
Save repository release/tag

### ISSUE THREAD

**Issue by aaguiar96** [lardemua/atom#258]
Hi @miguelriemoliveira and @eupedrosa 

I was thinking... When will we make the first release of atom?
After testing and validating mmtbot, what is missing for the first stable release of our repo?

- [ ] OptimizationUtils (?) 
- [ ] ...

**Comment by miguelriemoliveira** [comment]
Hum, good question. I would say we should try to sync the submission (or the acceptance) of the new paper with the release.

Some functionalities that come to mind are, 2D lidar, RGBD cameras (depth component), better integration of optimization utils, I think we are close ...

**Comment by miguelriemoliveira** [comment]
@aaguiar96 , FYI me and @eupedrosa have a student working on an rviz plugin for atom https://github.com/MiguelDRPina/atom_rviz_plugin

**Comment by aaguiar96** [comment]
I @miguelriemoliveira 

I do not have access to that repo, but that is great. :-)

**Comment by eupedrosa** [comment]
I can create a release for the melodic version. It was working right?
However, I notice that ATOM's README does not have an install section. Should I add it??????

**Comment by miguelriemoliveira** [comment]
> I can create a release for the melodic version. It was working right?

well, that's complicated. It was, but I never know _..._

> However, I notice that ATOM's README does not have an install section. Should I add it??????

Yes it should, definitely, @danifpdra can I ask you to create one since you are doing the installation of atom right now?

**Comment by miguelriemoliveira** [comment]
> I @miguelriemoliveira
> 
> I do not have access to that repo, but that is great. :-)

I asked the student to invite you. You should receive an invitation soon.

**Comment by danifpdra** [comment]
Yes, I can add it.

**Comment by miguelriemoliveira** [comment]
> Yes, I can add it.

Thanks.
