### ISSUE TITLE
Charuco not appearing on camera image

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#259]
Hi @miguelriemoliveira,

When using the command

`roslaunch mmtbot_bringup sim.launch gui:=true`

The charuco doesn't appear on the camera image. Am I doing something wrong?

![image](https://user-images.githubusercontent.com/47574905/110618401-9fb96a80-818e-11eb-88f5-758771eff491.png)

**Comment by miguelriemoliveira** [comment]
OK, you should always write the command you are using ... I suspect it is the? 

`roslaunch mmtbot_bringup sim.launch gui:=false`

**Comment by danifpdra** [comment]
gui:=true. I already edited the initial comment.

**Comment by miguelriemoliveira** [comment]
Ok, so what do you see in the gazebo frontend? Where is the pattern? Can you post a screenshot of gazebo?

**Comment by danifpdra** [comment]
The pattern does not appear in gazebo.

![image](https://user-images.githubusercontent.com/47574905/110621778-84e8f500-8192-11eb-89d2-0e78dfb547b4.png)

**Comment by miguelriemoliveira** [comment]
OK, what the code is doing is sending the pose of the pattern to the gazebo. Sometimes (I could not understand why) the communication between the rviz and the gazebo fails. The initial pose of the pattern in  gazebo is  under the ground, which is why you don't see it.

Try one of these:

1. move the pattern around in rviz (using the pattern's interactive marker) and see if gazebo updates
2. Just for testing, try to move the pattern in gazebo. Do you know how? Select the pattern from the tree on the left side, then select the manipulate object and move the pattern. If you want I can record a small video...

**Comment by miguelriemoliveira** [comment]
Just an additional comment: The charuco should appear only in the world camera, since the hand camera is pointing to the ground.
After solving the first issue and seeing the charuco in the world camera, you must then move the manipulator (using moveit) to point the hand camera to the pattern.

**Comment by danifpdra** [comment]
The hand camera is not point to the ground: 

![image](https://user-images.githubusercontent.com/47574905/110622579-8ff05500-8193-11eb-9aa4-6eedf68ddf69.png)


I have already tried to move the pattern in rviz but it does not update in the gazebo. I can't move the pattern in gazebo because it is not there. I selected from the tree and it points to nothing.

**Comment by miguelriemoliveira** [comment]
> The hand camera is not point to the ground:

Right, you moved the arm already. My bad.

About the gazebo, I will post a video in a moment.

**Comment by miguelriemoliveira** [comment]
One possibility is that your machine is not good enough. Can you post your specs? Also, what is the reported Real time factor in gazebo? Mine is 0.4 ...

**Comment by danifpdra** [comment]
Mine is 0.29

**Comment by danifpdra** [comment]
![image](https://user-images.githubusercontent.com/47574905/110624325-f0809180-8195-11eb-8287-095b36411767.png)

**Comment by miguelriemoliveira** [comment]
See if this helps https://youtu.be/L_e2gHEY4BM

**Comment by miguelriemoliveira** [comment]
About the computer ... it is a fantastic ... torradeira : -)

**Comment by miguelriemoliveira** [comment]
export GAZEBO_MODEL_PATH="`rospack find mmtbot_gazebo`/models:${GAZEBO_MODEL_PATH}"

**Comment by miguelriemoliveira** [comment]
This is working now, according to @danifpdra .
