### ISSUE TITLE
Do we stilld need to publish the agrob wheels transforms?

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#261]
Hi @aaguiar96 ,

Because we could not see agrob's wheels I did this in the visualization (which, apart from this, is completely general). 

https://github.com/lardemua/atom/blob/db1a402516fa95782bbe493bf72f4ca5d5b1915d/atom_calibration/src/atom_calibration/calibration/visualization.py#L452-L465

But I would like to remove. Do you know if we still need this? Do you have the agrob joint states for the wheels?

We should solve it when recording the agrob file ...

**Comment by aaguiar96** [comment]
Hi @miguelriemoliveira 

You can delete that code. I will create four static transforms in the `agrob` package to solve this as soon as I have some time.
It is a better workaround since it does not requires hardcode in atom.

**Comment by miguelriemoliveira** [comment]
Exactly! Thanks.

**Comment by aaguiar96** [comment]
Closed with https://github.com/aaguiar96/agrob/commit/171c30faac76cef9a74fac3fbdb1a4c01b99c314.
