### ISSUE TITLE
Instructions for evaluating on readme

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#262]
Hi @aaguiar96 ,

could you write down some instructions on how to evaluate the results of a calibration and compare them against the standard methods?

If you did this we could ask @danifpdra to validate those instructions by  evaluating  the calibration of mmtbot.

Is that a good idea?

**Comment by aaguiar96** [comment]
I @miguelriemoliveira 

Yes, it is a good idea.
I will do that soon.

**Comment by miguelriemoliveira** [comment]
Hi @aaguiar96 ,

just remembered. This is not yet migrated to python3. 

Can you do it?

@danifpdra , when you have them send two datasets to @aaguiar96 (calibrated train and test) so he can try the code.

**Comment by aaguiar96** [comment]
Yes @miguelriemoliveira, I'll do it. :-)

**Comment by miguelriemoliveira** [comment]
Thanks!

**Comment by aaguiar96** [comment]
Hi @miguelriemoliveira  and @danifpdra 

I migrated the `atom_evaluation` code to python3 and tested the three scripts with a mmtbot test calibration.
It worked really well.

I will now explain the process on the readme file.

**Comment by miguelriemoliveira** [comment]
Great news. How did you get the datasets? You made some by yourself?

**Comment by aaguiar96** [comment]
> Great news. How did you get the datasets? You made some by yourself?

Yes, I made one just for test purposes.

**Comment by aaguiar96** [comment]
Done! 

@danifpdra let me know if you have any doubt.

**Comment by miguelriemoliveira** [comment]
Thanks @aaguiar96 ,

I looked at it and it looks really nice.

Thanks. @danifpdra its on you. Let us know if you need something else.
