### ISSUE TITLE
shebang line for python3

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#267]
Hi @eupedrosa @danifpdra and @aaguiar96 ,

In my system, the shebang line 

`#!/usr/bin/env python`

calls python2. Not sure if that's just my system configuration, but I would propose to force running with python3 
by changing the shebang line of our scripts to 

`#!/usr/bin/env python3`

Makes sense? You opinion?

**Comment by eupedrosa** [comment]
Yes, it makes sense.

**Comment by miguelriemoliveira** [comment]
Working.
