### ISSUE TITLE
Camera to camera evaluation script improvements

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#268]
Hi @aaguiar96 ,

could we change the convention displayed in the images for the **camera_to_camera_evalutation.py**

![image](https://user-images.githubusercontent.com/11350998/111640206-e3961a80-87f3-11eb-8e3b-4d17eb032bdb.png)

Could we change + to dots? Because that's the convention we use in the calibrate script, and it should be uniform.

**Comment by miguelriemoliveira** [comment]
Could you also check that the target and source sensors exists and output accordingly if they don't?
Right now I get:

```
in <module>
    K_s[0, :] = train_dataset['sensors'][source_sensor]['camera_info']['K'][0:3]
KeyError: 'hand_camera'
```

Thanks.

**Comment by miguelriemoliveira** [comment]
Another error:

```
Traceback (most recent call last):
  File "/home/mike/catkin_ws/src/calibration/atom/atom_evaluation/scripts/camera_to_camera_evalutation.py", line 187, in <module>
    for collection_key, collection in test_dataset['collections'].items():
RuntimeError: dictionary changed size during iteration

```

I had the same error when passing to python3, you want me to fix it?

**Comment by miguelriemoliveira** [comment]
Lets use meters always ... SI forever!

**Comment by aaguiar96** [comment]
This is also closed.
