### ISSUE TITLE
Add tictoc to calibration output

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#274]
Hi @miguelriemoliveira,

Can you add a tictoc to the calibration output?

**Comment by miguelriemoliveira** [comment]
Sure, will work on it soon.

**Comment by miguelriemoliveira** [comment]
Now the optimization code will print:

```
-----------------------------
Optimization finished in 1.66824 secs: `xtol` termination condition is satisfied.
```

Will also include information about the time of execution (of the complete batch command) for #273.
