### ISSUE TITLE
organization of code of results for a paper or robot

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#282]
Hi @danifpdra,

About the new results for mmtbot. I already had this in mind for the papers of @eupedrosa and @aaguiar96 .
The problem is that the results, unlike everything else, are lost in the computers of the person which is taking the results. I discussed with @eupedrosa some alternatives, but in the end we did not advance.

This is what I think we need.:

1. a single place where the data, the scripts to process the data (or configurations for standard scripts are located)
2. Typically the data is very large, so perhaps it could be on a google drive or one drive and there should be a script to download it to a standard location

So I propose that we create a git repository (or add a new folder or package to existing repos) which would contain this.

The mmtbot example:

A new mmtbot_evaluaton folder should contain
 - scripts for downloading the data, processing the results in batch (the batch config yml should be here)
 - results a folder with the results

Any other ideas? Something missing here?

**Comment by miguelriemoliveira** [comment]
@danifpdra what is your opinion about this? If you agree I can reorganize, no problem.

**Comment by danifpdra** [comment]
Hi @miguelriemoliveira  ,

I agree with you. I think the data should be available for all. Your solution seems good.

**Comment by miguelriemoliveira** [comment]
Hi @danifpdra ,

do you want me to start with this reorganization? I can give it a try ...

**Comment by danifpdra** [comment]
hi @miguelriemoliveira,

As you wish. Do you prefer if I do it? I can do it if you want.

**Comment by miguelriemoliveira** [comment]
I will do the first round and then you adjust as you want ok? Do you have everything pushed?

**Comment by danifpdra** [comment]
I've just pushed everything now.

**Comment by miguelriemoliveira** [comment]
Hi @danifpdra ,

I have the first proposal. All the things are in mmtbot_experiments. There is a global readme and a readme for each experiment.

What is missing: 
1. Checking the datasets and bagfiles. You are not using mine, we are already desynced which is another reason to get this up and running.
2. Adding a folder with the results. That folder we were putting inside the dataset older should be in this repo I think ...

Can you do these two?

... and give comments and suggestion to improve ...

**Comment by miguelriemoliveira** [comment]
Closing...
