### ISSUE TITLE
Integration with Rviz Panel - Collect Data - Get collection state

### ISSUE THREAD

**Issue by MiguelDRPina** [lardemua/atom#288]
We should be able to show the collections made.

**Comment by miguelriemoliveira** [comment]
Hi @MiguelDRPina ,

could I ask you to create an issue for grouping all the issues in Integration with Rviz Panel - Collect Data, as in

https://github.com/lardemua/atom/issues/279

Because we have a lot of issues now, and it would be helpful...

**Comment by MiguelDRPina** [comment]
Hi @miguelriemoliveira ,

Done (issue #290)

**Comment by miguelriemoliveira** [comment]
> Done (issue #290)

Thanks

**Comment by miguelriemoliveira** [comment]
Hi @MiguelDRPina ,

I implemented the service https://github.com/lardemua/atom/blob/noetic-devel/atom_msgs/srv/GetDataset.srv

I hesitated back and forth and ended up deciding that it made no sense for the python code data_collector to be filtering the information in the dataset. Might as well send you everything and then you decide what you need and take it. 
So the solution was for the service to send the complete json string which describes a dataset (the content of a data_collected.json file in a dataset).

Granted, this way you get the burden of having to parse a json and navigate it. To make  things easier I looked around on how this could be done and made a cpp example of calling the service and parsing the json in the response. 

Lets use this cpp json parser https://github.com/nlohmann/json (nothing to install. Just added the hpp to our repo).
The test code from where you can see how you can integrate is 
https://github.com/MiguelDRPina/atom_rviz_plugin/blob/main/atom_rviz_plugin/src/test_json_parser.cpp

Let me know if you need some help.

**Comment by MiguelDRPina** [comment]
Hi @miguelriemoliveira ,
Ok, thank you. I will take a look into it and I'll say something if I need to.

**Comment by MiguelDRPina** [comment]
Hello @miguelriemoliveira ,

I only had a chance to work on this issue this morning, and I am running into some errors. 

I have ran the launchfile for the data collect, saved a few collections and ran the [file](https://github.com/MiguelDRPina/atom_rviz_plugin/blob/main/atom_rviz_plugin/src/test_json_parser.cpp) you made and it all printed out fine. But then I tried just parsing the json file in the [data_collect.cpp](https://github.com/MiguelDRPina/atom_rviz_plugin/blob/main/atom_rviz_plugin/src/data_collect.cpp) file using your code and for some reason I am getting an error. I tried running the code in the same function that publishes the message to save the collection (when the save button is clicked), but then I also created a button to separate both actions, thinking it would make a difference. It didn't.

Do you know what I could be missing?

**Comment by miguelriemoliveira** [comment]
Hi @MiguelDRPina ,

when you run in the data_collect.cpp, is the service call responded successfully, or does it fail?

**Comment by MiguelDRPina** [comment]
I am not 100% sure, since I am running with the launchfile I can't see what is being printed in the terminal. But I would assume so, because if I comment everything after calling the service, there's no error.
The Rviz crashes only when I insert this line:
```ruby
json j = json::parse(srv.response.dataset_json);
```

**Comment by miguelriemoliveira** [comment]
> I am not 100% sure, since I am running with the launchfile I can't see what is being printed in the terminal. 

you should fix this, otherwise it will be very difficult to debug.

Your code is running inside rviz, and since we are launching rviz with a launch file we must make sure the output of the node is being redirected to the terminal, i.e., this line should have a **output="screen"**

https://github.com/miguelriemoliveira/mmtbot/blob/8dc4f873b80d95b13359079b7fc9360cf8543908/mmtbot_calibration/launch/playbag.launch#L62

Try again and let me know if the service is successfully called or not...

**Comment by MiguelDRPina** [comment]
Yes, service called successfully. And the json file is saved on output_folder. The error appears with that line I mentioned.

**Comment by miguelriemoliveira** [comment]
and what's the output of this?

`ROS_INFO("srv.response.dataset_json=%s", srv.response.dataset_json.c_str());`

**Comment by MiguelDRPina** [comment]
![Screenshot from 2021-04-26 15-33-35](https://user-images.githubusercontent.com/73201389/116100466-da2a8880-a6a4-11eb-8ab6-ff8032c0f1dd.png)

**Comment by miguelriemoliveira** [comment]
Hi @MiguelDRPina ,

not sure I understand your response ...  where is the text?

"srv.response.dataset_json = blablabla ..."

from line https://github.com/MiguelDRPina/atom_rviz_plugin/blob/f2618c191b0b77fbe2b3864910c32ce6195b1257/atom_rviz_plugin/src/data_collect.cpp#L43

Did you change the launch file as described here?

> you should fix this, otherwise it will be very difficult to debug.
> 
> Your code is running inside rviz, and since we are launching rviz with a launch file we must make sure the output of the node is being redirected to the terminal, i.e., this line should have a output="screen"
> 
> https://github.com/miguelriemoliveira/mmtbot/blob/8dc4f873b80d95b13359079b7fc9360cf8543908/mmtbot_calibration/launch/playbag.launch#L62
> 
> Try again and let me know if the service is successfully called or not...

**Comment by MiguelDRPina** [comment]
I did change the launchfile. And I highlighted the line you asked (first line in the terminal).

**Comment by miguelriemoliveira** [comment]
ah ... sory, did not see it. Better to copy paste the terminal's output rather than posting an image. Its much easier to spot and copy paste.

In any case, this is the problem, your json is empty.

The procedure is: 

1. launch
`roslaunch mmtbot_calibration collect_data.launch  output_folder:=/home/mike/datasets/mmtbot/tmp overwrite:=true`

2. get at least one collection by setting the save (use the right button click on the sphere's  to make sure it works)

3. Then call the service to getDataset

it should work like this ... are you doing like this?

**Comment by MiguelDRPina** [comment]
Well, the way I was doing was: in the function connected to the event of clicking the save Button I had created in the panel (in issue #287) I would call the service and try to read the json so I could then add the collection to the treeWidget in the panel.

**Comment by MiguelDRPina** [comment]
Ok, I have now tried separately again (one button just to save the collection and one where I call the service and parse the json file just like you did) and it worked. It wasn't working when I tried earlier. But then my question is why can't I do all of this in the same function? 
Because for me it makes sense that, as I click on the button to save the collection, that collection would be added to the tree list. And that means I would have to parse the json file in the same function as the one I use to save the collection.

**Comment by miguelriemoliveira** [comment]
It should work as you have but I am not sure. If you do it as I suggest does it work?

**Comment by miguelriemoliveira** [comment]
Push your code so I can try it ...

**Comment by miguelriemoliveira** [comment]
You, it should work in the same, but let me check from my side ...

**Comment by MiguelDRPina** [comment]
Code is pushed. The way it is right now is the way that works (parsing the json in a separate function). If you want the way it doesn't work, just uncomment the commented part on the save function.

**Comment by miguelriemoliveira** [comment]
OK, thanks. A moment please ...

**Comment by miguelriemoliveira** [comment]
I am stuck on #291 can you see what's wrong with that so I can test?

**Comment by miguelriemoliveira** [comment]
I think I know what's happening. The idea is that two functionalities are called in sequence:

1. save a new collection
2. get the state of all collections

The problem is that we are using a message publication for 1. which does not tell us when the process of saving the collection is finished. Note that you should only go into 2. when the collection has finished saving. Having a publish / subscribe does not give this information. I will implement a service for 1. and then all should work fine.

...

**Comment by MiguelDRPina** [comment]
Ok, thank you.

**Comment by miguelriemoliveira** [comment]
Done. Tested it. Should work fine. Already changed the data_collect.cpp to call the service. Check it. 

Back to you ...

**Comment by MiguelDRPina** [comment]
Seems to be working fine, I'll work on it from here. Thank you again.

**Comment by miguelriemoliveira** [comment]
No problem. It is a pleasure to code a bit ...

**Comment by MiguelDRPina** [comment]
Hello @miguelriemoliveira,

Just 2 quick questions.
```ruby
      for (auto& collection: j["collections"].items()) // iterates over all collections
      {
        for (auto& sensor: collection.value().at("labels").items()) { // iterates over all sensors in this label
          QTreeWidgetItem *childLevel2TreeItem = new QTreeWidgetItem();
          childLevel2TreeItem->setText(0, "sensor ");
          childLevel1TreeItem->addChild(childLevel2TreeItem);
        }
      }
```
In your json parser, you have 2 cycles like this (forget what's inside the cycles). The first cycle is iterating over the sensors of all collections, but the way I am doing I wanted to iterate over all sensors of JUST the one collection that I am adding when I click on the save button (I have the index of the desired collection). How can I do that?

Second question is, besides the collections, each respective sensors and if they were labeled or not, is there any other thing from the json file you or @eupedrosa would like to see on the tree?

**Comment by miguelriemoliveira** [comment]
Hi @MiguelDRPina ,

the collections are named with numbers, i.e. 0,1,2,3, ... .

The last saved one is the highest number. You could use this...

So just print all collection names

 ```
for (auto& collection: j["collections"].items()) // iterates over all collections
 {
count << collection.key() << endl;
}
```

an figure out a way to get the largers value for key (you probably have to convert to numeric to compare).

A tip: copy the contents of the data_collected.json file you have from a dataset and paste them into 

https://jsoneditoronline.org/#left=local.yikeme&right=local.reqaji

It helps you visualize the structure in the json.

> Second question is, besides the collections, each respective sensors and if they were labeled or not, is there any other thing from the json file you or @eupedrosa would like to see on the tree?

hum, not sure for now. Just show that information and then we'll probably remember more stuff... @eupedrosa , any ideas?
