### ISSUE TITLE
Error launching calibration panel

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#291]
Hi @MiguelDRPina,

I can't run .when launching

`roslaunch mmtbot_calibration collect_data.launch  output_folder:=/home/mike/datasets/mmtbot/tmp overwrite:=true`

I get this error 

```
terminate called after throwing an instance of 'YAML::BadFile'.978000               
  what():  bad file
```

when I launch the atom calibration panel ...any idea what's wrong?

**Comment by MiguelDRPina** [comment]
Yes. Change the file path in line 22 of the [read_write_config](https://github.com/MiguelDRPina/atom_rviz_plugin/blob/f2618c191b0b77fbe2b3864910c32ce6195b1257/atom_rviz_plugin/src/read_write_config.cpp) to your config.yaml absolute path.

**Comment by MiguelDRPina** [comment]
I intend on maybe having the path being given within the panel, but for now I am setting it in the code.

**Comment by miguelriemoliveira** [comment]
OK, but you should set that so that it does not break the code. Something like if text is empty do not run these functionalities ...
