### ISSUE TITLE
Integration with Rviz Panel - set initial estimate - calling service to get the state of visible and marker scale

### ISSUE THREAD

**Issue by MiguelDRPina** [lardemua/atom#293]
Hi @miguelriemoliveira ,
Can you add a new service that, when called, returns the current state of the services 'visible' and 'scale' (addressed here: https://github.com/lardemua/atom/issues/278)?

**Comment by miguelriemoliveira** [comment]
Hi @MiguelDRPina ,

done. It's a new service called **/set_initial_estimate/\<sensor\>/get_sensor_interactive_marker**

example:

`rosservice call /set_initial_estimate/world_camera/get_sensor_interactive_marker "{}"`

returns:

```
visible: True
scale: 0.5
```

**Comment by miguelriemoliveira** [comment]
Please transfer this issue to the ATOM repository.

**Comment by miguelriemoliveira** [comment]
This is the commit that solves this issue: https://github.com/lardemua/atom/commit/8f7224b830903e6e0d208e81c9d42ae2113df1c4

**Comment by miguelriemoliveira** [comment]
Passing to you Miguel for integration with rviz pannel.

**Comment by MiguelDRPina** [comment]
Hi @miguelriemoliveira ,
Thank you, I will integrate with the panel today.
As for transferring this issue to the ATOM repository, I don't know if there's any sort of permission you need to give me to be able to do so, but when I go to Transfer Issue, it doesn't let me transfer it.

**Comment by miguelriemoliveira** [comment]
Try again. I just added you to the atom repo.

**Comment by MiguelDRPina** [comment]
Still doesn't appear as an transfer option...
![Screenshot from 2021-04-13 14-59-14](https://user-images.githubusercontent.com/73201389/114565147-e8ba7e00-9c68-11eb-9a96-e97b44224fed.png)

**Comment by miguelriemoliveira** [comment]
did you accept the collaboration invitation first? Did you receive any in
your email?


*  Miguel Riem de Oliveira                                             *
Diretor de curso Mestrado Eng. Automação Industrial
email:    ***@***.***    |    ***@***.***
office: 22.2.18                 |    ext: 23887
Dep. de Engenharia Mecânica, Universidade de Aveiro
*Campus Universitário de Santiago, 3810-193  Portugal*

**Comment by miguelriemoliveira** [comment]
I was looking around

https://docs.github.com/pt/github/managing-your-work-on-github/transferring-an-issue-to-another-repository

I think only in some special cases we can transfer. Anyway, the best is to create the issues always in ATOM.

For this particular case lets just leave it here, agree?

**Comment by MiguelDRPina** [comment]
Right, from now on I will create my issues there.

**Comment by MiguelDRPina** [comment]
Hi @miguelriemoliveira ,
```
      std::string combobox_sensor = ui_->initEstimateSensorsComboBox->currentText().toUtf8().constData();
      std::string service_name = "/set_initial_estimate/" + combobox_sensor + "/get_sensor_interactive_marker";

      ros::ServiceClient client = nh.serviceClient<atom_msgs::GetSensorInteractiveMarker>(service_name);
```

Doing this, I am getting the following ERROR message:
error: ‘GetSensorInteractiveMarker’ is not a member of ‘atom_msgs’; did you mean ‘SetSensorInteractiveMarker’ .

Do you know what could be wrong? The code is committed if you want to take a better look at it.

**Comment by miguelriemoliveira** [comment]
I am on it ...

**Comment by miguelriemoliveira** [comment]
You were missing the include for the get service

`#include <atom_msgs/GetSensorInteractiveMarker.h>`

**Comment by MiguelDRPina** [comment]
Yes, I was. Thank you.

**Comment by MiguelDRPina** [comment]
Already getting the states of each service as desired. Thanks for the help. Closing the issue...

**Comment by miguelriemoliveira** [comment]
Hi @MiguelDRPina ,

I transferred the repo to the lardemua organization, which is the official group of the DEM Robotics group. Here it is:

https://github.com/lardemua/atom_rviz_plugin

I gave you admin permissions on this repo.

After this I was able to transfer the issues to the atom. Here they are:

https://github.com/lardemua/atom/issues/293
https://github.com/lardemua/atom/issues/294
https://github.com/lardemua/atom/issues/292

I recommend that you remove the atom_rviz code from the repo (make a backup before) and clone it again from the lardemua owner. 

I think that's it no? Do you need anything else?

**Comment by MiguelDRPina** [comment]
That's it, yes. Thank you.
