### ISSUE TITLE
Integration with Rviz Panel - Adding GUI as a new display instead of a new panel

### ISSUE THREAD

**Issue by MiguelDRPina** [lardemua/atom#294]

**Comment by miguelriemoliveira** [comment]
Hi @MiguelDRPina ,

did you find / try any tutorial for this? 

I can search some if you want, but tell what you already tried ...

**Comment by MiguelDRPina** [comment]
Hi @miguelriemoliveira , 

I have tried several, I don't have the links to all of them, some that I can remember are the following (there's more that I am forgetting to link and not all of them are exclusively for new display type, but I tried to adapt them):
http://docs.ros.org/en/indigo/api/rviz_plugin_tutorials/html/index.html
https://qiita.com/RyodoTanaka/items/4924af4f7b1e91f3a5b9   (this one is in japanese but I translated the page)
https://qiita.com/srs/items/343f859d7b741ccd5711
http://wiki.ros.org/rqt/Tutorials/Writing%20a%20C%2B%2B%20Plugin

As I said in issue lardemua/atom_rviz_plugin#4 I also tried to look into the MoveIt plugins, but also with not a lot of success.

**Comment by miguelriemoliveira** [comment]
Thanks. I will try to find some time to look into it and let you know.

**Comment by miguelriemoliveira** [comment]
Hi @MiguelDRPina ,


the first one you mention 

http://docs.ros.org/en/indigo/api/rviz_plugin_tutorials/html/display_plugin_tutorial.html

seems to do what we want. 

![image](https://user-images.githubusercontent.com/11350998/111029151-f1fac580-83f2-11eb-8e25-4907c35b82ae.png)

Could you make it work as is? If not, what was the problem?

**Comment by MiguelDRPina** [comment]
I am able to create a new DisplayType. My problem is that most of the displays examples that I found are like that one you are showing, where you can see and alter properties like color, etc, and I want a display where I can see the actual GUI (just like with the panel, where I was able to add the .ui file). 

From everything I tried so far the one that I actual think I got close to (at least it was the only where I was actually able to run catkin_make until the end without an error) was the first one I tried, where I just did a very similar thing to what I did when adding the panel. But then I got an error in the RViz, like this:

![Screenshot from 2021-03-13 12-22-17](https://user-images.githubusercontent.com/73201389/111029968-a39bf580-83f7-11eb-985d-fe0f87a7ff35.png)

I just added this package to the repository (https://github.com/MiguelDRPina/atom_rviz_plugin/tree/main/new_display), maybe you know what the error is.

**Comment by miguelriemoliveira** [comment]
Hi @MiguelDRPina , ok I can try.

The only plugin I remember has a panel associated with a new display is the moveit plugin ...

**Comment by miguelriemoliveira** [comment]
Not sure if you've seen this already ...
https://github.com/ros-visualization/visualization_tutorials/tree/noetic-devel/rviz_plugin_tutorials

**Comment by miguelriemoliveira** [comment]
Hi @MiguelDRPina , 

I was looking around and found some interesting stuff:

This I think will be your bible for the next few months
http://docs.ros.org/en/hydro/api/rviz/html/c++/index.html

They talk about displays and panels here
http://library.isr.ist.utl.pt/docs/roswiki/rviz(2f)PluginAPI.html#Changes_to_Plugin_API

An example of a general plugin with a panel.
https://github.com/davetcoleman/moveit_dashboard

Also discussing panels
https://github.com/ros-visualization/rviz/issues/480

I was thinking about your problem and remembered the image display type does exactly what we need. When activated It creates a panel (which contains only the image stream, but we can add whatever).

I searched around to find that source code for the Image display but could not find it. Perhaps here:
https://github.com/ros-visualization/rviz

I also found some other custom rviz displays for cameras 
https://github.com/futureneer/zod_rviz_plugin
https://github.com/jkammerl/depth_image_rviz_plugin

Hope that helps

**Comment by miguelriemoliveira** [comment]
> I am able to create a new DisplayType. My problem is that most of the displays examples that I found are like that one you are showing, where you can see and alter properties like color, etc, and I want a display where I can see the actual GUI (just like with the panel, where I was able to add the .ui file).
> 
> From everything I tried so far the one that I actual think I got close to (at least it was the only where I was actually able to run catkin_make until the end without an error) was the first one I tried, where I just did a very similar thing to what I did when adding the panel. But then I got an error in the RViz, like this:
> 
> ![Screenshot from 2021-03-13 12-22-17](https://user-images.githubusercontent.com/73201389/111029968-a39bf580-83f7-11eb-985d-fe0f87a7ff35.png)
> 
> I just added this package to the repository (https://github.com/MiguelDRPina/atom_rviz_plugin/tree/main/new_display), maybe you know what the error is.

@eupedrosa can you help here?

**Comment by eupedrosa** [comment]
Just like before, clean the project, rebuild and re-source.
The plugin system is very sensitive to this kind of things.

**Comment by MiguelDRPina** [comment]
> Hi @MiguelDRPina ,
> 
> I was looking around and found some interesting stuff:
> 
> This I think will be your bible for the next few months
> http://docs.ros.org/en/hydro/api/rviz/html/c++/index.html
> 
> They talk about displays and panels here
> http://library.isr.ist.utl.pt/docs/roswiki/rviz(2f)PluginAPI.html#Changes_to_Plugin_API
> 
> An example of a general plugin with a panel.
> https://github.com/davetcoleman/moveit_dashboard
> 
> Also discussing panels
> [ros-visualization/rviz#480](https://github.com/ros-visualization/rviz/issues/480)
> 
> I was thinking about your problem and remembered the image display type does exactly what we need. When activated It creates a panel (which contains only the image stream, but we can add whatever).
> 
> I searched around to find that source code for the Image display but could not find it. Perhaps here:
> https://github.com/ros-visualization/rviz
> 
> I also found some other custom rviz displays for cameras
> https://github.com/futureneer/zod_rviz_plugin
> https://github.com/jkammerl/depth_image_rviz_plugin
> 
> Hope that helps

Thanks, I will look into all of these.

**Comment by MiguelDRPina** [comment]
> Just like before, clean the project, rebuild and re-source.
> The plugin system is very sensitive to this kind of things.

I have done that, just like we did the other day. Still didn't work.

**Comment by eupedrosa** [comment]
I think the problem is here:
https://github.com/MiguelDRPina/atom_rviz_plugin/blob/1471bbde9bee110e2258ec48f18649b8a4715dac/new_display/plugin_description.xml#L1-L9

I believe the plugin is not correctly defined. You can easilly comparare with the panel plugin:

https://github.com/MiguelDRPina/atom_rviz_plugin/blob/1471bbde9bee110e2258ec48f18649b8a4715dac/atom_rviz_plugin/plugin_description.xml#L1-L8

The properties `library` and `name` are wrong for the `new_display`.

**Comment by MiguelDRPina** [comment]
Hi @eupedrosa , 
I believe the name is right and I think the library can be defined both ways. Regardless, I changed them to match how I had defined the panel and rebuilt the package, but the error was the same.

**Comment by miguelriemoliveira** [comment]
Hi @MiguelDRPina ,

just to be sure ... after changing, did you remove the catkin_ws build and devel folders and then recompile again?

**Comment by MiguelDRPina** [comment]
Yes, I did. It must be something about the code itself, because it did look to simple the way the code is, and if it were that simple there would be more plugins made that way, instead of only the moveit one. I will keep trying to see if I can make this work, and in the meantime I will look into de rest of what I have to do.

**Comment by miguelriemoliveira** [comment]
Hi @MiguelDRPina ,

well, I said above that also the image display and the camera display also show a panel ... so its not just moveit, do you agree? Or is there some difference I am missing?

**Comment by MiguelDRPina** [comment]
You're right, there's that too. It doesn't seem to be done quite the same way as with the moveit, but it might work too. I'll keep looking into that.

**Comment by miguelriemoliveira** [comment]
Not relevant.
