### ISSUE TITLE
Integration with RViz Panel - Calibration

### ISSUE THREAD

**Issue by MiguelDRPina** [lardemua/atom#302]
Issue to discuss the Calibration Tab Widget.

**Comment by MiguelDRPina** [comment]
Hi @miguelriemoliveira, 

There's no hurry as I won't be using them right now, but when you can could you please send me some testing datasets?

**Comment by miguelriemoliveira** [comment]
Hi @MiguelDRPina ,

here it goes: 

https://drive.google.com/drive/folders/1pDKpNwdU-a49MY2BoGq7A9JkP3kHVPz6?usp=sharing

**Comment by MiguelDRPina** [comment]
Hello @miguelriemoliveira ,

I practically finished the Calibration Tab. I only have a few questions about some of the parameters. In the [calibration part of atom readme](https://github.com/lardemua/atom#calibrate-sensors), there are some arguments that I do not have on the panel because there is no explanation of what the arguments are. I have the following ones:
```
  -json JSON_FILE, --json_file JSON_FILE
                        Json file containing input dataset.
  -vo, --view_optimization
                        Displays generic total error and residuals graphs.
  -v, --verbose         Be verbose
  -rv, --ros_visualization
                        Publish ros visualization markers.
  -si, --show_images    shows images for each camera
  -oi, --optimize_intrinsics
                        Adds camera instrinsics and distortion to the optimization
  -pof, --profile_objective_function
                        Runs and prints a profile of the objective function,
                        then exits.
  -sr SAMPLE_RESIDUALS, --sample_residuals SAMPLE_RESIDUALS
                        Samples residuals
  -ss SAMPLE_SEED, --sample_seed SAMPLE_SEED
                        Sampling seed
  -uic, --use_incomplete_collections
                        Remove any collection which does not have a detection
                        for all sensors.
  -rpd, --remove_partial_detections
                        Remove detected labels which are only partial. Used or
                        the Charuco.
  -ssf SENSOR_SELECTION_FUNCTION, --sensor_selection_function SENSOR_SELECTION_FUNCTION
                        A string to be evaluated into a lambda function that
                        receives a sensor name as input and returns True or
                        False to indicate if the sensor should be loaded (and
                        used in the optimization). The Syntax is lambda name:
                        f(x), where f(x) is the function in python language.
                        Example: lambda name: name in ["left_laser",
                        "frontal_camera"] , to load only sensors left_laser
                        and frontal_camera
  -csf COLLECTION_SELECTION_FUNCTION, --collection_selection_function COLLECTION_SELECTION_FUNCTION
                        A string to be evaluated into a lambda function that
                        receives a collection name as input and returns True
                        or False to indicate if the collection should be
                        loaded (and used in the optimization). The Syntax is
                        lambda name: f(x), where f(x) is the function in
                        python language. Example: lambda name: int(name) > 5 ,
                        to load only collections 6, 7, and onward.
```

But in the ATOM repository there is also mentions of [-sv SKIP_VERTICES] [-z Z_INCONSISTENCY_THRESHOLD]  [-vpv] [-od] [-fec] [-rpd],...........
Should I add these too? If so, can you provide some information about them?

Also, from the ones I showed above that do have an explanation, most can be represented with just a checkbox since either they are called or not. From the ones that can't, the json file, ssf and csf ones are said to be a string. What about the Sample seed and sample residuals? How are these supposed to be called?

**Comment by MiguelDRPina** [comment]
And another thing, I am doing this based on the README because I can't run the calibration. When try to do: rosrun atom_calibration calibrate -h to see the arguments, I get the following error:
```
Traceback (most recent call last):
  File "/home/miguel/catkin_ws/devel/lib/atom_calibration/calibrate", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/miguel/catkin_ws/src/calibration/atom/atom_calibration/scripts/calibrate", line 19, in <module>
    import OptimizationUtils.OptimizationUtils as OptimizationUtils
ModuleNotFoundError: No module named 'OptimizationUtils'

```

How can I install this OptimizationUtils?

**Comment by miguelriemoliveira** [comment]
> But in the ATOM repository there is also mentions of [-sv SKIP_VERTICES] [-z Z_INCONSISTENCY_THRESHOLD] [-vpv] [-od] [-fec] [-rpd],...........
> Should I add these too? If so, can you provide some information about them?

These are not used and will be removed, so don't include them.


> Also, from the ones I showed above that do have an explanation, most can be represented with just a checkbox since either they are called or not. From the ones that can't, the json file, ssf and csf ones are said to be a string. What about the Sample seed and sample residuals? How are these supposed to be called?

An example here:

`rosrun atom_calibration calibrate -json ~/datasets/mmtbot/train_dataset/data_collected.json -csf 'lambda name: int(name) == 18' -nig 0.0 0.0 -ss 1 -uic -phased -rv -si
`

The csf and the ssf are strings which are evaluated as python expressions. For example, assume that I have a dataset with 20 collections, and I just want to run the calibration with the first 8 collections. The string for csf would be:

`...  -csf 'lambda name: int(name) < 8' ...`

but we could have an alternative way in which you would allow the user to select the collections he/she wants ... talk to me about it ...


Something else: I don't think you have all the parameters, because you are looking into the readme which is outdated. if you run the 

`rosrun atom_calibration calibrate -h`

You get the updated parameters.

**Comment by miguelriemoliveira** [comment]
BWT ... can you update the readme please?

**Comment by miguelriemoliveira** [comment]
> And another thing, I am doing this based on the README because I can't run the calibration. When try to do: rosrun atom_calibration calibrate -h to see the arguments, I get the following error:

Should have read this first ... did you install OptimizationUtils?

https://github.com/miguelriemoliveira/OptimizationUtils

Also, add this (addapted) to your .bashrc

`export PYTHONPATH="${PYTHONPATH}:/home/mike/workingcopy/OptimizationUtils" `

**Comment by miguelriemoliveira** [comment]
But so that you don't loose time here's the output of the 

`rosrun atom_calibration calibrate -h`

```bash
usage: calibrate [-h] [-sv SKIP_VERTICES] [-z Z_INCONSISTENCY_THRESHOLD] [-vpv] [-vo] -json JSON_FILE [-v] [-rv]
                 [-si] [-oi] [-pof] [-sr SAMPLE_RESIDUALS] [-ss SAMPLE_SEED] [-ajf] [-uic] [-rpd]
                 [-nig translation rotation] [-ssf SENSOR_SELECTION_FUNCTION] [-csf COLLECTION_SELECTION_FUNCTION]
                 [-phased] [-ipg] [-oj OUTPUT_JSON] [-ox OUTPUT_XACRO]

optional arguments:
  -h, --help            show this help message and exit
  -sv SKIP_VERTICES, --skip_vertices SKIP_VERTICES
                        skip vertices. Useful for fast testing
  -z Z_INCONSISTENCY_THRESHOLD, --z_inconsistency_threshold Z_INCONSISTENCY_THRESHOLD
                        threshold for max z inconsistency value
  -vpv, --view_projected_vertices
                        visualize projections of vertices onto images
  -vo, --view_optimization
                        ...
  -json JSON_FILE, --json_file JSON_FILE
                        Json file containing input dataset.
  -v, --verbose         Be verbose
  -rv, --ros_visualization
                        Publish ros visualization markers.
  -si, --show_images    shows images for each camera
  -oi, --optimize_intrinsics
                        Adds camera instrinsics to the optimization
  -pof, --profile_objective_function
                        Runs and prints a profile of the objective function, then exits.
  -sr SAMPLE_RESIDUALS, --sample_residuals SAMPLE_RESIDUALS
                        Samples residuals
  -ss SAMPLE_SEED, --sample_seed SAMPLE_SEED
                        Sampling seed
  -ajf, --all_joints_fixed
                        Assume all joints are fixed and because of that draw a single robot mesh. Overrides
                        automatic detection of static robot.
  -uic, --use_incomplete_collections
                        Remove any collection which does not have a detection for all sensors.
  -rpd, --remove_partial_detections
                        Remove detected labels which are only partial. Used or the Charuco.
  -nig translation rotation, --noisy_initial_guess translation rotation
                        Percentage of noise to add to the initial guess atomic transformations set before.
  -ssf SENSOR_SELECTION_FUNCTION, --sensor_selection_function SENSOR_SELECTION_FUNCTION
                        A string to be evaluated into a lambda function that receives a sensor name as input and
                        returns True or False to indicate if the sensor should be loaded (and used in the
                        optimization). The Syntax is lambda name: f(x), where f(x) is the function in python
                        language. Example: lambda name: name in ["left_laser", "frontal_camera"] , to load only
                        sensors left_laser and frontal_camera
  -csf COLLECTION_SELECTION_FUNCTION, --collection_selection_function COLLECTION_SELECTION_FUNCTION
                        A string to be evaluated into a lambda function that receives a collection name as input and
                        returns True or False to indicate if the collection should be loaded (and used in the
                        optimization). The Syntax is lambda name: f(x), where f(x) is the function in python
                        language. Example: lambda name: int(name) > 5 , to load only collections 6, 7, and onward.
  -phased, --phased_execution
                        Stay in a loop before calling optimization, and in another after calling the optimization.
                        Good for debugging.
  -ipg, --initial_pose_ghost
                        Draw a ghost mesh with the systems initial pose. Good for debugging.
  -oj OUTPUT_JSON, --output_json OUTPUT_JSON
                        Full path to output json file.
  -ox OUTPUT_XACRO, --output_xacro OUTPUT_XACRO
                        Full path to output xacro file.
```

**Comment by MiguelDRPina** [comment]
> > And another thing, I am doing this based on the README because I can't run the calibration. When try to do: rosrun atom_calibration calibrate -h to see the arguments, I get the following error:
> 
> Should have read this first ... did you install OptimizationUtils?
> 
> https://github.com/miguelriemoliveira/OptimizationUtils
> 
> Also, add this (addapted) to your .bashrc
> 
> `export PYTHONPATH="${PYTHONPATH}:/home/mike/workingcopy/OptimizationUtils" `

I installed it, but I got the same error when trying to run the rosrun atom_calibration calibrate -h .

**Comment by MiguelDRPina** [comment]
> But so that you don't loose time here's the output of the
> 
> `rosrun atom_calibration calibrate -h`


Thank you. And do I add all of these to the panel? Or do you think that some are not as practical to have in the panel?
![Screenshot from 2021-06-17 15-09-17](https://user-images.githubusercontent.com/73201389/122413604-6d35bf80-cf7e-11eb-8540-350df083ffca.png)

Right now, the panel is as shown in that image (so far only with the arguments that were on the outdated version that was in the readme). As you write/click on the checkboxes, the respective argument gets added/removed from the line edit below. The "Copy" button copies the content to the clipboard and can be pasted on the terminal. The "Calibrate" button would run the command directly.

**Comment by miguelriemoliveira** [comment]
Installing optimizationutils -> lets do a meeting for that.

If you have time, insert all the parameters that we have. Its more complete.

**Comment by miguelriemoliveira** [comment]
`As you write/click on the checkboxes, the respective argument gets added/removed from the line edit below. The "Copy" button copies the content to the clipboard and can be pasted on the terminal. The "Calibrate" button would run the command directly.`

Yep, that was the idea.
