### ISSUE TITLE
Error in batch execution

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#303]
Hi @miguelriemoliveira ,

I'm getting this error when trying to execute the batch execution. Can you help me out here?

`Traceback (most recent call last):
  File "./batch_execution", line 95, in <module>
    main()
  File "./batch_execution", line 83, in main
    if not os.path.exists(file):
  File "/usr/lib/python3.8/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType`

This is what I'm trying to run:

```
    - name: "partial_0"
      cmd: "{{ cmd_prefix }} -csf 'lambda name: int(name) in [0,3,5,7,9,10,11,12,15,16]' -nig 0.05 0.02 -ss 1"
      files_to_collect:
        - '{{ dataset_path }}/atom_calibration.json'
        -  '/tmp/optimized.urdf.xacro'
        -
    - name: "partial_1"
      cmd: "{{ cmd_prefix }} -csf 'lambda name: int(name) in [0,3,5,7,9,10,11,12,15,16,1]' -nig 0.05 0.02 -ss 1"
      files_to_collect:
        - '{{ dataset_path }}/atom_calibration.json'
        -  '/tmp/optimized.urdf.xacro'

    - name: "partial_3"
      cmd: "{{ cmd_prefix }} -csf 'lambda name: int(name) in [0,3,5,7,9,10,11,12,15,16,1,2,4]' -nig 0.05 0.02 -ss 1"
      files_to_collect:
        - '{{ dataset_path }}/atom_calibration.json'
        -  '/tmp/optimized.urdf.xacro'

    - name: "partial_6"
      cmd: "{{ cmd_prefix }} -csf 'lambda name: int(name) in [0,3,5,7,9,10,11,12,15,16,1,2,4,6,8,13]' -nig 0.05 0.02 -ss 1"
      files_to_collect:
        - '{{ dataset_path }}/atom_calibration.json'
        -  '/tmp/optimized.urdf.xacro'

    - name: "partial_9"
      cmd: "{{ cmd_prefix }} -csf 'lambda name: int(name) in [0,3,5,7,9,10,11,12,15,16,1,2,4,6,8,13,14,19,24]' -nig 0.05 0.02 -ss 1"
      files_to_collect:
        - '{{ dataset_path }}/atom_calibration.json'
        -  '/tmp/optimized.urdf.xacro' ```

**Comment by miguelriemoliveira** [comment]
Hi @danifpdra ,

can you post the entire contents of the config file?

**Comment by danifpdra** [comment]
here https://github.com/miguelriemoliveira/mmtbot/blob/main/mmtbot_experiments/01_initial_estimate_vs_error/batch_mmtbot_partial.yml

**Comment by miguelriemoliveira** [comment]
@danifpdra if you run with -v (verbose ) what do you see? (please git pull)

**Comment by danifpdra** [comment]
I am running in verbose mode.

```
Traceback (most recent call last):
  File "./batch_execution", line 95, in <module>
    main()
  File "./batch_execution", line 83, in main
    print(Fore.BLUE + Back.YELLOW + 'Moving file ' + file + ' to ' + filename_out + Style.RESET_ALL)
UnboundLocalError: local variable 'filename_out' referenced before assignment
```

**Comment by miguelriemoliveira** [comment]
how are you running the script ( BTW this should always be in the initial message of the issue)? 

I run with

`/home/mike/catkin_ws/src/calibration/mmtbot/mmtbot_experiments/01_initial_estimate_vs_error && rosrun atom_evaluation batch_execution -f batch_mmtbot.yml -v`

**Comment by miguelriemoliveira** [comment]
Wait, you give two different outputs ? Which one is it?

**Comment by danifpdra** [comment]
I deleted one. It's the last one. Sorry...

I'm running like this: `roscd atom_evaluation/scripts && ./batch_execution -v -f /home/daniela/catkin_ws/src/calibration/mmtbot/mmtbot_experiments/01_initial_estimate_vs_error/batch_mmtbot_partial.yml > partials.txt`

**Comment by miguelriemoliveira** [comment]
I found the problem: 

```
 - name: "partial_0"
      cmd: "{{ cmd_prefix }} -csf 'lambda name: int(name) in [0,3,5,7,9,10,11,12,15,16]' -nig 0.05 0.02 -ss 1"
      files_to_collect:
        - '{{ dataset_path }}/atom_calibration.json'
        -  '/tmp/optimized.urdf.xacro'
        -
```

the last dash defines a file to collect which has no name. When the script tries to find file "None" the error occurs. If you remove the dash then it should work. Also I added a more informative message when this happens.

**Comment by miguelriemoliveira** [comment]
Please close if solved.

**Comment by danifpdra** [comment]
I'm still getting the same problem after deleting the dash.

**Comment by danifpdra** [comment]
It works not after the latest commit. Thanks.

**Comment by miguelriemoliveira** [comment]
Great!
