### ISSUE TITLE
Unable to commit

### ISSUE THREAD

**Issue by MiguelDRPina** [lardemua/atom#305]
Hello @miguelriemoliveira ,

I decided to come work just for a little bit on some pending details about the interface and I have tried to commit, without success. And it turns out, the last time I came here (a few days ago), it apparently did not commit as well, but I hadn't noticed.

![Screenshot from 2021-06-11 23-35-59](https://user-images.githubusercontent.com/73201389/121755130-502c6700-cb0e-11eb-9fa0-59a6002420fb.png)

I don't know if the permissions were changed or anything. Could you please check that?

**Comment by miguelriemoliveira** [comment]
Hi Miguel

Did you pull? Do you have conflicts?

I can check it tomorrow.


Miguel

**Comment by MiguelDRPina** [comment]
Yes, I did pull. But I keep getting that error saying I do not have permission.

**Comment by MiguelDRPina** [comment]
Don't know if you changed anything or not, but somehow I was able to push now. Thank you.

**Comment by miguelriemoliveira** [comment]
Changed nothing. Great!
