### ISSUE TITLE
Improvement of atom_rviz_plugin readme

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#307]
Hi @MiguelDRPina ,

I suggest that you improve the readme with some photos or even videos of the calibration panel.
Use the atom readme as a model.

**Comment by MiguelDRPina** [comment]
Hello @miguelriemoliveira ,

Yes, I plan on doing so after I have everything in the panel done and the thesis fully written so I can try to do it properly without being in a rush.

**Comment by miguelriemoliveira** [comment]
Makes sense. I will set low priority then.
