### ISSUE TITLE
Problems with camera_to_camera_evaluation.py

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#310]
Hi @aaguiar96,

Me and @miguelriemoliveira were both having problems using the camera_to_camera_evaluation.py. Only worked when commenting this

https://github.com/lardemua/atom/blob/b3fdb58beca137552937b46d32f267b61edaf3c1/atom_evaluation/scripts/camera_to_camera_evalutation.py#L356

Can you take and look at this and see why it's not working?

**Comment by aaguiar96** [comment]
I @danifpdra

Thank you. I will take a look.

**Comment by miguelriemoliveira** [comment]
This is solved, right?
