### ISSUE TITLE
Create an atom dataset inspection tool

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#311]
Hi @danifpdra ,

I am doing this because I need to fill in the paper's table 2. 

Anything you can remember that would be interesting to see in a dataset let me know ...

**Comment by danifpdra** [comment]
Hi @miguelriemoliveira,

train-1 : 39 collections, 32 incomplete 

test-1 : 21 collections, 18 incomplete

I'm not sure if the -rpd flag is not working or if there are no partial detections. When I calibrate with or without -rpd it uses the same number of collections.

**Comment by miguelriemoliveira** [comment]
Thanks, can you check the style of table 2 of the paper., in particular the last collumn.

Some datasets say the partial collections, others dont.

Some have X collections, Y incimplete, Z partial
some others have X collections, Y incimplete Z of which are partial

Can you homogeneize please?

**Comment by danifpdra** [comment]
done

**Comment by miguelriemoliveira** [comment]
Thanks. The paper is getting better and better. Its great that we were able to get these new results for the atlascar2.

**Comment by danifpdra** [comment]
I agree. Fingers crossed that it's accepted.

**Comment by miguelriemoliveira** [comment]
Implemented a script that looks into the dataset and prints out some useful information.

![image](https://user-images.githubusercontent.com/11350998/140984188-b2fa10d6-df73-4ac3-8658-9cf23b59f7a3.png)

@danifpdra can you test it? Something like this:

    rosrun atom_calibration inspect_dataset -json data_collected.json

**Comment by eupedrosa** [comment]
Now, this is [rich](https://rich.readthedocs.io/en/latest/tables.html):exclamation:

**Comment by miguelriemoliveira** [comment]
Thanks. Next time I will use that one.

**Comment by danifpdra** [comment]
This works. Closing now.
