### ISSUE TITLE
Verify the parent and child links for all sensors in the calibration.yaml

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#316]
This is important to verify the validity of the configuration file. 

The parent - child pair must be an existing atomic transformation, otherwise the configuration is invalid.

This should be checked in the configure_calibration_pkg.

@danifpdra can you do this? You know how to?

**Comment by danifpdra** [comment]
I can do it but I don't know how.

I already solved the previous problem tho. We are calibrating successfully!

**Comment by miguelriemoliveira** [comment]
> I can do it but I don't know how.

let me try to help you start. Here's where we are already doing some verifications:

https://github.com/lardemua/atom/blob/06de6901b5c7f93d72411c079d9764488928a3e4/atom_calibration/scripts/configure_calibration_pkg#L160-L243

So we should add one more that checks, for each sensor in the calibration file, if the parent to child transformation exists in the xacro tf treem and if it does if they are directly connected (to ensure they are atomic).

Here we are getting the path from A to B, which returns a list. If this list has lenght larger than 2, it means A and B are not directly connected.

What do you think?

**Comment by danifpdra** [comment]
OK, I will do that. No problem!
