### ISSUE TITLE
Initial estimate disappears when the computer is rebooted?

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#318]
HI @miguelriemoliveira,

Is the initial estimate that was set supposed to disappear when the computer is rebooted?  Shouldn't there be an option to save it?

![image](https://user-images.githubusercontent.com/47574905/135457329-7717857a-4787-482a-bd5b-baf5c23f7b93.png)

**Comment by miguelriemoliveira** [comment]
It should be stored in the file https://github.com/lardemua/larcc/blob/main/larcc_calibration/urdf/initial_estimate.urdf.xacro

Did you reconfigure the package? Doing so deletes the initial estimate ...

**Comment by danifpdra** [comment]
No, I didn't reconfigure

**Comment by miguelriemoliveira** [comment]
Strange ... you'll have to set the initial estimate again, and this time make a local backup of the file above. If it happens again we try to reuse the file.

**Comment by danifpdra** [comment]
I already did that. Thanks
