### ISSUE TITLE
Restructure data collector

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#319]

**Comment by miguelriemoliveira** [comment]
Hi @eupedrosa and @aaguiar96 ,

I am working with @danifpdra in the calibration of a large robotic system containing 3 velodynes and multiple cameras.

This large set of sensors is an excellent stress test for the atom tools which, for now, have held their ground.
There is a problem now that I am not sure can be solved without restructuring the data collector code https://github.com/lardemua/larcc/issues/36#issuecomment-942444648.

The problem is that the collector node subscribes to many different sensor data topics, and for some reason it starts receiving very old messages after a while. Check the issue for more details.

This issue is to launch a discussion on the best architecture for the collector. 

First question: Should the collector and the labeller be a single process?

We could think of splitting into several processes and then having a single collector,  and multiple labeller processes, one for  each sensor. The advantages would be that we don't have a big process, and the disadvantage would be that the raw data and the labels could be desynchronized.

Second question: Should the collecting and the labelling be simultaneous? I think the answer is yes because, although an offline labelling procedure would help (for example allowing for semi-automatic labelling) the fact is that having the visual feedback of how the collections are being labelled is an important aspect of deciding when to save a collection.

I would like to hear your opinions and any ideas you may have.

Thanks,
Miguel

**Comment by eupedrosa** [comment]
> The problem is that the collector node subscribes to many different sensor data topics, and for some reason it starts receiving very old messages after a while. Check the issue for more details.

I would start to understand why this is happening. My educated guess is that the collector and labeling process takes too long and some messages are dropped.

> First question: Should the collector and the labeller be a single process?

Maybe we should create a diagram of how this is currently working so we can have a big picture of the process. I tried to look at the code and am still not sure how it is currently working.

> Second question: Should the collecting and the labelling be simultaneous? I think the answer is yes because, although an offline labelling procedure would help (for example allowing for semi-automatic labelling) the fact is that having the visual feedback of how the collections are being labelled is an important aspect of deciding when to save a collection.

I also believe it should be simultaneous.

**Comment by miguelriemoliveira** [comment]
Hi @eupedrosa ,

sorry for taking so long to reply.

Right now we should be able to avoid restructuring the code because we implemented a
automatic configuration of message throttles. Check https://github.com/lardemua/atom/issues/320.

Lets leave this for later.

Thanks for the feedback.

**Comment by miguelriemoliveira** [comment]
Now its working fine for larcc, and also now we have the manual annotator so its less important to do this.
