### ISSUE TITLE
Create dataset playback functionality

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#335]

**Comment by manuelgitgomes** [comment]
Good morning! As I ran the command `roslaunch simplebot_calibration dataset_playback.launch` from the [simpleBot repo](https://github.com/miguelriemoliveira/simpleBot)  and the command `rosrun atom_calibration dataset_playback2 -json $ATOM_DATASETS/simplebot/dataset2/dataset.json` , the following RVIZ appears.
![image](https://user-images.githubusercontent.com/58152228/146756767-95362d22-3e81-4d78-ae11-05e9d28552f6.png)
The image topic exists but it does not publish anything, and the pattern links do not exist at all. 
Have I setup anything wrong that gives me these results or are they general?

**Comment by miguelriemoliveira** [comment]
Hi @manuelgitgomes ,

could it be that your fixed frame in not well selected? I think it should be world but chek the tf tree ...

**Comment by miguelriemoliveira** [comment]
I don't think **base_footprint** exists, only **c0_base_footprint**. Use world, that one always exists ...

**Comment by miguelriemoliveira** [comment]
If you want we can talk in 30 or 45 mins ...

**Comment by manuelgitgomes** [comment]
base_footprint exist, it's the parent link of all the c*_base_footprint.
![image](https://user-images.githubusercontent.com/58152228/146788029-8ae6bbf6-32c8-4484-ba1d-505a89e6aea5.png)
We can talked at 15:30 if you prefer.

**Comment by miguelriemoliveira** [comment]
Hi @manuelgitgomes ,

just a tip. You write:

As I ran the command `roslaunch simplebot_calibration dataset_playback.launch` from the [simpleBot repo](https://github.com/miguelriemoliveira/simpleBot)  and the command `rosrun atom_calibration dataset_playback2 -json $ATOM_DATASETS/simplebot/dataset2/dataset.json` , the following RVIZ appears.

It is much easier like this:

As I ran the command 

`roslaunch simplebot_calibration dataset_playback.launch` 

from the [simpleBot repo](https://github.com/miguelriemoliveira/simpleBot)  and the command 

`rosrun atom_calibration dataset_playback2 -json $ATOM_DATASETS/simplebot/dataset2/dataset.json` 

, the following RVIZ appears.

Try to copy paste and you will see the lates is much easier to copy.

**Comment by DanielCoelho112** [comment]
Hi @miguelriemoliveira  and @manuelgitgomes.

What was the problem here? Should commit 458ad2f solve this problem?
I'm getting the same RViz as you, @manuelgitgomes.

**Comment by DanielCoelho112** [comment]
My bad... I forgot to pull the atom repository. Sorry.
The only problem for me now is that the topic with the labeled images is not receiving messages. Was this happening with you too?

**Comment by manuelgitgomes** [comment]
This is an atom feature. When running the dataset_playback script add the `-si` flag to show the images.

**Comment by DanielCoelho112** [comment]
Working!
Thanks @manuelgitgomes
