### ISSUE TITLE
Create dataset_playback launch files in an automatic way

### ISSUE THREAD

**Issue by DanielCoelho112** [lardemua/atom#338]
Right now, every time the calibration is run, the dataset_playback launch file will be erased.

**Comment by miguelriemoliveira** [comment]
Hi @DanielCoelho112 ,

what erases (because it creates new launch files) is the calibration configuration, i.e.:

`rosrun simplebot_calibration configure`

**Comment by manuelgitgomes** [comment]
Sorry, misplaced the number of the issue. The closed issue should be #336, reopening this one.

**Comment by miguelriemoliveira** [comment]
This is done.
