### ISSUE TITLE
Create an intuitive way to change collections in dataset_playback

### ISSUE THREAD

**Issue by manuelgitgomes** [lardemua/atom#340]
Instead of changing based on a timer, as seen on:
https://github.com/lardemua/atom/blob/694f8e939f793d903e4b259f24b5d84d875f074d/atom_calibration/scripts/dataset_playback2#L162-L164
Change it to a better way, like pressing a specific key. This also needs to be accompanied by a reset on rviz.

**Comment by DanielCoelho112** [comment]
Hi, 

The part of changing the collection based on some specific key is working in 0289a00. To go to the next collection you have to press the "right arrow" and to go to the previous collection you have to press the "left arrow".

However, the part of resetting the Rviz whenever we change collection is not yet done.

**Comment by miguelriemoliveira** [comment]
Hi @DanielCoelho112 ,

great. Resetting remotely does not work, but you can reload the configuration file.

https://answers.ros.org/question/225945/can-i-reset-rviz-via-topic/

**Comment by DanielCoelho112** [comment]
It makes sense. I'll do that later.

**Comment by manuelgitgomes** [comment]
Used professor's method as it can be seen in here:
https://github.com/lardemua/atom/blob/ba0045a5b8326416a92e90b7c1730b9ca04a0a44/atom_calibration/src/atom_calibration/dataset_playback/visualization.py#L619-L624
When the marker frame_id references the current collection, it should add the marker. When it references the previously selected collection, it deletes the marker.
