### ISSUE TITLE
Create rgbd camera xacro which also has a visual component for the depth camera

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#349]
We need this to have a visual feedback of the calibration of rgbd cameras.

**Comment by miguelriemoliveira** [comment]
![image](https://user-images.githubusercontent.com/11350998/149122025-ea15d842-89dd-478e-b7a6-ab7b9632d78c.png)


![image](https://user-images.githubusercontent.com/11350998/149122430-7884db2b-951b-4d42-89ee-131bc4de5ecc.png)

**Comment by miguelriemoliveira** [comment]
@danifpdra

**Comment by danifpdra** [comment]
![image](https://user-images.githubusercontent.com/47574905/149163954-c8f02b80-b51e-4b19-8668-5d43350a1ab8.png)
 
There you go, some nice pink cylinder :-)

**Comment by miguelriemoliveira** [comment]
no comments ...

**Comment by danifpdra** [comment]
2 RGBS -  no initial estimate, no nig

![image](https://user-images.githubusercontent.com/47574905/149186733-79dabbeb-6725-4c19-a5c7-afe6b9e6c572.png)


2RGBS - no initial estimate, nig 0.1 0.1

![image](https://user-images.githubusercontent.com/47574905/149189669-30cec87c-f3ff-4a60-9b4d-be32018cf53f.png)
(the visual component of the world camera didn't move because I changed the calibration parent and child links but you can see that the coordinated system is way ahead of where it should be)

2RGBS - with initial estimate, no nig
![image](https://user-images.githubusercontent.com/47574905/149189286-d0b1b839-e5a7-4d5f-b4a5-1365592ea844.png)
(again, the same problem)

**Comment by danifpdra** [comment]
Calibration summary here:
![image](https://user-images.githubusercontent.com/47574905/149189389-c55427ca-9a3d-432b-a533-7987efe0ca99.png)

**Comment by miguelriemoliveira** [comment]
Hi @danifpdra ,

I was thinking about this and had and idea. I want you to tell me what you think.

Why don't we have two camera cad models, one anchored on the rgb optical frame and another on the depth optical frame?
We could put them with different colors (none in pink), but that way we would know these two must coincide for the calibration to be successful.

If you like the idea I can try to implement ...

**Comment by danifpdra** [comment]
Hi @miguelriemoliveira,

But if we are trying to calibrate, for example, from camera_link to camera_rgb frame, how would the camera move? Because at the current state none of them moves now because we are not calibrating the camera's position in relation to the support

**Comment by miguelriemoliveira** [comment]
if the **camera_link to camera_rgb_frame** moves so will everything after that, including the cad model attached to the **camera_rgb_optical_frame**.

Right now they don't move because the cad model is attached to a coordinate frame before, not after.

You agree?

**Comment by danifpdra** [comment]
I'm not quite being able to visualize it but if it's possible, I think it's a good idea

**Comment by miguelriemoliveira** [comment]
Its implemented. 

![image](https://user-images.githubusercontent.com/11350998/149656237-7cc95867-8dc9-4785-9b2e-ee152f21bec6.png)

Each frame rgb_optical_frame and depth_optical_frame have a camera stl attached to it 

The rgb cad model

![image](https://user-images.githubusercontent.com/11350998/149656720-5013846c-ed19-4d31-8fa8-c833fc378adf.png)

and the depth optical frame

![image](https://user-images.githubusercontent.com/11350998/149656729-4de3039c-6b80-4e47-9760-2e42b95045d1.png)

This change deprecates all bagfiles and datasets for the mmtbot.  Should we proceed with it?

**Comment by danifpdra** [comment]
That's fine by me.

**Comment by miguelriemoliveira** [comment]
What, no comments about the color?

**Comment by danifpdra** [comment]
I'm very proud of you for embracing your inner pink ahah

**Comment by miguelriemoliveira** [comment]
@danifpdra this is done, right? I mean, there should be a very urgent issue to change from pink to another color, but this issue is fine, right?

**Comment by miguelriemoliveira** [comment]
Done in #626
