### ISSUE TITLE
Simulated experiment mmtbot calibration using only the rgb cameras 

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#350]

**Comment by miguelriemoliveira** [comment]
With depth we are not being able to optimize properly. We get this:

![image](https://user-images.githubusercontent.com/11350998/149125004-043e430b-7fd0-47df-8963-73acf6fa3c50.png)


This issue is to debug and (finally) make sure that the rgb component of the of is really working.

**Comment by danifpdra** [comment]
hi @miguelriemoliveira ,

good news. I've done new experiments with the anchored sensor and nig and everything works very well:

![image](https://user-images.githubusercontent.com/47574905/149341893-25e5302c-aea7-41f6-98c7-7d1ab0b940b6.png)
