### ISSUE TITLE
Lidar to lidar evaluation 

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#356]
Hi @miguelriemoliveira ,

I should I calculate the error in the LiDAR to LiDAR evaluation? I have two 3D point clouds, but I can't project them into the pattern so it doesn't make sense to use longitudinal and orthogonal errors. Should I use 3D distances?

**Comment by miguelriemoliveira** [comment]
Yes, I would use 3D distances. 

For each point in laser A, find the distances to all points in laser B and retrieve the minimum. 

This is called Hausdorff distance.

https://pt.wikipedia.org/wiki/Dist%C3%A2ncia_Hausdorff



I think @tiagomfmadeira developed a python code for that. Do you remember @tiagomfmadeira ?

**Comment by tiagomfmadeira** [comment]
Hello @miguelriemoliveira and @danifpdra,

Yes! However, there's a quite efficient implementation of the algorithm in Open3d. I've recently used it in a cost function for the optimization of point cloud poses with OptimizationUtils.
Here it is: http://www.open3d.org/docs/latest/tutorial/Basic/pointcloud.html#Point-Cloud-Distance
Maybe give it a go?

**Comment by miguelriemoliveira** [comment]
Thanks @tiagomfmadeira .
