### ISSUE TITLE
Matplotlib very slow in lidar to lidar evaluation 

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#361]
Hi @miguelriemoliveira 

Can you help ?

I'm running evaluating lidar to lidar in the twolidarbot with the following test and train datasets

[train_dataset.zip](https://github.com/lardemua/atom/files/8004502/train_dataset.zip)
[test_dataset.zip](https://github.com/lardemua/atom/files/8004517/test_dataset.zip)

You can run the evaluation with

`rosrun atom_evaluation lidar_to_lidar_evaluation.py -ld1 lidar_1 -ld2 lidar_2 -train_json $ATOM_DATASETS/twolidarbot/train_dataset/atom_calibration.json -test_json $ATOM_DATASETS/twolidarbot/test_dataset/dataset.json `

**Comment by miguelriemoliveira** [comment]
Not anymore I think .
