### ISSUE TITLE
3D LiDAR labeling inconsistency

### ISSUE THREAD

**Issue by DanielCoelho112** [lardemua/atom#363]
Hi @miguelriemoliveira,

As discussed, it looks like we are applying some downsampling technique in the lidar labeling:
![154581747-afbcad5a-9d02-4e39-95ba-82719c08adc1](https://user-images.githubusercontent.com/73063947/155315451-42418d18-9def-4a18-9c57-cbd327b7c4cc.png)

This image was taken in the dataset_reviewer stage, so it should not be downsampled. Can you track down the problem?

**Comment by miguelriemoliveira** [comment]
Don't have time for taking a look now. Will leave it for later.

**Comment by miguelriemoliveira** [comment]
I think this is due to the sampling of solid points that can be configured, so it should be a feature, not a bug.
