### ISSUE TITLE
Dataset with 2 LiDARs - Dataset Reviewer

### ISSUE THREAD

**Issue by DanielCoelho112** [lardemua/atom#364]
Hi @danifpdra,

do you have a dataset with 2 lidars? I'm planning to test the dataset reviewer in a more complex dataset.

**Comment by danifpdra** [comment]
Hi @DanielCoelho112 ,

Can it be simulation or do you want real world?

**Comment by DanielCoelho112** [comment]
@danifpdra.

for now, I think simulation is better.

**Comment by danifpdra** [comment]
[train_dataset.zip](https://github.com/lardemua/atom/files/8134851/train_dataset.zip)

Here it is. Two lidars and one camera

**Comment by DanielCoelho112** [comment]
Thanks @danifpdra
