### ISSUE TITLE
Fix  getPointsInDepthSensorAsNPArray

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#365]
Hi @danifpdra ,

I was looking for this 

https://github.com/lardemua/atom/blob/8c1553a0fd15ebd56f962c4290bc6dbe6ecd90e3/atom_calibration/src/atom_calibration/calibration/objective_function.py#L89-L138

and noticed you still have lots of debug stuff there. Can you remove this mike stuff please?

Thanks

**Comment by miguelriemoliveira** [comment]
Hi Daniela,

Did you do it? You did not respond ...

**Comment by danifpdra** [comment]
I didn't answer because I did it and pushed it: 

![image](https://user-images.githubusercontent.com/47574905/156017530-180774b7-13ad-4d60-9f0f-b6d08f81a15e.png)

**Comment by miguelriemoliveira** [comment]
OK, thanks @danifpdra .
