### ISSUE TITLE
Creation of a simulated AtlasCar2 enviornment

### ISSUE THREAD

**Issue by manuelgitgomes** [lardemua/atom#366]
This task consists of subtasks:

- [x] - Create models for AtlasCar2's wheels and AtlasCar2 without the wheels;
- [x] - Create a generic Ackermann vehicle simulation;
- [x] - Search gazebo simulated worlds, such as a city, a highway, etc...;
- [x] - Fuse previously created models, world and simulation;

Due date: 25 of March.

**Comment by vitoruapt** [comment]
Check the previous works of Ricardo Silva (http://lars.mec.ua.pt/public/LAR%20Projects/RobotNavigation/2018_RicardoSilva/) or Manuel Ferreira (http://lars.mec.ua.pt/public/LAR%20Projects/RobotNavigation/2019_ManuelFerreira/) because they used the ATLASCAR2 model in Gazebo. Maybe you can find something useful for your work!

**Comment by manuelgitgomes** [comment]
Thank you professor!

**Comment by manuelgitgomes** [comment]
Good evening, I'm having a bit of trouble editing the mesh for atlascar. Do we have access to a normal model (.sldpart, .step, etc..)?

**Comment by miguelriemoliveira** [comment]
Not really. Can't you convert it?

**Comment by manuelgitgomes** [comment]
I can, but it was taking too long due to the detail of the mesh.
I'll leave it converting overnight, tomorrow morning I will bring news.

**Comment by miguelriemoliveira** [comment]
That's strange. The mesh should be small, or else it will hamper rviz ...

**Comment by manuelgitgomes** [comment]
Solved the first task in this issue. 
The mesh was indeed large and after I tried various software programs to convert the mesh to a solid body, I used the program blender to edit the mesh and created the two needed meshes. 
The files can be found on [this commit](https://github.com/manuelgitgomes/atlascar2/commit/54b31e106f7e085e5a7c3158acbb6136443625a7), on a fork of the atlascar2 repo.

**Comment by manuelgitgomes** [comment]
Task number 3 done on commit https://github.com/manuelgitgomes/atlascar2/commit/0e4c36a15ee349c64031f1afe8ca4800ec88b24e (bad comment placed it on issue #336). The world can be seen in the following picture and was found on this [repo](https://github.com/chaolmu/gazebo_models_worlds_collection).

![image](https://user-images.githubusercontent.com/58152228/159327371-9e220def-925d-4b9d-8222-f5ad43bdf6c9.png)


On commit https://github.com/manuelgitgomes/atlascar2/commit/cb83ba9ef669626a1d3f6427c116249e001150c3, also mislabeled, I came across a glitched mesh, as can be seen below. Please ignore the placement of the wheels as it still needs work.
![image](https://user-images.githubusercontent.com/58152228/159327796-968eb8a9-14de-4728-a108-f56f8dd5e032.png)

This model was exported from blender. After re-importing the mesh on blender, it still is flawless, as can be seen below.
![image](https://user-images.githubusercontent.com/58152228/159328009-5d2dd6c7-5a51-4c38-8898-c3229d3c6c2f.png)

I also tested the mesh on another dae and stl viewers, in which [some of them](https://imagetostl.com/view-dae-online) have a flawless model:
![image](https://user-images.githubusercontent.com/58152228/159328397-3f866d9e-5739-43d5-b067-ef7f0ed714fa.png)

While [others](https://www.creators3d.com/online-viewer) show a similar model as the one appearing in gazebo.

![image](https://user-images.githubusercontent.com/58152228/159328514-2215b0ca-6415-41f4-b60e-53907f536ce2.png)

Does anyone has any idea on why this works this way and/or how to solve it?

Thanks.

**Comment by miguelriemoliveira** [comment]
Hi @manuelgitgomes ,

the city looks great. 

I did not understand the problem with the models very well. Can you please explain?

**Comment by manuelgitgomes** [comment]
Hello @miguelriemoliveira!
Basically, for the same mesh, some programs show it correctly, while others show it with faults.
Gazebo is one of the ones who see it faulty. 
I don't know why this happens, but will try to figure it out tomorrow.

**Comment by miguelriemoliveira** [comment]
Ok. I remembered that the collada files has some configurations that were not supported by rviz ...

**Comment by manuelgitgomes** [comment]
I found a workaround and the mesh is now functional.
![image](https://user-images.githubusercontent.com/58152228/159593806-ae4e56c0-3680-47cc-9ba0-4a5790c7f1f0.png)
Instead of editing the mesh used on the link Prof. Vitor sent, I edited the one in atlascar2 repo.

**Comment by manuelgitgomes** [comment]
Car spawn is successfully done, as can be seen below.
![image](https://user-images.githubusercontent.com/58152228/159895810-f6ae01c3-8c35-4d44-b962-a12c187305a3.png)

Car collisions are also displayed bellow as orange solids:
![image](https://user-images.githubusercontent.com/58152228/159896039-510f1cc9-4f8d-4d1e-8509-53b9dda57106.png)

Next step is to develop the controller!

**Comment by miguelriemoliveira** [comment]
Looks very nice! Can you use joint state publisher to change the steering angle?

**Comment by manuelgitgomes** [comment]
The controller is working with a few bugs, as can be seen [here](https://www.youtube.com/watch?v=UCiW6hJ80Iw).
In the video the steering angle of the wheels is erratic. When moving in front they generally lock in a position where they stop the movement of the vehicle. When turning, they generally function well, sometimes also locking in a certain position.
The problem is not on the collision box of the chassis for I have disabled it temporarily. I believe the problem might be on the out of tune PIDs for the wheels. 
If anyone has an idea of where the bug might be, please tell me!

**Comment by manuelgitgomes** [comment]
I rebuilt the simulation from a stable ackermann vehicle and the problem remained. The problem started appearing after changing the length of the axle, that is, the distance between left and right wheels. It aggravated after correcting the weight.

I also tested the simulation with the vehicle placed on top of a box. The results are shown [here](https://www.youtube.com/watch?v=u-kMuT7NBLo). When accelerating the front wheels turned inwards in relation to the vehicle. After placing the velocity back at 0, the wheels started oscillating. This problem really seems like an out of tune PID.

After searching online, I found [this author](https://answers.ros.org/question/328721/gazebo-ros-control-position-controller-joints-problem/) having problems while creating an ackermann controller. A set of solutions is presented below, one of them is the tuning of the PIDs. This might be the next step.

**Comment by miguelriemoliveira** [comment]
Hi @manuelgitgomes ,

I think you're in the right path. Keep going.

**Comment by manuelgitgomes** [comment]
Issue (finally) solved, as can be seen [here](https://www.youtube.com/watch?v=UWo4ndSZ1XU). The vehicle runs as intended, as can be seen in the video. Thank you to @Sarxell for helping me find the major bug, which was in the conversion from twist to ackermann. Combining this with the reduction of the wheel weight made the vehicle fulfil its purpose.
A minor bug was found, when the car is travelling at large velocities, after a sharp turn, the wheels do not align 100% with the middle, making it swerve a little to one of the sides.
The next tasks will be to document the process on the README.md file and to add sensors.

**Comment by miguelriemoliveira** [comment]
Congrats. Looks very nice.

**Comment by miguelriemoliveira** [comment]
... and thanks @sarxell for the help. I added you as a collaborator already.

**Comment by manuelgitgomes** [comment]
Documentation of this feature was made. Issue closed.

**Comment by miguelriemoliveira** [comment]
Nice!
