### ISSUE TITLE
Adding function to save collection by collection

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#370]
Hi @DanielCoelho112,

Can you implement a feature to save the new labelled collection with the S key or maybe they are saved automatically in a new dataset.json each time we move on to the next collection?

Because this crashed a lot and once it crashed we lose our previous labelled collections...

**Comment by DanielCoelho112** [comment]
Hi @danifpdra,

> Can you implement a feature to save the new labelled collection with the S key or maybe they are saved automatically in a new dataset.json each time we move on to the next collection?

Yes I can. But I think the best way for now is after each collection you save the dataset. Then if the program crashes, you can load the dataset_corrected.json and start from there. In this way, you never lose any labeled collection.

**Comment by danifpdra** [comment]
Yes, I understand that, but it would be much easier if each collection would be automatically saved each time we move on to another one

**Comment by miguelriemoliveira** [comment]
Implemented by @manuelgitgomes .
