### ISSUE TITLE
Add text to each sensor's interactive marker

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#372]
When we have 3 lidar's we have 3 labelers and we don't know which is which ... a text near the marker would help to distinguish. 

We could use the description field for that but the color is fixed to white which is not visible  with our white background.

**Comment by miguelriemoliveira** [comment]
Implemented. @danifpdra what do you think? Does it help?

![image](https://user-images.githubusercontent.com/11350998/160231940-824288b8-6b69-44d5-9b5a-818751c91fe0.png)

**Comment by danifpdra** [comment]
Hi @miguelriemoliveira ,

Would it be possible that the color of the marker's text matches the color of the cloud labeller? It would be easier to identify which is which

**Comment by miguelriemoliveira** [comment]
Hi @danifpdra ,

the problem is that the color of each sensor is created in the configure_calibration_pgk

https://github.com/lardemua/atom/blob/2d2aeeb2a90a9881124d11eb289287470c82a293/atom_calibration/scripts/configure_calibration_pkg#L103-L104

and this marker is being created on the collector ... I will try to do it, will get back to you.

**Comment by danifpdra** [comment]
The colormap can't be created in the same way in the collector?

**Comment by miguelriemoliveira** [comment]
Yes, that's my idea, although its not ideal because once you change the first, you'll forget to change the second.

**Comment by danifpdra** [comment]
Isn't there a way to get the color automatically?

**Comment by miguelriemoliveira** [comment]
There is the one in the code above, but if I change the colormap for example I must do it also in the other place.

**Comment by danifpdra** [comment]
Couldn't we save the colors somewhere when we run the configure_calibration_pkg and read them in the collector?

**Comment by miguelriemoliveira** [comment]
We could but I think this would complicate things even more. My suggestion is to do the same colormap code line in both, and add a note near that line saying if we change this we should also change it on file x, line y. Can you do it @danifpdra ?

**Comment by danifpdra** [comment]
ok, no problem

**Comment by miguelriemoliveira** [comment]
Hi @danifpdra , can we close this?
