### ISSUE TITLE
Configure calibration package with different config.yaml files

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#373]
Hi @miguelriemoliveira ,

So I have been saving previous/relevant configuration in larcc like this: 

![image](https://user-images.githubusercontent.com/47574905/160376368-5de72cf3-3bc0-405d-88a9-1bbabebb3534.png)

Previously we've thought about having different config.yaml and different calibration folder... But now I was thinking, couldn't we add an option to specify the config.yaml file to some other file (default would be config.yaml) and that way we could have previous configuration saved like I have and just configure them again any time? It would be simpler, I guess. Tell me what you think

**Comment by miguelriemoliveira** [comment]
Hi @danifpdra ,

I agree.

**Comment by danifpdra** [comment]
Implemented, 

Use 

`rosrun yourpackage_calibration configure -c new_config_file.yml`

To configure with a different file.
