### ISSUE TITLE
Is there any way to make the depth labeler less sensitive to the black holes in the chessboard?

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#385]
![image](https://user-images.githubusercontent.com/47574905/162230363-d01a5b4d-e5a7-477e-825e-733abdec6e25.png)
![image](https://user-images.githubusercontent.com/47574905/162230380-1085505a-6ad4-4a11-94cd-ebd5b60cb347.png)

**Comment by miguelriemoliveira** [comment]
Don't think so. In these extreme cases better use the manual labeller.

I am closing the issue.
