### ISSUE TITLE
Why are the kinect images with channels inverted?

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#387]
![camera_2_27](https://user-images.githubusercontent.com/11350998/162495979-9ba43d9a-cf5b-41c9-8ed6-633a21832a2f.jpg)

Our fanuc looks like a motoman!

@danifpdra can you try to fix this?

**Comment by danifpdra** [comment]
Hi @miguelriemoliveira ,

That's not the Kinect... That's the Astra. And that only happens when collecting data, the bagfile is fine.

**Comment by eupedrosa** [comment]
OpenCV uses by default BGR and not RGB...

**Comment by miguelriemoliveira** [comment]
Hum, strange. I will look into it.

**Comment by miguelriemoliveira** [comment]
When I do a 

    roslaunch larcc_calibration playbag.launch

the images seem fine ...

![image](https://user-images.githubusercontent.com/11350998/163341540-fa66fb75-f13c-4127-b9ba-2647d1991420.png)

**Comment by danifpdra** [comment]
I've told you before, the problem is saving the images, not the bag

**Comment by danifpdra** [comment]
![image](https://user-images.githubusercontent.com/47574905/163349789-c3614e6b-063f-4bad-826b-cc9b6f8c1b67.png)

The images are also fine in the collector

**Comment by miguelriemoliveira** [comment]
Fixed. Had to convert from rgb8 to bgr8 images before calling imwrite. Tested collecting a dataset and loading with dataset playback. Its working. Will close. 

@danifpdra , if you notice something wrong let me know.

**Comment by miguelriemoliveira** [comment]
Thanks. I will kook into it.
