### ISSUE TITLE
Calibration stops after Computing sparse matrix....

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#388]
Hi @miguelriemoliveira ,

When trying to calibrate using 

`roslaunch larcc_calibration calibrate.launch dataset_file:=$ATOM_DATASETS/larcc_real/dataset_test/dataset_corrected.json run_calibration:=false`

and

`rosrun atom_calibration calibrate -uic -json $ATOM_DATASETS/larcc_real/dataset_test/dataset_corrected.json -nig 0.05 0.05  -ipg -si -rv -ssf 'lambda name: name in ["lidar_1","lidar_2","lidar_3", "camera_2", "camera_3", "camera_4","depth_camera_1"]' -uic`

(dataset here: https://we.tl/t-zf8rCYqiIo) 

I get this 

```
immovable links are: ['world', 'table', 'tabletop_table', 'leg1_table', 'leg2_table', 'leg3_table', 'leg4_table', 'gantry', 'gantry_gantry', 'leg1_gantry', 'leg2_gantry', 'leg3_gantry', 'leg4_gantry', 'bigbeam1_gantry', 'bigbeam2_gantry', 'smallbeam1_bigbeam1_gantry', 'smallbeam2_bigbeam1_gantry', 'rectangularbeam1_gantry', 'rectangularbeam2_gantry', 'rectangularbeam3_gantry', 'lidar_1_base_link', 'lidar_1', 'lidar_2_base_link', 'lidar_2', 'lidar_3_base_link', 'lidar_3', 'camera_1_link', 'camera_1_depth_frame', 'camera_1_depth_optical_frame', 'camera_1_rgb_frame', 'camera_1_rgb_optical_frame', 'camera_2_link', 'camera_2_rgb_frame', 'camera_2_rgb_optical_frame', 'camera_2_depth_frame', 'camera_2_depth_optical_frame', 'camera_3_link', 'camera_3_rgb_frame', 'camera_3_rgb_optical_frame', 'camera_3_depth_frame', 'camera_3_depth_optical_frame', 'camera_4_link', 'camera_4_rgb_frame', 'camera_4_rgb_optical_frame', 'camera_4_depth_frame', 'camera_4_depth_optical_frame']
movable links are: []
Robot has all joints fixed. Will render only collection 0
Anchored sensor is lidar_2
Creating parameters ...
Creating residuals ... 
  RNG Seed: 4722282011812042379
Computing sparse matrix ... 
```

And then the program ends and the calibration doesn't start... Did someone modify this file? It seemed like an `exit(0)` but there is none in that context... Do you know what happened?

**Comment by danifpdra** [comment]
@miguelriemoliveira ,

Are you trying to cause me bugs on purpose?!?!?!

![image](https://user-images.githubusercontent.com/47574905/163168683-9cdd9221-1c50-4884-9108-21923d127609.png)

**Comment by miguelriemoliveira** [comment]
Sorry ... not on purpose ...
