### ISSUE TITLE
We should talk to Daniel to understand why sorting was a problem.

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#390]
```
# TODO We should talk to Daniel to understand why sorting was a problem.

The would be that we don't replicate functions in atom.
```

https://github.com/lardemua/atom/blob/4b49504966a7af7cf2160b4f508f175678fda830/atom_calibration/scripts/dataset_playback#L58

**Comment by miguelriemoliveira** [comment]
This issue was created directly in vscode ... uau! Now I don't have any effort to give you guys additional work ...

**Comment by DanielCoelho112** [comment]
> This issue was created directly in vscode ... uau! Now I don't have any effort to give you guys additional work ...

vscode is awesome :)

The problem with sorting is that we are sorting characters and not integers. So if we have more than 10 collections, the sorted collections will be: ['0', '1','10','11','2']. I didn't want to change the code, so I replicated the functions.

With the sorting as it is, when we are moving from collection to collection, we jump from 1 to 10...

**Comment by miguelriemoliveira** [comment]
Ah, ok. I will try to solve it in a better way, because having duplicate functions is not ideal.

**Comment by miguelriemoliveira** [comment]
But I am lost  because this latest version is commented. Is that you @manuelgitgomes ?

**Comment by manuelgitgomes** [comment]
Yes! I compared the used one with the original one and no difference was found, so i commented it.

Obter Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by miguelriemoliveira** [comment]
Thanks @manuelgitgomes ,

I will try to fix the bug of crashing when we select many points.

**Comment by miguelriemoliveira** [comment]
This was a very hard one. @DanielCoelho112 , now it's working:

![image](https://user-images.githubusercontent.com/11350998/163165812-adaa5036-05f0-47a1-9c16-17ac62764851.png)

In commit 152aa3ffc39aa342124470c59cd1fef55cb83e08

**Comment by DanielCoelho112** [comment]
Great!! @miguelriemoliveira

1h30 with me and we get nothing. You try for 5 min, and you solve it... Looks like I was slowing you down ahah

**Comment by miguelriemoliveira** [comment]
It was luck ...

**Comment by miguelriemoliveira** [comment]
I tested today and the collections are presented in order I think.

I am closing this issue, lets reopen if needed.
