### ISSUE TITLE
Gantry Xacro in front of calibrated camera in Rviz

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#392]
With Xacro on 

![image](https://user-images.githubusercontent.com/47574905/163197318-96c08106-52a8-4b22-9373-ad09963b5af4.png)

Without xacro on

![image](https://user-images.githubusercontent.com/47574905/163197396-7c8140b0-2885-4f90-ae6f-e64e473ea7ce.png)

**Comment by miguelriemoliveira** [comment]
Hi @danifpdra ,

how about the alignment of teh lidars with the xacro? How is it? Can you post an image?

**Comment by miguelriemoliveira** [comment]
Hi @danifpdra ,

so you are absolutely sure that the xacro is correctly defined and in accordance with the real dimensions of the cell?

**Comment by danifpdra** [comment]
I'm not absolutely sure because there is no way to measure the simulated xacro... But according to my calculations yes

**Comment by miguelriemoliveira** [comment]
Ok, so let's try to work on this when we are both at LAR.
