### ISSUE TITLE
Is it really necessary to define the buff_size?

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#393]
```
                     buff_size=52428800)  # TODO Is it really necessary to define the buff_size?
```

https://github.com/lardemua/atom/blob/baff374982775c72b7ca2ea789e12009f4827c0f/atom_calibration/scripts/dataset_playback#L250

**Comment by DanielCoelho112** [comment]
Hi @miguelriemoliveira, 

I don't think so, I don't even remember why I did that. Maybe I copied it from somewhere in ATOM.

**Comment by miguelriemoliveira** [comment]
ok, I'll fix it then.
