### ISSUE TITLE
Is the dataset reviewer fully functional?

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#397]
Hi @danifpdra ,

Me, @manuelgitgomes and @DanielCoelho112 worked on the dataset reviewer in the last days.

I think now we have a fully functional solution, but I wanted you to tell us if something is missing.

List of related issues (Please edit and add if any is missing).

- [x] https://github.com/lardemua/atom/issues/396
- [x] https://github.com/lardemua/atom/issues/394
- [x] https://github.com/lardemua/atom/issues/393
- [x] https://github.com/lardemua/atom/issues/391
- [x] https://github.com/lardemua/atom/issues/384
- [x] https://github.com/lardemua/atom/issues/378
- [x] https://github.com/lardemua/atom/issues/377
- [x] https://github.com/lardemua/atom/issues/374
- [x] https://github.com/lardemua/atom/issues/372
- [x] https://github.com/lardemua/atom/issues/399
- [x] https://github.com/lardemua/atom/issues/398
- [x] https://github.com/lardemua/atom/issues/403
- [x] https://github.com/lardemua/atom/issues/404
- [x] https://github.com/lardemua/atom/issues/407

**Comment by manuelgitgomes** [comment]
That's great, congrats to all! I will test this ASAP.

**Comment by miguelriemoliveira** [comment]
Closing this one. Both opened issues are defined as low priority.
