### ISSUE TITLE
Show projections from the pattern in the depth image

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#400]
Hi @danifpdra ,

During calibration, It would be nice to see in the depth image the projections of the pattern. This would give use an idea of whether the calibration is aligning well.  Right now we only show the labeled data.

![image](https://user-images.githubusercontent.com/11350998/163572893-2b096b4b-55b3-47f6-b40f-0c72d467f6de.png)

**Comment by danifpdra** [comment]
Ok, I will work on that.

**Comment by miguelriemoliveira** [comment]
Hi @danifpdra , great but give priority to getting results and the paper.

BTW, you have to git pull everything, recompile the atom code and  reconfigure your calibration package to have it working.

**Comment by danifpdra** [comment]
Well now I'm already finishing it... Can you zoom for 5 minutes just to give me your input?

**Comment by miguelriemoliveira** [comment]
I with classes this morning, and a meeting at 14h. We can talk 10 mins at 16h?

**Comment by danifpdra** [comment]
Ok
