### ISSUE TITLE
This is strange here

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#411]
Can we remove this?

**Comment by danifpdra** [comment]
whatt??

**Comment by miguelriemoliveira** [comment]
Sorry, I thought it send directly a link to the code.

This one:

https://github.com/lardemua/atom/blob/76f6f44ca369d13c8a7dada4fc762188e272458a/atom_calibration/scripts/configure_calibration_pkg#L654-L659

**Comment by danifpdra** [comment]
I was trying to implement the frustum visualization but couldn't. There's an issue about that

**Comment by danifpdra** [comment]
https://github.com/lardemua/atom/issues/362

**Comment by miguelriemoliveira** [comment]
Ok, got it. Will try to work on that when possible.

**Comment by miguelriemoliveira** [comment]
Working on #362. Close this one.
