### ISSUE TITLE
Daniela, add here instructions for the depht to camera and depth to lidar calibrations!-->

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#422]
```
<!-- #TODO Daniela, add here instructions for the depht to camera and depth to lidar calibrations!-->
```

https://github.com/lardemua/atom/blob/f106e302749806c9c7fc88f0f3ba25b87d63546a/README.md#L420

**Comment by danifpdra** [comment]
I have to check this. I don't remember the commands. I will do it when I'm evaluating the datasets
