### ISSUE TITLE
Weird output when inspecting dataset

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#423]
When running 

`rosrun atom_calibration inspect_dataset -json $ATOM_DATASETS/larcc_real/dataset_train/dataset_corrected.json`

I got this

```
Skipped loading images and point clouds for collections: [].
Loaded dataset containing 7 sensors and 29 collections.
Dataset contains 7 sensors: ['camera_2', 'camera_3', 'camera_4', 'depth_camera_1', 'lidar_1', 'lidar_2', 'lidar_3']
Complete collections (6):['1', '12', '19', '2', '24', '4']
Incomplete collections (23):['0', '10', '11', '13', '14', '15', '16', '17', '18', '20', '21', '22', '23', '25', '26', '27', '28', '3', '5', '6', '7', '8', '9']
Sensor camera_2 has 6 complete detections: ['10', '14', '15', '22', '27', '9']
Sensor camera_2 has 23 partial detections: ['0', '1', '11', '12', '13', '16', '17', '18', '19', '2', '20', '21', '23', '24', '25', '26', '28', '3', '4', '5', '6', '7', '8']
**Sensor camera_3 is not a camera. All detections are complete.**
Sensor camera_4 has 20 complete detections: ['0', '11', '12', '13', '14', '15', '16', '18', '20', '21', '22', '23', '24', '26', '28', '3', '5', '6', '7', '8']
Sensor camera_4 has 9 partial detections: ['1', '10', '17', '19', '2', '25', '27', '4', '9']
Sensor depth_camera_1 has 0 complete detections: []
Sensor depth_camera_1 has 29 partial detections: ['0', '1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22', '23', '24', '25', '26', '27', '28', '3', '4', '5', '6', '7', '8', '9']
Sensor lidar_1 is not a camera. All detections are complete.
Sensor lidar_2 is not a camera. All detections are complete.
Sensor lidar_3 is not a camera. All detections are complete.
```

(Problem: **Sensor camera_3 is not a camera. All detections are complete.**)

There's some kind of problem here...

**Comment by danifpdra** [comment]
It also says 

`Sensor depth_camera_1 has 29 partial detections: ['0', '1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22', '23', '24', '25', '26', '27', '28', '3', '4', '5', '6', '7', '8', '9']`

And the table doesn't show that, and it makes no sense...

![image](https://user-images.githubusercontent.com/47574905/164241331-5f9ec692-af1b-4dbe-a682-54663b0bd512.png)

**Comment by danifpdra** [comment]
I belive the problem is here

https://github.com/lardemua/atom/blob/cf09906acc512979a31a61b6b3a9018e3e406767/atom_calibration/scripts/inspect_dataset#L157-L169

As in the first collection the pattern is not detected on camera_3 it fails this if and assumes it's not a camera

**Comment by miguelriemoliveira** [comment]
Thanks.
