### ISSUE TITLE
Lidar 2 does not move in larcc calibration

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#427]

**Comment by danifpdra** [comment]
https://we.tl/t-abeVemWSzN

**Comment by miguelriemoliveira** [comment]
![image](https://user-images.githubusercontent.com/11350998/164698411-06ba3bea-13d1-4ade-aa5a-caf05326d109.png)

**Comment by danifpdra** [comment]
FYI @miguelriemoliveira ,

This xacro is an optimization that went well. It is in the larcc_calibration/urdf/optimized/ folder. You can replace the optimized xacro in the playbag.launch (i did that and pushed just for visualization if you want to check it)

I'm pasting it here just to save it

[well_optimized.urdf.zip](https://github.com/lardemua/atom/files/8541632/well_optimized.urdf.zip)

**Comment by miguelriemoliveira** [comment]
First I tried to create some form of decay function that would give more strength to the errors of the anchored sensor at start, and then as the optimization progressed would start leveling out with the other sensors. For that I needed https://github.com/miguelriemoliveira/OptimizationUtils/issues/68 which is implemented, but the result in the optimization was not good.

**Comment by danifpdra** [comment]
bag: https://uapt33090-my.sharepoint.com/:u:/g/personal/danielarato_ua_pt/EUlU4WxpgLNPsyEk2HFBh1EBVoQ8f7U2Nudrbbqh_B3Upw?e=1WsX25

**Comment by miguelriemoliveira** [comment]
Hi @danifpdra ,

I just created a new **dataset_corrected.json** which is has some fixes when compared with the one you sent. Perhaps you can replace yours ...

[dataset_corrected.json.zip](https://github.com/lardemua/atom/files/8575394/dataset_corrected.json.zip)

**Comment by miguelriemoliveira** [comment]
This is solved with the two stage calibration procedure for anchored sensors.
