### ISSUE TITLE
Remove and add points in the rgb annotation tool

### ISSUE THREAD

**Issue by Analtino2021** [lardemua/atom#437]

**Comment by miguelriemoliveira** [comment]
Near to finalizing a new script


![image](https://user-images.githubusercontent.com/11350998/168470425-5ab6a469-cb73-4b9d-add9-89508609fc7e.png)

**Comment by miguelriemoliveira** [comment]
![image](https://user-images.githubusercontent.com/11350998/168470463-814a7ef8-c85d-444c-8e04-c2638c404d24.png)

**Comment by miguelriemoliveira** [comment]
The annotations file now has a new format. I will adapt the code for the scripts:

depth_sensor_to_camera_evaluation.py
range_sensor_to_camera_evaluation.py

to adjust to this.

**Comment by miguelriemoliveira** [comment]
New colors and interpolation between annotated points functional.

![image](https://user-images.githubusercontent.com/11350998/168475227-82cb8e75-8f4a-42aa-8c37-60b9a1f7cdd7.png)

**Comment by miguelriemoliveira** [comment]
Ok, changed range_sensor_to_camera_evaluation . 

![image](https://user-images.githubusercontent.com/11350998/168930655-6abd5706-6ee2-4f6e-959e-8545c639a238.png)

**Comment by miguelriemoliveira** [comment]
Visual output from range_sensor_to_camera_evaluation script

![image](https://user-images.githubusercontent.com/11350998/169248660-c7525f03-e569-4a1f-a1b6-f4520aa3873a.png)

**Comment by miguelriemoliveira** [comment]
Also renamed script to range_to_rgb_evaluation

**Comment by miguelriemoliveira** [comment]
Hi @manuelgitgomes ,

I have been working onthis the past week and am now read to change the annotations and the evaluation scripts. 
This should be coordinated, so lets talk about this. For now changes are in branch 

https://github.com/lardemua/atom/tree/miguelriemoliveira/issue437
