### ISSUE TITLE
Create  frustums  as filled polygons with transparency

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#458]
Hi @miguelriemoliveira,

I created a new branch for RGB frustums, the branch is called **frustum**...

You can see the frustum with

`roslaunch larcc_calibration collect_data.launch output_folder:=~/datasets/larcc_sim/tests_for_paper overwrite:=true bag_rate:=0.1 bag_start:=0
`

The idea is to get some images like this 
![frustum_grelha](https://user-images.githubusercontent.com/47574905/168662765-50f813f0-d1cc-4b8b-baa9-f822d377dc4a.png)
![frustum_sem_lidars](https://user-images.githubusercontent.com/47574905/168662770-f33cf245-4624-49a9-a825-2614cf9c86a1.png)
![frustum_prespetiva_2](https://user-images.githubusercontent.com/47574905/168662773-d44f0f5f-6e56-4efb-872b-a79ead8e3f18.png)
![frustum_prespetiva_1](https://user-images.githubusercontent.com/47574905/168662775-971b5e9f-3c85-4608-aa2c-01592afd8cda.png)
![frustum_smaller](https://user-images.githubusercontent.com/47574905/168662778-a234643c-5276-4fd8-bd1d-8e00408e1e42.png)
![frustum_3d](https://user-images.githubusercontent.com/47574905/168662780-247f8017-4ecf-4a13-a4bb-32dbae052f6e.png)
![frustum_top_down](https://user-images.githubusercontent.com/47574905/168662783-ff6abf69-561a-4cc1-a993-75dd42213b41.png)
![frustum_thick](https://user-images.githubusercontent.com/47574905/168662785-6c89478d-58ae-43ce-a8a0-888c2aa01d52.png)

**Comment by danifpdra** [comment]
Check this https://github.com/DavidB-CMU/rviz_tools_py

**Comment by miguelriemoliveira** [comment]
We have our first filled frustum 

![image](https://user-images.githubusercontent.com/11350998/169503949-f555d33e-a8cf-474e-b6a6-7e561c93184f.png)

**Comment by miguelriemoliveira** [comment]
and for the entire larcc

![image](https://user-images.githubusercontent.com/11350998/169504867-12f9cc33-749a-4d45-8ab1-9182a11684ca.png)

**Comment by danifpdra** [comment]
Looks great! Is it possible to see them in real time running the bag? Or just offline?

**Comment by miguelriemoliveira** [comment]
Sure it is. I changed the colors from random to fixed. We are now defining a colormap Pastel2 https://matplotlib.org/3.5.0/gallery/color/colormap_reference.html to define the sensor's color based on its index.

Looks even better:

![image](https://user-images.githubusercontent.com/11350998/169506866-db45151d-360d-4394-a8ee-3818e50fef6f.png)

I will commit in a moment.

**Comment by danifpdra** [comment]
Great! You should have been a designer

**Comment by miguelriemoliveira** [comment]
> Great! You should have been a designer
Wasn't it a doctor?

Ok, this is operational and in the master branch. Deleted the frustum branch.

Have fun with the images for the paper.

**Comment by danifpdra** [comment]
You are multi-talented!

Thanks, will do.
