### ISSUE TITLE
Think about a better way to evaluate lidar-lidar evaluation (for example point to line distance)

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#461]

**Comment by danifpdra** [comment]
Hi @miguelriemoliveira and @manuelgitgomes ,

I am really bothered by this... 

![image](https://user-images.githubusercontent.com/47574905/169257827-eb082ce8-715d-44cb-8518-f4320fc8d9d7.png)

As I told you in the other issue, the distance between two LiDAR scans is 10cm which is 100mm. That means that when projecting transforming the point clouds from one coordinate system to the other we could actually end up with a displacement up to 50mm... This means that, in reality, this table does not mean anything and that the better results can just mean "better luck" in fitting the scans of the two LiDARs and the bad results can just mean that we hit one scan hit the middle of two scans in the other LiDAR... 

Do you have any idea?

**Comment by miguelriemoliveira** [comment]
Well, we could use that point to line idea. Do you think we should work on it for this paper?

**Comment by danifpdra** [comment]
I don't know, I explained what was happening in that section but I think the reviewers can devalue our results, don't you think?

**Comment by miguelriemoliveira** [comment]
> I don't know, I explained what was happening in that section but I think the reviewers can devalue our results, don't you think?

Let me read your discussion and then see if it leaves that impression. 
Also, @manuelgitgomes working on icp calibration #463 so we can later compare and see of the calibration using icp is also "bad".

**Comment by manuelgitgomes** [comment]
> That means that when projecting transforming the point clouds from one coordinate system to the other we could actually end up with a displacement up to 50mm...

I'm not 100% sure I understood, but we can argue that if the results are under 50mm, the calibration was successful in achieving the best it could regarding the sensor's resolution. If they are over 50mm, some improvements need to be taken. So we can argue that the calibration inside the simulated environment reached its peak while the one in the real world can be improved.

**Comment by danifpdra** [comment]
> > That means that when projecting transforming the point clouds from one coordinate system to the other we could actually end up with a displacement up to 50mm...
> 
> I'm not 100% sure I understood, but we can argue that if the results are under 50mm, the calibration was successful in achieving the best it could regarding the sensor's resolution. If they are over 50mm, some improvements need to be taken. So we can argue that the calibration inside the simulated environment reached its peak while the one in the real world can be improved.

I don't think we can argue that... Because, as I said, it can just be a case of luck. For example in lidar2 to lidar3 we have 13mm, that means the we could have had the luck of the lidar scans aligning. And when in lidar 1 to lidar2 we have higher results that means that we could just have had bad luck and the lidar scans ended up with a 50mm alignment. Which really means that those results do not indicate that the calibration was accurate or not.

**Comment by manuelgitgomes** [comment]
> Which really means that those results do not indicate that the calibration was accurate or not.

Ok, that makes sense. And an error of 50 can mean two different things. It can mean a correct calibration with the point in between two points or it can mean a displacement in the vertical or horizontal direction of 50 mm, which is not a correct calibration, right?

**Comment by danifpdra** [comment]
> > Which really means that those results do not indicate that the calibration was accurate or not.
> 
> Ok, that makes sense. And an error of 50 can mean two different things. It can mean a correct calibration with the point in between two points or it can mean a displacement in the vertical or horizontal direction of 50 mm, which is not a correct calibration, right?

Yes, exactly that!

**Comment by miguelriemoliveira** [comment]
> I don't think we can argue that... Because, as I said, it can just be a case of luck. For example in lidar2 to lidar3 we have 13mm, that means the we could have had the luck of the lidar scans aligning. And when in lidar 1 to lidar2 we have higher results that means that we could just have had bad luck and the lidar scans ended up with a 50mm alignment. Which really means that those results do not indicate that the calibration was accurate or not.

the way I think about it is that we cannot expect a calibration to be more accurate than the sensor's resolution. So if the resolution is about 50mm and we calibrate with an error of 10, we were probably lucky. But if, for example we get an error or 80 mm then it means the calibration could be better and is therefore not accurate. So I think I agree with @manuelgitgomes when he says this part:

> we can argue that if the results are under 50mm, the calibration was successful in achieving the best it could regarding the sensor's resolution. If they are over 50mm, some improvements need to be taken. 

@danifpdra  replied:

> I don't think we can argue that... Because, as I said, it can just be a case of luck. For example in lidar2 to lidar3 we have 13mm, that means the we could have had the luck of the lidar scans aligning. And when in lidar 1 to lidar2 we have higher results that means that we could just have had bad luck and the lidar scans ended up with a 50mm alignment. Which really means that those results do not indicate that the calibration was accurate or not.

and yes, luck (randomness) is always involved. But that's why we compute this for multiple points and multiple collections, to extract the tendency. So if for multiple points and multiple collections we are having accuracy values close to the sensors resolution I would say our calibration is the "most accurate it can be", whereas if our accuracy is considerably larger than the sensor resolution it is fair to say that the calibration can be improved.

Does it make sense? I did not understand this part

> Ok, that makes sense. And an error of 50 can mean two different things. It can mean a correct calibration with the point in between two points or it can mean a displacement in the vertical or horizontal direction of 50 mm, which is not a correct calibration, right?

**Comment by manuelgitgomes** [comment]
> Does it make sense? I did not understand this part

An error of 50mm can mean the projection in red, which is correct, just unlucky, but it can also mean the projection in blue, which is incorrect.
![2022_05_19_0ik_Kleki](https://user-images.githubusercontent.com/58152228/169269223-f85f2e56-44d0-4879-961e-f062f89c2279.png)
![2022_05_19_0ij_Kleki](https://user-images.githubusercontent.com/58152228/169269233-8c77db43-cf37-4cbc-b76e-a1b3bfc7379c.png)

**Comment by miguelriemoliveira** [comment]
I think I still do not understand. Let's talk, perhaps its better.

**Comment by manuelgitgomes** [comment]
Zoom?

**Comment by miguelriemoliveira** [comment]
Nobody is going to work on this in the near future.
