### ISSUE TITLE
LiDAR resolution

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#464]
FYI @miguelriemoliveira 

I made measurements for all the LiDARs and all of them were around 10cm

(length in the bottom left corner)

![image](https://user-images.githubusercontent.com/47574905/169075239-6477216e-5cac-41b0-a927-84968639ed1c.png)
![image](https://user-images.githubusercontent.com/47574905/169075333-acb7138c-880a-4582-a4ff-9d2ac303a4f0.png)

**Comment by miguelriemoliveira** [comment]
ok, and how far from the sensor is the pattern?
*  Miguel Riem de Oliveira                                             *
Diretor de curso Mestrado Eng. Automação Industrial
email:    ***@***.***    |    ***@***.***
zoom: https://videoconf-colibri.zoom.us/j/7155402102
office: 22.2.18                 |    ext: 23887
Dep. de Engenharia Mecânica, Universidade de Aveiro
*Campus Universitário de Santiago, 3810-193  Portugal*

**Comment by danifpdra** [comment]
around 2 and 2.5 meters depending on the sensor

**Comment by miguelriemoliveira** [comment]
Ok, so you can use this to justify the apparent lack of accuracy in the lidar to lidar evaluation.
