### ISSUE TITLE
point cloud projection to image

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#465]
Hi @miguelriemoliveira 
I was checking the point cloud projection to image script and i get this... 

![image](https://user-images.githubusercontent.com/47574905/169084297-a9f9898a-11cf-4dde-9700-341ee10b8d96.png)

But in the agrob paper we had this 
![image](https://user-images.githubusercontent.com/47574905/169084452-ce561c73-f349-4aaa-a24d-a8bba48b3109.png)
 
with a colormap instead of a fixed color... Do you know how to do this? the color in the script is fixed

**Comment by miguelriemoliveira** [comment]
Hi @danifpdra ,

I am investigating. Let me know how you run this please...

**Comment by miguelriemoliveira** [comment]
No need. I was able to run. Did some changes and now we have this

![image](https://user-images.githubusercontent.com/11350998/169166564-fc966e03-a8ae-4ce7-af2a-bdda34506695.png)

**Comment by miguelriemoliveira** [comment]
@danifpdra , See if it helps.

**Comment by miguelriemoliveira** [comment]
Hi @danifpdra , 

I think this is solved.

**Comment by danifpdra** [comment]
Thanks. I will take a look into it.
