### ISSUE TITLE
Annotation bug

### ISSUE THREAD

**Issue by manuelgitgomes** [lardemua/atom#474]
With the new annotations, when one or more sides are empty, the program crashes. This can be seen on the dataset `gazebo_move` of atlascar2, on collection 30 and on the `top_left_camera` sensor.

You can use the command:
```bash
rosrun atom_evaluation annotate_pattern_borders_in_rgb -d $ATOM_DATASETS/atlascar2/gazebo_move/dataset.json -cs top_left_camera
```
to reach the desired collection.

**Comment by miguelriemoliveira** [comment]
Hi @manuelgitgomes ,

just fixed it. Also datasyned the new annotation file with the correct labels (it was ok before, but I updated it)
