### ISSUE TITLE
Use CamelCase for functions and class methods, with the first character being small, like saveICPCalibration.

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#475]
Snake case we use for variables. It is better if we all use the same style.

Assignees: @manuelgitgomes
Labels: enhancement

https://github.com/lardemua/atom/blob/bbe7bbe566280a00fb6a58e83e4422318847e1bb/atom_evaluation/scripts/other_calibrations/icp_calibration.py#L82

**Comment by manuelgitgomes** [comment]
Ok! I will change that!

**Comment by miguelriemoliveira** [comment]
Thanks
