### ISSUE TITLE
ATOM inspect dataset changed?

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#478]
Hi @miguelriemoliveira ,

This file changed https://github.com/lardemua/atom/blob/de8e171ec7ffb3083e0cabe74b0700978f3a28b6/atom_evaluation/scripts/inspect_atom_dataset

it doesn't show the green and red table anymore and it's just a list of all collections... why? it's must harder to read

**Comment by danifpdra** [comment]
What do the two last lines mean?

```Collection 0:
Sensor 3dlidar
Complete (non partial) detection
Sensor hand_camera
Partial detection
Sensor world_camera
Partial detection
[False, True, True]
[False, True, True]
```

**Comment by miguelriemoliveira** [comment]
If it changed it was not intentional. I will add it to my todo list.

**Comment by miguelriemoliveira** [comment]
Mistery solved. There were two files:

1. atom_calibration/inspect_dataset (which was doing what we expected)

and 

2. atom_evaluation/inspect_atom_dataset (which was printing old stuff)


I am deleting 2, and renaming 1 to be 

atom_calibration/inspect_atom_dataset

**Comment by danifpdra** [comment]
ok, thanks
