### ISSUE TITLE
New frustum don't allow to move interactive markers

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#480]
![image](https://user-images.githubusercontent.com/47574905/171219235-bc590729-e3ab-44f1-b64c-7c150e3204db.png)

**Comment by miguelriemoliveira** [comment]
Perhaps you need to turn them off or find a viewpoint where they are not in front?
I think there is the namespace with only the wireframe, that should work

**Comment by miguelriemoliveira** [comment]
Closed because  #484 is done.
