### ISSUE TITLE
Visualization of sensor frustums on set initial estimate

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#484]
Hi @danifpdra ,

Right now we are showing the sensor fustrums during the collect data stage.

I was wondering  does it not make more sense to run this in the set_initial_estimate?

**Comment by danifpdra** [comment]
Yes, it would, but we put them initially there because we can't give the seed point to the depth image without it... the RGB was just for the paper

**Comment by miguelriemoliveira** [comment]
Ok, I get it. But if we do #485 the this could  go into the set initial estimate right?

**Comment by danifpdra** [comment]
Sure, that would do

**Comment by miguelriemoliveira** [comment]
Implemented.
