### ISSUE TITLE
Depth camera labeling using image clicks

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#485]
Hi @danifpdra ,

I am thinking about changing the depth camera automatic labeling seed point selection to an image click mechanism.
Something like "just click inside the pattern".

It would be better that the current approach, right?

**Comment by danifpdra** [comment]
> Hi @danifpdra ,
> 
> I am thinking about changing the depth camera automatic labeling seed point selection to an image click mechanism. Something like "just click inside the pattern".
> 
> It would be better that the current approach, right?

Yes, sure

**Comment by miguelriemoliveira** [comment]
Got it

https://youtube.com/shorts/OuLHvp95UBI?feature=share

Will commit in a sec

**Comment by miguelriemoliveira** [comment]
Done in d3faa4576fd0db611f5ee107fe8b0346a73aa736 . Please try it @danifpdra
