### ISSUE TITLE
Dataset playback not working?

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#487]
Hi @miguelriemoliveira  and @miguelriemoliveira ,

Is the dataset_playback working for you?

First I could not run it because it got stuck here https://github.com/lardemua/atom/blob/53c2efba7a90f043ca97306cc7e27b394ceea66b/atom_calibration/src/atom_calibration/dataset_playback/visualization.py#L241

I had to comment that line... And now it runs normally but no image appears

![image](https://user-images.githubusercontent.com/47574905/172204808-5358d463-f92e-4964-9290-b60ab39a8166.png)

I am doing something wrong?

I am running it with 

`roslaunch camerabot_calibration dataset_playback.launch`

and 

`rosrun atom_calibration dataset_playback -json $ATOM_DATASETS/camerabot/train_real/dataset.json -uic -si`

for the dataset 
[train_real.zip](https://github.com/lardemua/atom/files/8846009/train_real.zip)
in the camerabot system

**Comment by manuelgitgomes** [comment]
This is weird, I will try this later today!

**Comment by manuelgitgomes** [comment]
Hello! I do not have the camerabot repo, so I cannot run these commands!

**Comment by danifpdra** [comment]
Everyhting is here:

![image](https://user-images.githubusercontent.com/47574905/172335864-46f46f24-2bc1-4990-b18d-9eeb0e763429.png)


but no image or pointcloud is being published although in the terminal everything looks fine. Did some of you change the way to launch this?

![image](https://user-images.githubusercontent.com/47574905/172336035-c2d59cb7-0c9d-409c-9b56-366acb8e3724.png)

**Comment by miguelriemoliveira** [comment]
Hi @danifpdra ,

first thing is we have to meet so you start using the lars_datasync. We have to stop sending datasets as attachments.

I also do not have the camerabot. Can you run the dataset playback with larcc or another robotic system? Is the problem just for the camerabot or not?

**Comment by danifpdra** [comment]
I already put the camerabot dataset there....

No, I tried the larcc and the same happens.

**Comment by miguelriemoliveira** [comment]
Working for me ...

![image](https://user-images.githubusercontent.com/11350998/172359346-38756bd4-63a4-40a2-8b4a-d8be8b09247e.png)


I ran:

    roslaunch larcc_calibration dataset_playback.launch 

and then:

    clear && rosrun atom_calibration dataset_playback -json $ATOM_DATASETS/larcc/larcc_real/test_dataset/dataset_corrected.json -csf "lambda x: int(x) <= 55" -uic -si  -ow


and it worked fine ...

**Comment by danifpdra** [comment]
It does not work for me...

![image](https://user-images.githubusercontent.com/47574905/172360861-e10ea94d-f891-4db3-bddd-24fd5a702f51.png)


My code is up to date

**Comment by miguelriemoliveira** [comment]
We can meet tomorrow morning and I can try to help ...

In the meantime are you using the commands I posted?

Miguel
*  Miguel Riem de Oliveira                                             *
Diretor de curso Mestrado Eng. Automação Industrial
email:    ***@***.***    |    ***@***.***
zoom: https://videoconf-colibri.zoom.us/j/7155402102
office: 22.2.18                 |    ext: 23887
Dep. de Engenharia Mecânica, Universidade de Aveiro
*Campus Universitário de Santiago, 3810-193  Portugal*

**Comment by danifpdra** [comment]
> We can meet tomorrow morning and I can try to help ...

I can't tomorrow morning...

> In the meantime are you using the commands I posted? 

Yes, I copied them

**Comment by miguelriemoliveira** [comment]
Ok, thursday after discussing with Manuel, 15h?
*  Miguel Riem de Oliveira                                             *
Diretor de curso Mestrado Eng. Automação Industrial
email:    ***@***.***    |    ***@***.***
zoom: https://videoconf-colibri.zoom.us/j/7155402102
office: 22.2.18                 |    ext: 23887
Dep. de Engenharia Mecânica, Universidade de Aveiro
*Campus Universitário de Santiago, 3810-193  Portugal*

**Comment by danifpdra** [comment]
I rebooted my computer and it now works... Go figure. Closing

**Comment by miguelriemoliveira** [comment]
Lol.
