### ISSUE TITLE
Create a documentation site for ATOM

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#489]
Hi @DanielCoelho112, @danifpdra , @eupedrosa , @vitoruapt , @manuelgitgomes and @aaguiar96 ,

I have been working on the ATOM documentation.

The github repo storing the documentation's source files is here:

https://github.com/lardemua/atom_documentation

and you can see the documentation here:

https://lardemua.github.io/atom_documentation/

It is not complete, but there is a lot there already. I intend to to release ATOM as a ROS package shortly, I am just waiting for the final decision of the ESWA paper before proceeding.

The goal is  to have as many people as possible using ATOM, and for that reason the documentation should be as clear as possible.

Please take a look and see if you have some suggestions on how to improve, what could be simpler, what is hard to understand etc.

Thanks for the help,
Miguel

**Comment by danifpdra** [comment]
Hi @miguelriemoliveira ,

I think it looks very good. I don't have any suggestions to improve right now but if I remember something in the mean time I will let you know!

**Comment by miguelriemoliveira** [comment]
Thanks @danifpdra,

ok, if your remember something let me know.

**Comment by vitoruapt** [comment]
Yes, nice looking documentation! It almost compels us to read it ;-)

**Comment by miguelriemoliveira** [comment]
Thanks @vitoruapt  ... I can see nobody is going to read it ... : - )

**Comment by danifpdra** [comment]
I notice that there are some commas missing here

![image](https://user-images.githubusercontent.com/47574905/173657465-dd08a6e9-2c96-447b-b221-3fd59384ea75.png)

**Comment by miguelriemoliveira** [comment]
Thanks @danifpdra . Fixed.

**Comment by miguelriemoliveira** [comment]
Thanks for the feedback. Closing.
