### ISSUE TITLE
Collecting data crashing when seed points "leaves" the image borders

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#490]
Hi @miguelriemoliveira ,

The collector for the depth modality is crashing since you implemented #485 when the seed points "touches" the image's borders

```
[ERROR] [1655135302.131409, 1655133869.630378]: bad callback: <bound method InteractiveDataLabeler.sensorDataReceivedCallback of <atom_calibration.collect.interactive_data_labeler.InteractiveDataLabeler object at 0x7f874e0643a0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/daniela/catkin_ws/src/calibration/atom/atom_calibration/src/atom_calibration/collect/interactive_data_labeler.py", line 295, in sensorDataReceivedCallback
    self.labelData()  # label the data
  File "/home/daniela/catkin_ws/src/calibration/atom/atom_calibration/src/atom_calibration/collect/interactive_data_labeler.py", line 501, in labelData
    self.labels, result_image, new_seed_point = labelDepthMsg(
  File "/home/daniela/catkin_ws/src/calibration/atom/atom_calibration/src/atom_calibration/collect/label_messages.py", line 408, in labelDepthMsg
    mask_up = np.logical_and(diff_up[seeds_up[1, :], seeds_up[0, :]],
IndexError: index 320 is out of bounds for axis 1 with size 320
```

**Comment by miguelriemoliveira** [comment]
Hi @danifpdra ,

I will try to fix it soon.

**Comment by miguelriemoliveira** [comment]
Hi @danifpdra ,
can you explain hoe you fixed it?

**Comment by danifpdra** [comment]
Hi @miguelriemoliveira ,

It was not being checked if the seed point went out of the image and because we are doing the pyrdown seed points really close to the edges were being converted to the edges and throwing errors in neighbour masks...

So I added a test that sees where the seed point is and if it is near the edges (near being the same percentage we use to filter the edges in the labelling algorithm), it's overwritten to the centre of the image again...


https://github.com/lardemua/atom/blob/93280d2affab3396056266a3f54a5f5cb83fae7d/atom_calibration/src/atom_calibration/collect/interactive_data_labeler.py#L499-L516

**Comment by miguelriemoliveira** [comment]
OK, got it.

On the else perhaps it would be best to say the new xy is the same as the previous xy ...
Thanks,
Miguel

**Comment by danifpdra** [comment]
> OK, got it.
> 
> On the else perhaps it would be best to say the new xy is the same as the previous xy ... Thanks, Miguel

I don't think so because if the seed point is being automatically calculated and it's moving towards the edge, and we say it's the previous edge points it will come back to being next to the edge and it will be an endless loop... while if it is the middle of the chessboard we can then correct it manually to the chessboard area. Because this problem happens when the algorithm starts tracking a moving person instead of the chessboard so the previous point will be on the person and not on the chessboard anyway.

**Comment by miguelriemoliveira** [comment]
> Because this problem happens when the algorithm starts tracking a moving person instead of the chessboard so the previous point will be on the person and not on the chessboard anyway.

That is what happens in your dataset. It could be in some other that the pattern is moved to the edge of the image, and if that's the case it would not make sense to "assume the  pattern is back at the middle of the image".

I think it is better to assume that if the tracked object disappeared near and image edge, then it should be close to that edge, not the middle of the image.

**Comment by danifpdra** [comment]
> > Because this problem happens when the algorithm starts tracking a moving person instead of the chessboard so the previous point will be on the person and not on the chessboard anyway.
> 
> That is what happens in your dataset. It could be in some other that the pattern is moved to the edge of the image, and if that's the case it would not make sense to "assume the pattern is back at the middle of the image".
> 
> I think it is better to assume that if the tracked object disappeared near and image edge, then it should be close to that edge, not the middle of the image.

I'm not assuming that the object is near the image. I am assuming that I've reached a point where I don't know where the pattern is because if the center of mass of the tracked object is in the edge it is because there is almost no object visible. I am assuming I am going back to center and manually find the object again, because when I was running this script with the click on image and the seed point started going near the edge I couldn't even change it manually, I clicked elsewhere and it did nothing.
