### ISSUE TITLE
Possible depth labelling problem with robot

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#501]
What do you think @miguelriemoliveira ?

We should really implement the delete points feature in the dataset reviewer

![image](https://user-images.githubusercontent.com/47574905/177185830-0a5ea4c2-ce0d-49b8-9f6c-ca8ea3aba4f3.png)

**Comment by miguelriemoliveira** [comment]
Yes, perhaps we should. Can you post a small bagfile please?

**Comment by danifpdra** [comment]
Here it is: https://we.tl/t-f6AgXH2CQu

I don't think we have the sync bagfiles folder in the larcc server so I used wetransfer. You have to run it with a bag_rate of at least 0.3 because of the sim time "problem"

**Comment by miguelriemoliveira** [comment]
> I don't think we have the sync bagfiles folder in the larcc server so I used wetransfer

What do you mean?

If its a new folder it copies ...

I will download and add.

**Comment by danifpdra** [comment]
The sync is only for the datasets folder, no?

**Comment by miguelriemoliveira** [comment]
Right, forgot about that. Sorry. I am doing a lot at the same time ... I will try to look at this later in the week.

**Comment by miguelriemoliveira** [comment]
@danifpdra ,

as I told you I cannot work on this until probably next september. Do you know how you could do it? Or we can wait til then ...

**Comment by miguelriemoliveira** [comment]
Fixed. Labeling for depth works fine now.
