### ISSUE TITLE
Images don't appear while calibration due to wrong configuration of rviz template

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#503]
Hi @miguelriemoliveira ,

You have changed the format of the number of the collections but you have not changed the configurations generated by the configure_calibration_package for example while calibrating...

![image](https://user-images.githubusercontent.com/47574905/177344363-26336d3e-618a-4103-8095-1c59dbe4d7da.png)

Now the images don't appear and we have to change to the correct topic if we want to visualize

**Comment by miguelriemoliveira** [comment]
Hi @danifpdra ,

right, If you know how to please do it ..., otherwise I will try to find  some time later this week.

**Comment by danifpdra** [comment]
Yes, I did it.. The question is... That value is static, always collection 000... For example, in my case I'm not using collection 000, I'm using only from 001 because the 000 was not good. So I can't see the images anyway... Is there any way that this value could be read in real time?

**Comment by miguelriemoliveira** [comment]
Hum, I don't think so. 

This Image displays only show one image of a sensor, so a collection must be selected.

I don't think there is a way, at configuration time, to know which is the best collection, so 000 is selected.

You may change it in RVIZ later on.

**Comment by danifpdra** [comment]
ok, it is solved then. closing
