### ISSUE TITLE
Evaluate if Realsense images are not fit for depth labelling 

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#505]
Several examples... Some are ok and some are not 

![image](https://user-images.githubusercontent.com/47574905/178462855-e922336f-20de-42b1-a5c7-14dd202a1fd4.png)
![image](https://user-images.githubusercontent.com/47574905/178463005-f44c0659-cae5-4ec3-a8ad-1e1a74df48a4.png)
![image](https://user-images.githubusercontent.com/47574905/178462723-01e903be-17d8-48c4-88e9-6ef2a9f695b2.png)
![image](https://user-images.githubusercontent.com/47574905/178463486-589a3a3a-26b0-4d3a-a64f-7f72cb525727.png)
![image](https://user-images.githubusercontent.com/47574905/178463545-b705a4b2-becd-4c99-b2e3-b22426294ea9.png)

**Comment by miguelriemoliveira** [comment]
Asus vs real sense

![image](https://user-images.githubusercontent.com/11350998/178501428-7534b132-7666-4d25-9eb3-450d7e7c5093.png)

**Comment by danifpdra** [comment]
![image](https://user-images.githubusercontent.com/47574905/180249967-f2d8479f-e782-41ac-9804-a04dc9503414.png)

**Comment by miguelriemoliveira** [comment]
I don't like the depth very much, but we can try to calibrate and see how it goes...

**Comment by danifpdra** [comment]
![image](https://user-images.githubusercontent.com/47574905/180410822-a54f912a-8b22-4e99-9222-41cdc0b95829.png)

**Comment by danifpdra** [comment]
![image](https://user-images.githubusercontent.com/47574905/180411533-bc02f80a-5bfa-402e-a01a-11e531d0e459.png)

**Comment by danifpdra** [comment]
I feel like a doctor analysing an x ray

![image](https://user-images.githubusercontent.com/47574905/180412565-b4f55472-b5eb-4c75-8f6f-824bc8b63bbc.png)

**Comment by miguelriemoliveira** [comment]
The data looks awful ...I would not use this camera.

**Comment by danifpdra** [comment]
so should I remove this from the paper?

**Comment by miguelriemoliveira** [comment]
No. Lets see the results ... whats the accuracy?
