### ISSUE TITLE
How should I annotate a calibration pattern that is not entirely visable?

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#511]
Hi @manuelgitgomes and @miguelriemoliveira ,

Take this example...

![image](https://user-images.githubusercontent.com/47574905/179958749-92f399ff-e300-4023-acfc-7bda843596bc.png)

This new annotation tool doesn't allow me to ignore one side of the chessboard... or maybe it does, and I don't know how. can you explain me?

**Comment by manuelgitgomes** [comment]
Hello! I had this problem as well. What I did was randomly click the side not used, and then clean it. It's not the best form, but it works.

**Comment by danifpdra** [comment]
How do I clean just one side @manuelgitgomes ?

**Comment by manuelgitgomes** [comment]
The letter "x" cleans all points from the current side!

**Comment by danifpdra** [comment]
oh ok, thanks

**Comment by miguelriemoliveira** [comment]
Thanks for helping  Manuel
