### ISSUE TITLE
Click mouse to indicate seed point in depth labeling does not entirely work

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#512]
I click and click and the seed point doesn't change

![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/47574905/180249814-f1c45922-5d43-4222-954c-755b63f5af6e.gif)

**Comment by miguelriemoliveira** [comment]
Hum, strange. Do you have the rviz version installed? Can you post the rostopic list?

**Comment by miguelriemoliveira** [comment]
Closing ... no feedback.
