### ISSUE TITLE
Ground Detected as Pattern

### ISSUE THREAD

**Issue by eupedrosa** [lardemua/atom#522]
Hi ATOM people.

The pattern detection jumps between the ground and the actual pattern.

![detection_jump](https://user-images.githubusercontent.com/6196901/180764912-dd84dcf7-410c-4117-8143-5050a400aa77.gif)

 Is there a way to filter the ground?

**Comment by miguelriemoliveira** [comment]
Hi @eupedrosa ,

You are also an "ATOM people"!

This is a know limitation. You have two options:

1. put the pattern a bit more above the ground
2. annotate the pattern manually using the dataset reviewer
