### ISSUE TITLE
Charuco pattern detection not working

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#537]
Spawned from #536 . 

Detection of pattern not working for @kovlo

**Comment by miguelriemoliveira** [comment]
From @kovlo

> But unfortunately now I'm struggling with the detection of my charuco board. (8x6 board with 2cm edges, 12cm size, 8cm inner size, 4x4 dictionary.) It currently detects only the half of it:
> Screenshot from 2022-09-21 16-40-44

**Comment by miguelriemoliveira** [comment]
The usual problem is a problem with the configuration of the pattern in the calibration/config.yaml of your calibration package.

@kovlo Can you post your config.yaml so I can take a look?

Also, you can make sure the configuration of the pattern is correct by using the test script view pattern, e.g.

    rosrun atom_calibration view_pattern.py

which has to be properly configured in order to work. This way you can be sure your parameters are correct.

**Comment by kovlo** [comment]
I checked my config line by line, and I configured my pattern with wrong row and column sizes.
Now the patterns seem to be detected, the rainbow colored markings are visible on the GUI as well, and I can run the calibration. 
But the results are not satisfying, I'm working on it to figure them out.

**Comment by miguelriemoliveira** [comment]
OK, let me know if you think I can help.

**Comment by kovlo** [comment]
> rosrun atom_calibration view_pattern.py

This is what is shows for this call: 
`rosrun atom_calibration view_pattern.py /camera/image_color -t charuco -d DICT_4X4_100 -x 7 -y 5 -L 120 -l 80`
Is this what I should expect?
![Screenshot from 2022-09-23 14-36-58](https://user-images.githubusercontent.com/12111565/191961886-5dc225a7-78c7-456d-bc60-50d79030db52.png)

When I run the calibration
(`rosrun atom_calibration calibrate -json /data/ATOM_Result/dataset.json -v -rv -si -oi`),
I observe the following:
- the board shown in the 3D view lies in an inaccurate orientation and position
- this is visible in the displayed image as well.
- the "texture" of the board is shown in small size between the colored marks.
![Screenshot from 2022-09-23 14-50-05](https://user-images.githubusercontent.com/12111565/191965082-e177070c-bc7d-4686-bae9-5c7df806708d.png)

I use calib.io_charuco_760x1000_8x6_120_93_DICT_4X4 board. The pdf was converted to svg and to dae using online tools, and it was specified in the calibration.yaml's mesh_file field. But this dae is not exactly the same as the calibration board (80mm vs 92mm inner figure size). When I used the original dae path, the behavior was the same.

Also, I have the intrinsic parameters of the camera, should I add them to the pointgrey camera driver when I record the calibration bag file?

If you have any suggestions, please share them with me.
Thanks again!

**Comment by miguelriemoliveira** [comment]
> This is what is shows for this call:
> rosrun atom_calibration view_pattern.py /camera/image_color -t charuco -d DICT_4X4_100 -x 7 -y 5 -L 120 -l 80
> Is this what I should expect?

No, I don't think its right, the circles should all be on the corners of the pattern. Is your dictionary correct? 

Try to have the pattern better illuminated to see if the detection is better ...

If you want, later this afternoon I can take a look at it, if you post a small bag file with the images ...

**Comment by eupedrosa** [comment]
Hi there. I belive the size must be in SI, i.e in meters not in millimiters.
Also, make sure the X and Y are not switched.

**Comment by kovlo** [comment]
Thank you @miguelriemoliveira  and @eupedrosa for your comments!
I set the W,H in wrong order as you pointed out, and even the sizes were in mm in the script I used (the config.yaml was good.)

This is what I see now, I hope it is closer to the expected:
![Screenshot from 2022-09-26 15-20-33](https://user-images.githubusercontent.com/12111565/192298942-861be020-c00e-444a-99b2-a48efa3a8387.png)
![Screenshot from 2022-09-26 15-47-37](https://user-images.githubusercontent.com/12111565/192298975-9cd020cb-190a-4d05-9be9-d6ace543a368.png)

Sorry for the false alarm, the detection errors came from my wrong configuration.

**Comment by miguelriemoliveira** [comment]
That's seems right. 

Let us know if you have other problems ahead.

I will close this issue.
