### ISSUE TITLE
Improve requirements.txt and installation tutorial

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#538]
In #536 there are some important tips we should include.

**Comment by kovlo** [comment]
`pip3 install prettytable`
is required for calibration.

**Comment by miguelriemoliveira** [comment]
> `pip3 install prettytable`
> is required for calibration.

Thanks. Added.

**Comment by kovlo** [comment]
These were also required (mentioned in the referenced issue). I copy them here:
```
readchar
urdf-parser-py
SQLAlchemy
open3d
```

**Comment by miguelriemoliveira** [comment]
Thanks @kovlo . 

I added all dependencies to the requirements.txt.
