### ISSUE TITLE
ATOM World Environment Package

### ISSUE THREAD

**Issue by JorgeFernandes-Git** [lardemua/atom#554]
Throughout the process of using ATOM, I noticed that I had to search for information that wasn't readily available. For example, I couldn't find a calibration world to record the bag, nor the script to interact with the pattern, at least in the ATOM repository. To address this, I decided to create a package that includes both of these items, which I then added to my branch. In addition, I developed a new script to simplify the process of recording rosbag files in the simulation.

It is a package that contains all the files needed to:

* Launch calibration studio where to spawn the robot:
```
roslaunch atom_worlds calibration_studio.launch
```
_________________
* Run **interactive** pattern:
```
rosrun atom_worlds interactive_pattern
```
_________________
* Run **autonomous** pattern:
```
rosrun atom_worlds autonomous_pattern
```
```
rosrun atom_worlds autonomous_pattern -vi
```
The camera topic can be configured on **camera.yaml** in the `config` folder.

I developed this script based on the idea of a self-moving pattern that responds to feedback from the camera. The pattern then remains static to allow the user time to save a collection.

**Watch it here:** https://youtu.be/7vii20Azfdk 

![Autonomous_pattern](https://user-images.githubusercontent.com/80167550/224743652-99c41ad3-5ff8-487a-aef9-a95c6fa00473.png)

_________________
* Launch rosbag record, after configure the topics to record (a template to a rosbag launch file):
```
roslaunch atom_worlds record_sensor_data.launch
```

**Comment by manuelgitgomes** [comment]
On commit [1684493](https://github.com/lardemua/atom/commit/16844939f13c0bdc368d77d1ffcee383c65669d9), I have made some adjustments to world package. Mainly, I corrected some bugs and changed some file names and locations, so it is more organized. I changed the `meshes` folder to `models`, renamed the `larcc` world to `calibration_studio`.
