### ISSUE TITLE
pattern in mmtbot is inverted in rviz

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#564]
Doing some experiments for comparing with #555 I noticed the pattern is inverted for mmtbot.

![image](https://user-images.githubusercontent.com/11350998/233788700-fcbd9bc7-08c6-49ec-a267-acb4e0481b60.png)

I think the problem is where the axis of the pattern are:

![image](https://user-images.githubusercontent.com/11350998/233788720-f372b730-e302-4a86-97d2-87647a9bc217.png)

**Comment by miguelriemoliveira** [comment]
The calibration works perfect though..., unlike #555, when I use a single camera sensor the starting point already has below 1 pixel error...

**Comment by miguelriemoliveira** [comment]
The same is true for the nrp ... provided we use the same sensor in the optimization and for computing the first guess

![image](https://user-images.githubusercontent.com/11350998/233790129-cf20fe49-6a0e-452a-ac1a-29d692c74b36.png)

**Comment by miguelriemoliveira** [comment]
@danifpdra , do you also have the pattern inverted in mmtbot?

**Comment by danifpdra** [comment]
No

![image](https://user-images.githubusercontent.com/47574905/233953344-74d716fe-3d1c-4446-8e22-66460dda9e2b.png)

**Comment by miguelriemoliveira** [comment]
That's strange. Do you have mmtbot up to date?

**Comment by danifpdra** [comment]
> That's strange. Do you have mmtbot up to date?

Yes, I've checkeed

**Comment by miguelriemoliveira** [comment]
> > That's strange. Do you have mmtbot up to date?
> 
> Yes, I've checkeed

Strange. Let me check again.

**Comment by miguelriemoliveira** [comment]
Well I cannot use your dataset because I have a crash

```
rosrun atom_calibration calibrate -json /home/mike/datasets/mmtbot/dataset_31_03_2021/data_collected.json -v -rv -si -uic -csf "lambda x: x not in ['001','002','003','004','005','006']" --phased -ssf "lambda x: x not in ['hand_camera']" 

Traceback (most recent call last):
  File "/home/mike/workspaces/catkin_ws/devel/lib/atom_calibration/calibrate", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/mike/workspaces/catkin_ws/src/calibration/atom/atom_calibration/scripts/calibrate", line 486, in <module>
    main()
  File "/home/mike/workspaces/catkin_ws/src/calibration/atom/atom_calibration/scripts/calibrate", line 106, in main
    dataset, json_file = loadResultsJSON(args["json_file"], args["collection_selection_function"])
  File "/home/mike/workspaces/catkin_ws/src/calibration/atom/atom_core/src/atom_core/dataset_io.py", line 64, in loadResultsJSON
    if not (sensor['modality'] == 'rgb' or sensor['modality'] == 'lidar3d' or sensor['modality'] == 'lidar2d' or
KeyError: 'modality'
INFO - 2023-04-24 11:05:41,034 - core - signal_shutdown [atexit]
```

I remember we added this modality key. How are you running this and on which dataset?

**Comment by danifpdra** [comment]
> Well I cannot use your dataset because I have a crash
> 
> ```
> rosrun atom_calibration calibrate -json /home/mike/datasets/mmtbot/dataset_31_03_2021/data_collected.json -v -rv -si -uic -csf "lambda x: x not in ['001','002','003','004','005','006']" --phased -ssf "lambda x: x not in ['hand_camera']" 
> 
> Traceback (most recent call last):
>   File "/home/mike/workspaces/catkin_ws/devel/lib/atom_calibration/calibrate", line 15, in <module>
>     exec(compile(fh.read(), python_script, 'exec'), context)
>   File "/home/mike/workspaces/catkin_ws/src/calibration/atom/atom_calibration/scripts/calibrate", line 486, in <module>
>     main()
>   File "/home/mike/workspaces/catkin_ws/src/calibration/atom/atom_calibration/scripts/calibrate", line 106, in main
>     dataset, json_file = loadResultsJSON(args["json_file"], args["collection_selection_function"])
>   File "/home/mike/workspaces/catkin_ws/src/calibration/atom/atom_core/src/atom_core/dataset_io.py", line 64, in loadResultsJSON
>     if not (sensor['modality'] == 'rgb' or sensor['modality'] == 'lidar3d' or sensor['modality'] == 'lidar2d' or
> KeyError: 'modality'
> INFO - 2023-04-24 11:05:41,034 - core - signal_shutdown [atexit]
> ```
> 
> I remember we added this modality key. How are you running this and on which dataset?

You asked me for the dataset we used in the paper... it's possible it's deprecated

**Comment by danifpdra** [comment]
[small_test.zip](https://github.com/lardemua/atom/files/11309219/small_test.zip)


Try this one

**Comment by miguelriemoliveira** [comment]
> You asked me for the dataset we used in the paper... it's possible it's deprecated

Right, I think it is. I will test the one you sent now.

**Comment by danifpdra** [comment]
Anyway, you should have access to all datasets... I don't know if you remember, but you made a script to sync the dataset folder of everyone and made us all put our datasets there

**Comment by miguelriemoliveira** [comment]
> Anyway, you should have access to all datasets... I don't know if you remember, but you made a script to sync the dataset folder of everyone and made us all put our datasets there

Right. I forgot : - )

**Comment by miguelriemoliveira** [comment]
For this dataset its fine:

![image](https://user-images.githubusercontent.com/11350998/233968897-9aa6a817-d624-471d-979a-7e0a27396130.png)

How / when did you create this dataset?


Can you test with [my dataset simple](https://drive.google.com/file/d/1CIGPd3QSNpdHRIGtwsCtYKOKInRVg0aS/view?usp=sharing)?

    rosrun atom_calibration calibrate -json /home/mike/datasets/mmtbot/small_test/dataset.json -v -rv -si -uic -csf "lambda x: x not in ['001','002','003','004','005','006']" --phased -ssf "lambda x: x not in ['hand_camera']"

**Comment by danifpdra** [comment]
It's fine 

![image](https://user-images.githubusercontent.com/47574905/233970501-ce871003-e7ca-46f5-a234-ea62efe5af29.png)


You have that information in the dataset metada:

```
{
  "_metadata": {
    "dataset_name": "small_test",
    "date": "Tue Jan 25 18:15:39 2022",
    "robot_name": "mmtbot",
    "timestamp": "1643134539.3365257",
    "user": "daniela",
    "version": "2.0"
  },
```

**Comment by miguelriemoliveira** [comment]
Thanks. And your opencv version is?

mine is 4.6.0

**Comment by danifpdra** [comment]
Mine is the same

**Comment by miguelriemoliveira** [comment]
> Mine is the same

I am starting to get upset with this #"#$"#ng thing...

**Comment by danifpdra** [comment]
> > Mine is the same
> 
> I am starting to get upset with this #"#$"#ng thing...

I don't know how to help you :(

**Comment by miguelriemoliveira** [comment]
Hi @danifpdra ,

I developed a new view_pattern3d.py script which not only detects the pattern but also computes its pose in 3D and publishes a tf. I want to make sure you are detecting the pattern the same way I am.

Can you please run an experiment to compare with me?

First, git pull atom and download the [simple bagfile from mmtbot](https://drive.google.com/file/d/1PFNtyc-2t-gkYnCaGl18zq6wlR1tm2AN/view?usp=share_link).

Then, reconfigure your calibration package

    rosrun mmtbot_calibration configure

Then launch the bagfile playback:

    roslaunch mmtbot_calibration playbag.launch bag_rate:=0.4

and finally, launch the pattern detector scritpt:

    clear && rosrun atom_calibration view_pattern3d.py -t charuco -d DICT_5xX_100 -x 11 -y 8 -L 0.06 -tn /world_camera/rgb/image_raw -cit /world_camera/rgb/camera_info

The questions is how do you see the frame of the pattern. Mine in the image below is like this (the one more to the right):

![image](https://user-images.githubusercontent.com/11350998/233992059-be411f9f-ea2c-4685-a536-cfbf3bea3d4e.png)

So in my case z points away from the cameras ... is yours like this as well?

**Comment by danifpdra** [comment]
Hi @miguelriemoliveira ,

I had a lot of errors running this in the file collect/patterns.py because of deprecated function of the cv2.aruco package...

Finally I manage to run it ,  results here

![image](https://user-images.githubusercontent.com/47574905/234030587-77659a8d-fbeb-415f-b02d-7a517cac8081.png)

**Comment by danifpdra** [comment]
Can you pull atom and check if it still works for you?

**Comment by miguelriemoliveira** [comment]
Now I get this error:

```
[ERROR] [1682352449.499708, 839.695690]: bad callback: <bound method SimplePatternDetector.onImageReceived of <__main__.SimplePatternDetector object at 0x7f77dadf4ac0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/mike/workspaces/catkin_ws/src/calibration/atom/atom_calibration/scripts/deprecated/view_pattern3d.py", line 82, in onImageReceived
    ret, rvecs, tvecs = cv2.solvePnP(objp[ids], np.array(corners, dtype=np.float32), K, D)
cv2.error: OpenCV(4.6.0) /io/opencv/modules/calib3d/src/solvepnp.cpp:831: error: (-215:Assertion failed) ( (npoints >= 4) || (npoints == 3 && flags == SOLVEPNP_ITERATIVE && useExtrinsicGuess) || (npoints >= 3 && flags == SOLVEPNP_SQPNP) ) && npoints == std::max(ipoints.checkVector(2, CV_32F), ipoints.checkVector(2, CV_64F)) in function 'solvePnPGeneric
```

**Comment by miguelriemoliveira** [comment]
Hi @danifpdra ,

I had to roll back your changes because I could not make it work. We are back using the CharucoBoard_create... We can try to make it work for you in zoom.

**Comment by miguelriemoliveira** [comment]
Upgraded the code to also show the coordinate system on the image. Z is pointing outwards

![image](https://user-images.githubusercontent.com/11350998/234067419-55ed4df0-f5b5-4c87-8268-f9da47cc7920.png)

**Comment by danifpdra** [comment]
Did you push the code to show the coordinate system? When I run that script no coordinate system appears

**Comment by danifpdra** [comment]
anyway, my coordinate system is different than yours

![image](https://user-images.githubusercontent.com/47574905/234549403-cc2353f8-fd3c-46c7-ae9e-1859931a3887.png)

**Comment by miguelriemoliveira** [comment]
> Did you push the code to show the coordinate system? When I run that script no coordinate system appears

Hi @danifpdra ,

sorry, only now I could return to this. I think I forgot. Can you try again?

**Comment by miguelriemoliveira** [comment]
> anyway, my coordinate system is different than yours

Actually, when I compare this image of yours [with mine](https://github.com/lardemua/atom/issues/564#issuecomment-1520048499) I think they are the same no?

**Comment by danifpdra** [comment]
No, the red axis is pointing to the screen in mine

**Comment by miguelriemoliveira** [comment]
Right, I was looking at the z axis only, because the x axis can change when you move the pattern.

In any case, can we talk. I am not sure today is a good day for you ... if not, no problem.

**Comment by danifpdra** [comment]
> Right, I was looking at the z axis only, because the x axis can change when you move the pattern.
> 
> In any case, can we talk. I am not sure today is a good day for you ... if not, no problem.

Sorry, I forgot to answer you. we can talk, yes

**Comment by danifpdra** [comment]
Anyway, in your picture, if you compare the pattern's axis with the other axis in the picture, the red and green are switched and they don't match the other axis.

**Comment by miguelriemoliveira** [comment]
Duplicate of #630. Closing.
