### ISSUE TITLE
Calibration of the Real ZauBot 

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#570]
Create originally at:

https://github.com/JorgeFernandes-Git/zau_bot/issues/18 

Discussion to continue here.

**Comment by miguelriemoliveira** [comment]
![image](https://user-images.githubusercontent.com/11350998/234703291-c48a7c48-13c8-4e90-9ef8-a050ed1aeaa6.png)

This bagfile is strange. There periodic stops in the sending of joints

**Comment by JorgeFernandes-Git** [comment]
This can be closed. 
The problem was solved by using the average time stamp instead of the max time.

https://github.com/lardemua/atom/blob/91c8c3848969ae4d605f8140beec5e4bf6ecea7e/atom_calibration/src/atom_calibration/collect/data_collector_and_labeler.py#L293-L294

**Comment by miguelriemoliveira** [comment]
This is nice because using the average should be much better in theory. I remember I removed it because of some specific system and then forgot to restore it.
