### ISSUE TITLE
Create a script to change a transformation from dynamic to static in a bagfile

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#584]
@JorgeFernandes-Git your should be aware of this.

Because of #578  we decided to add a verification on the calibration package configuration to check if the transformations defined to be optimized are static (#581).

If now, the configuration fails. we cannot calibrate the system.

One solution would be to "convert"  a dynamic transformation in a bagfile into a static one.

**Comment by miguelriemoliveira** [comment]
Implemented and tested. Seems to be working fine. @JorgeFernandes-Git , can you test to see if it solves the [problem of the zau_full_calibration bagfile](#578)?

**Comment by JorgeFernandes-Git** [comment]
Hi @miguelriemoliveira.

I'm testing this:

I run a test for 10 seconds:
```
rosrun atom_calibration dynamic_to_static_tf_rosbag -bfi zau_full_calibration_train_bag.bag -bfo test.bag -p zau/base_link -c base_link
```

Got the message:
```
Converting bagfile. Please wait.
Processing bag messages:   1%|██                                                                                                                                          | 5997/411400 [00:00<00:34, 11746.35it/s]
Finished in 2.61 seconds.
Created a /tf_static of transform zau/base_link to base_link
Removed 99 transformations from bag.
```

But the test bag come like this:
![tf_tree](https://github.com/lardemua/atom/assets/80167550/935f000b-2241-4b87-9bee-9e0e02e385d3)

The tree is disconnected.

**Comment by miguelriemoliveira** [comment]
Hi @JorgeFernandes-Git ,

Hum, I have to look into it...

**Comment by miguelriemoliveira** [comment]
Hi @JorgeFernandes-Git ,

I just run for the entire bag and the results are ok:

![image](https://github.com/lardemua/atom/assets/11350998/d7e9c17d-6282-4090-9b75-bc5caf033760)

Are you sure you updated before running? You seem to have a different version~.
What do you mean run a test for 10 secs? That was a debug version. Now it should process the entire bagfile.

**Comment by JorgeFernandes-Git** [comment]
Can you send me?

**Comment by miguelriemoliveira** [comment]
Run it again in your bag file. Its much easier no?

**Comment by miguelriemoliveira** [comment]
This is not working. @JorgeFernandes-Git , let me know when you have a simpler bag file for testing.

**Comment by JorgeFernandes-Git** [comment]
I create a simple bag to test this script where:
* static_child is published 1 time on /tf_static;
* dynamic_child is published on /tf at a rate of 10 Hz.

![image](https://github.com/lardemua/atom/assets/80167550/0879f059-5f7f-44e6-95dd-06214c906515)

Bag info:

```
path:        fake_bag.bag
version:     2.0
duration:    27.4s
start:       May 22 2023 19:20:18.93 (1684779618.93)
end:         May 22 2023 19:20:46.37 (1684779646.37)
size:        58.3 KB
messages:    275
compression: none [1/1 chunks]
types:       rosgraph_msgs/Log  [acffd30cd6b6de30f120938c17c593fb]
             tf2_msgs/TFMessage [94810edda583a504dfda3829e70d7eec]
topics:      /rosout        2 msgs    : rosgraph_msgs/Log 
             /tf          272 msgs    : tf2_msgs/TFMessage
             /tf_static     1 msg     : tf2_msgs/TFMessage
```

After run the script like this:

```
rosrun atom_calibration dynamic_to_static_tf_rosbag -bfi fake_bag.bag -bfo mod.bag -p parent -c dynamic_child
```

I got this result: 

```
path:        mod.bag
version:     2.0
duration:    0.3s
start:       May 22 2023 19:20:18.93 (1684779618.93)
end:         May 22 2023 19:20:19.27 (1684779619.27)
size:        12.0 KB
messages:    4
compression: none [1/1 chunks]
types:       rosgraph_msgs/Log  [acffd30cd6b6de30f120938c17c593fb]
             tf2_msgs/TFMessage [94810edda583a504dfda3829e70d7eec]
topics:      /rosout      2 msgs    : rosgraph_msgs/Log 
             /tf_static   2 msgs    : tf2_msgs/TFMessage
```

With this tf tree:

![image](https://github.com/lardemua/atom/assets/80167550/6ea7c130-abeb-462c-bccc-8742c6baf414)


**Conclusion: Seems the result is what we expected.**

**Comment by JorgeFernandes-Git** [comment]
The bags:

[Original](https://drive.google.com/file/d/1Atz4DxusPhx6qNVRIToOjfpRGerYJYl-/view?usp=sharing)
And:
[Modified](https://drive.google.com/file/d/13VniP05sW3z0xiO3URwHd6h8VQjeeH7q/view?usp=share_link)

**Comment by JorgeFernandes-Git** [comment]
@miguelriemoliveira.

I also made this script to try to remove tfs from the bag:

https://github.com/JorgeFernandes-Git/zau_bot/blob/Zau_INESCTEC/zau_bot_bringup/scripts/delete_tfs_in_bagfile.py

I'm trying other ideas.

**Comment by JorgeFernandes-Git** [comment]
Hi @miguelriemoliveira.

After reading more about this, I realize that the /tf_static should have one message, with all the static tfs.

"tf2_ros provides the [StaticTransformBroadcaster](http://docs.ros.org/jade/api/tf2_ros/html/c++/classtf2__ros_1_1StaticTransformBroadcaster.html) class that manages a vector of transforms, (...) calling sendTransform automatically adds the transforms you pass and publishes everything in a single message."

After inspect with `rosbag info` other good bags I have, I notice that all of them have one message.

**Comment by JorgeFernandes-Git** [comment]
Hi @miguelriemoliveira.

After running some tests I discovered that the real problem is on the script.

Here is an example:
Before running the scipt:
![image](https://github.com/lardemua/atom/assets/80167550/1c0a1073-6887-44ba-80db-25ae360b3640)


After running:
```
rosrun atom_calibration dynamic_to_static_tf_rosbag -bfi e3_rgb2agv.bag -bfo test.bag -p base_link_mb -c wheel_left_link
```
Here is the tf_tree:
![image](https://github.com/lardemua/atom/assets/80167550/3439baa5-e5e7-4a13-8d86-13b623083905)

All the static tfs are erased... I try some ideas, but no futher sucess.

**Comment by JorgeFernandes-Git** [comment]
I repeat the previous experiment but with 2 dynamic frames:

![image](https://github.com/lardemua/atom/assets/80167550/8e1b3ba1-1964-4893-8507-113091098d44)

Run the same command:
```
rosrun atom_calibration dynamic_to_static_tf_rosbag -bfi new_fake_bag.bag -bfo new_test.bag -p parent -c dynamic_child
```

Result:
![image](https://github.com/lardemua/atom/assets/80167550/f29040e9-dc21-4137-93e3-a0e9925e1416)

The tf_static are erased again.

**Comment by JorgeFernandes-Git** [comment]
Running on the test.bag:

```
rqt_bag new_test.bag
```

![image](https://github.com/lardemua/atom/assets/80167550/65c208b0-fdbd-4766-8dc3-872f67d0ea38)


The tf_static are there ...... But don't appear on the tf_tree.

[New_fake_bag.bag](https://drive.google.com/file/d/1lCWJSYExbEXB4DghQn1tGHaXDB7MHY-3/view?usp=sharing) - Original
[New_test.bag](https://drive.google.com/file/d/1kDvQV71_IEqbgQijyaRw9qhuFrUa8I8k/view?usp=sharing) - Created by the script

**Comment by miguelriemoliveira** [comment]
We now have lots of experiments. I have created a repository for rosbag tools [here](https://github.com/miguelriemoliveira/rosbag_tools).

**Comment by miguelriemoliveira** [comment]
Hi @JorgeFernandes-Git ,

finally, this is solved. Check https://github.com/miguelriemoliveira/rosbag_tools/commit/7dfc7dd95faa92a116963624526f6654a081da6c

As I said, I created a new repository named [rosbag_tools](https://github.com/miguelriemoliveira/rosbag_tools) for collecting several rosbag processing scripts.

In the particular case of **zau_full_calibration_train_bag.bag** #578, to repair you should run:

1. Aggregate all msgs on tf_static topic into a single one:

    ./aggregate_tf_static_msgs -bfi ~/bagfiles/zaubot/zau_full_calibration_train_bag.bag

2. Move the desired transform from the tf to the tf_static topic:

    ./dynamic_to_static_tf -bfi ~/bagfiles/zaubot/aggregated.bag -p zau/base_link -c base_link

After this the bag runs smooth. You can play the bag and only later run rqt and you'll see the complete tree without disconnections.

Let me know if you have some problems.
