### ISSUE TITLE
Empty folder in "Collect Data" calibration step

### ISSUE THREAD

**Issue by cobvinicius** [lardemua/atom#586]
Hello. 
I'm following the calibration steps through https://lardemua.github.io/atom_documentation/procedures/.

However, during "Collect Data" step, at the end of the process, the folder where the collections were supposed to be is empty, so the collections are not being saved. I don't know if I'm doing something wrong, but I've tried several times and the result is the same.

**Comment by miguelriemoliveira** [comment]
Hi @cobvinicius ,

thanks for the interest.

You have to give me more details. With that information I cannot help.
What is your system like? Do you have a bagfile and a repository with the calibration package that you can share?

Regards,
Miguel

**Comment by cobvinicius** [comment]
Hello @miguelriemoliveira.

My repository is on: https://github.com/cobvinicius/DigiAqua and my bagfile: https://uapt33090-my.sharepoint.com/:u:/g/personal/viniciuscob_ua_pt/ETmMYNSnitFPm9DtzvqkHFgB0hPcQMGnsSCX7-BGtCjt7w?e=BTggqI

I am trying to run the command: roslaunch digiaqua_calibration collect_data.launch output_folder:=/home/vinicius/catkin_ws/src/DigiAqua/datasets bag_rate:=0.5 overwrite:=true

The rviz opens normally and I can separate the image collections. However, when finishing the process through the terminal, the images are not saved where they are supposed to be...

Thanks,
Vinicius Batista

**Comment by miguelriemoliveira** [comment]
Hi @cobvinicius ,

I cannot access the repository. Probably its private?

**Comment by cobvinicius** [comment]
Sorry.
I guess you can access now.

Thanks,
Vinícius Batista

**Comment by miguelriemoliveira** [comment]
Hi @cobvinicius ,

I looked into the bagfile. It is very large a took a while to download.

I noticed it has redundant information. If you save the raw images, you should not also save the compressed images in the bagfile (you also have an additional format theora also being saved). Its like having a very large file, compressing it, and them sending as attachment in an email both the compressed version and the large file.

ATOM supports the usage of compressed images in a bagfile. What it does is setup a decompression mechanism in the automatically produced launch files. However, I am not sure this mechanism gets confused for having both the image and the compressed image in the bagfile. This is not usual.

You have two options:

1. Record a new bagfile with the correct topics
2. Repair the existing bagfile by removing the topics raw and theora from the bag.

Concerning 2. you can check this library

https://github.com/miguelriemoliveira/rosbag_tools

And use the delete_topic script to remove the redundant transforms. Just to give you an idea, when doing this we go from 4.5 GB in the original bagfile to 178MB !!!

**Comment by miguelriemoliveira** [comment]
Hi @cobvinicius 

For me it works fine. You should read the documentation in atom and watch a couple of videos on how to collect data.
You must right click the green sphere in the image is to record a collection

![image](https://github.com/lardemua/atom/assets/11350998/d87012c3-1135-4f70-b22f-26968fac6ddb)

Then you have another problem. Your images are not being correctly labelled. Without correct labels in any of the sensors, the collection is useless and therefore is not saved.  In image above, you should see markers on top of the chessboard, denoting it was detected.

I looked into the config.yml and noticed you set the wrong number of corners. Your chessboard is a 7x10, and not an 8x11.
After changing I can get labels in the images:

![image](https://github.com/lardemua/atom/assets/11350998/0f313123-030a-4b00-b4c1-37d190dfb182)

**Comment by miguelriemoliveira** [comment]
I tried to fix the config.yml but I do not have permissions to write to the repository ...

**Comment by cobvinicius** [comment]
I followed these tips and managed to solve the problem, thank you very much for your help!

**Comment by miguelriemoliveira** [comment]
> I looked into the config.yml and noticed you set the wrong number of corners. Your chessboard is a 7x10, and not an 8x11.
> After changing I can get labels in the images:

Great.
