### ISSUE TITLE
Issue with the flag "use_tfs"

### ISSUE THREAD

**Issue by tomchol** [lardemua/atom#591]
Hi. First, thank you for your work. 
I have an issue with the code. For some reasons, when I am using the function set_initial_estimate, I get the following error.

![Screenshot from 2023-06-14 18-08-38](https://github.com/lardemua/atom/assets/62744934/6c50bd0e-9ac4-4f10-ac70-616f53d1eed0)

But when I put the flag "use_tfs" in the playbag.launch to true, the error gets resolved and everything is working. What I don't understand is, why should someone not publish the tfs from the rosbag? The dynamic  values from the arms moving are stored in this rosbag. For the static transforms I can understand, but not for the dynamics ones. 
Is there something I am missing? I am currently assuming that is errors comes from the fact that the tfs are not published hence the program does not detect the transform between two parts of my system. 

Thanks for the help, I hope it's clear. 
Regards,
Tom

**Comment by JorgeFernandes-Git** [comment]
Hi @tomchol. 

The set_initial_estimate usually works without problems.

In your error seems like the world frame is not encontered in the bag file. 

Is this frame in the bag file? 
Can you show the tf_tree of the bag_file and the summary.pdf generated by ATOM?
