### ISSUE TITLE
Documentation is wrong

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#604]
The steps here are not correct

https://lardemua.github.io/atom_documentation/procedures/#using-a-different-configuration-file

When I use the -h flag, the output is:

`Usage: /home/daniela/catkin_ws/src/calibration/camerabot/camerabot_calibration/scripts/configure -c config_file.yml
-e 	-c Name of specific configuration file that must be inside the package_calibration/calibration/ folder.`

So the flag is -c and not -cfg, and I don't understand what the flag -n would be but it's not mentioned here

**Comment by miguelriemoliveira** [comment]
Fixed. Thanks for the tip.
