### ISSUE TITLE
Bad sensor assignement for normalizer

### ISSUE THREAD

**Issue by manuelgitgomes** [lardemua/atom#611]
Hello @miguelriemoliveira!

I found the error, finally. (or at least one of them).

In the following line, the normalizer is calculated:

https://github.com/lardemua/atom/blob/6df1489bb7087e6057b3587a5a4740392830dce1/atom_calibration/scripts/calibrate#L441

Imagine I have two sensors. a depth and an rgb camera. Imagine they are named `depth_camera` and `camera`. 
When the normalizer of the rgb camera is being calculated, the residuals of the rgb and the depth camera are considered, as they both `camera` in their sensor key.

To solve this, a verification must be applied in the calibration configuration.

**Comment by miguelriemoliveira** [comment]
Great work. Thanks

**Comment by miguelriemoliveira** [comment]
This should be closed, right @manuelgitgomes ?

**Comment by manuelgitgomes** [comment]
It is now @miguelriemoliveira
