### ISSUE TITLE
Calibrate rgb_rgb_system robotic system (former ase_2rgb)

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#620]

**Comment by miguelriemoliveira** [comment]
This is complete. Only the evaluation is missing but this is not working for now (#641 )

**Comment by miguelriemoliveira** [comment]
@brunofavs you can try to calibrate from your side following the instructions?

https://github.com/lardemua/atom/blob/noetic-devel/atom_examples/rgb_rgb_system/README.md

**Comment by brunofavs** [comment]
Hey
Ok I will work on it in the morning before our meeting and see what I can accomplish!
