### ISSUE TITLE
Depth to RGB evaluation failing when there is incomplete collections 

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#621]
@manuelgitgomes @miguelriemoliveira  FYI

I will fix this

**Comment by manuelgitgomes** [comment]
Hello Daniela. Sorry, I didnt merge my changes into the main branch. Fix this and I will implement it. Thanks

________________________________
From: Daniela Rato ***@***.***>
Sent: Friday, September 29, 2023 2:26:15 PM
To: lardemua/atom ***@***.***>
Cc: Manuel Gomes ***@***.***>; Mention ***@***.***>
Subject: [lardemua/atom] Depth to RGB evaluation failing when there is incomplete collections (Issue #621)


@manuelgitgomes<https://github.com/manuelgitgomes> @miguelriemoliveira<https://github.com/miguelriemoliveira> FYI

I will fix this

**Comment by danifpdra** [comment]
Hi @manuelgitgomes , it's fixed and pushed
