### ISSUE TITLE
Meshes from pattern are on the opposite side

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#630]
This is the problem, when running calibrate, e.g.:

    rosrun atom_calibration calibrate -json $ATOM_DATASETS/rgb_rgb_system/dataset1/dataset.json -v -rv -si -uic -csf 'lambda x: int(x)< 5'

![image](https://github.com/lardemua/atom/assets/11350998/b647d857-9ca8-4836-923d-7e30656ee302)

I know @manuelgitgomes also has this problem, but for @danifpdra its ok.

Do you confirm?

Should investigate why this occurs ...

**Comment by danifpdra** [comment]
I also have that problem during the calibration phase

![image](https://github.com/lardemua/atom/assets/47574905/4befbb89-cd86-430a-b30b-d6d5ae938be5)

**Comment by miguelriemoliveira** [comment]
Hi @danifpdra , 

so you too? I was under the impression it was fine for you. That means me, you and @manuelgitgomes all have this problem. It must be fixed.

I think its because of this:

https://github.com/opencv/opencv-python/issues/755

**Comment by miguelriemoliveira** [comment]
Solved. Had to create a new charuco pattern with a distinct coordinate system,

The new pattern is called **charuco_800_600_5x5_100**, where the last part is the reference of the aruco dictionary.

I will remove the old charuco_800x600 from the atom_worlds repo, but we have many robotic systems which still have it defined internally (see the example of [mmtbot](https://github.com/miguelriemoliveira/mmtbot/tree/main/mmtbot_gazebo/models/charuco_800x600) ).

In these cases, I recommend that the intervention deletes the local **charuco_800x600** pattern  and replaces it by the atom_worlds **charuco_800_600_5x5_100** pattern.

Also had to change several stuff in atom_worlds such as de world definition to include this new pattern.

I also want to rename and alter the structure of atom_worlds, but we'll do it later.

![image](https://github.com/lardemua/atom/assets/11350998/d815d2ea-5ed1-4447-85d3-29f02110013d)

**Comment by miguelriemoliveira** [comment]
Will push when branch called issue629 is merged.
