### ISSUE TITLE
Depth labeling not excluding image edges (both automatic and manual)

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#644]
![image](https://github.com/lardemua/atom/assets/47574905/e38a121e-abd7-43ea-af63-e89d977aeb3b)

**Comment by danifpdra** [comment]
This is also happening in the dataset_playback... This wasn't happening before

![image](https://github.com/lardemua/atom/assets/47574905/4ebb38a8-33b8-4a1d-af55-abeb98c8e06c)

**Comment by danifpdra** [comment]
We should add some "rubber" to delete faulty edges

**Comment by danifpdra** [comment]
The problem seems to be inside the function labelDepthMessage

**Comment by danifpdra** [comment]
Changed the filter_border_edges in the function arguments and seems to solve the problem?

```
        labels, gui_image, _ = labelDepthMsg(msg, seed=None, bridge=None,
                                             pyrdown=0, scatter_seed=True,
                                             scatter_seed_radius=8,
                                             debug=False,
                                             subsample_solid_points=7, limit_sample_step=1,
                                             filter_border_edges=0.05,
                                             pattern_mask=pattern_mask)

```

This argument wasn't set for inside the depth_manual_labeling.py script

**Comment by danifpdra** [comment]
Solves the problem for vertical limits but not for horizontal limits

![image](https://github.com/lardemua/atom/assets/47574905/184c5e6d-a59f-4493-9ae9-e9231f4aeb72)

**Comment by danifpdra** [comment]
The problem seems to be that the image has some weird black huge edges around the actual image??

![image](https://github.com/lardemua/atom/assets/47574905/02697328-3646-4506-bf05-00edbe042103)

**Comment by danifpdra** [comment]
Solved for vertical edges by filtering 7.5% of the image in each border

**Comment by miguelriemoliveira** [comment]
Thanks @danifpdra ,

So the edge near to image boundaries already exists, but the problem now are there gigantic holes in the pattern near the bottom?

**Comment by danifpdra** [comment]
> Thanks @danifpdra ,
> 
> So the edge near to image boundaries already exists, but the problem now are there gigantic holes in the pattern near the bottom?

No, I think the problem is that the real depth maps have a huge back frame around the actual image

**Comment by danifpdra** [comment]
If you see in the image above, I am clicking on the black part in the bottom and side and it still is recognized by the click on image plugin

**Comment by miguelriemoliveira** [comment]
Hum, ok. I will investigate.

**Comment by miguelriemoliveira** [comment]
Hi @danifpdra ,

I noticed the argument **filter_border_edges=0.05** has a value. 

did you try to change it to see if it works?

**Comment by danifpdra** [comment]
> Solved for vertical edges by filtering 7.5% of the image in each border

Yes, I told you here. But the same value doesn't work for all the edges

**Comment by danifpdra** [comment]
Hi @miguelriemoliveira,

I told you I would come back with more bugs!

This didn't work for vertical edges

![image](https://github.com/lardemua/atom/assets/47574905/086cd896-947e-416e-bbf4-4556e7c460aa)

**Comment by danifpdra** [comment]
It works for right edge

![image](https://github.com/lardemua/atom/assets/47574905/aa6b8e64-2d5e-4809-adc3-3d33f1db01a5)

**Comment by miguelriemoliveira** [comment]
There was a bug. I restructured and now I think its working. Can you try it please?

**Comment by miguelriemoliveira** [comment]
There a problem though. For simulated images the entire top part of the image is nans. 

I tested with atom_examples/rgb_depth_system

    roslaunch rgb_depth_system_calibration dataset_playback.launch

and then

    rosrun atom_calibration dataset_playback -json $ATOM_DATASETS/rgb_depth_system/rgb_depth_system_example_train_dataset/dataset.json -ow

This is what happens. With this user defined polygon:

![image](https://github.com/lardemua/atom/assets/11350998/8a28edcb-6efd-432d-91df-ac41e06aef66)

we get this:

![image](https://github.com/lardemua/atom/assets/11350998/419dd3fe-2008-4b2b-bae4-105d04d7c669)

Notice how the upper corner has the border points removed.

 I think there is nothing we can do here. My suggestion is to add a flag in the **labelDepthMsg** called **remove_nan_border** 

If **remove_nan_border** == False  -> run the border detection assuming the entire image canvas, like we did before

If **remove_nan_border** == True  -> run the border detection using the detection of the nan frames around the image

You agree? I added this parameter already to test, but now we must add the functionality to set it from the command line when we call 

    rosrun atom_calibration dataset_playback -json $ATOM_DATASETS/rgb_depth_system/rgb_depth_system_example_train_dataset/dataset.json -ow

If you agree I will do it ...

**Comment by danifpdra** [comment]
I think it's a good idea

**Comment by miguelriemoliveira** [comment]
Implemented. The argument is called remove_nan_border, you can use it like this:

    rosrun atom_calibration dataset_playback -json $ATOM_DATASETS/rgb_depth_system/rgb_depth_system_example_train_dataset/dataset.json -ow --remove_nan_border

Notice that by default it does not remove the border, i.e., will work poorly for your real images from hell.

**Comment by danifpdra** [comment]
It works poorly anyway in the images from hell 🥲

![image](https://github.com/lardemua/atom/assets/47574905/45a3f912-dead-4f8a-8914-caf44afc4f78)

**Comment by danifpdra** [comment]
Something weird happened here...
![image](https://github.com/lardemua/atom/assets/47574905/29d96889-bfe0-4116-bf58-bcbd60379d1c)

**Comment by miguelriemoliveira** [comment]
How can I replicate the error?
