### ISSUE TITLE
Problem with dependencies

### ISSUE THREAD

**Issue by manuelgitgomes** [lardemua/atom#647]
Hello @miguelriemoliveira!

I found an error in our `requirements.txt`.
Most of our dependencies in there don't define a specific version.
This means that, when installed, it defaults to the latest version.
This creates an error because of `numpy`.

Numpy's versions after 1.20 have some breaking changes, such as the deprecation of `np.float`.
This is a problem because `ros_numpy` has not been updated to change this, although there are issues and PR on their repository warning them about it.

This could be easily solved by downgrading numpy to a version below 1.20.
However, other dependencies installed from the `requirements.txt` are dependent on versions above 1.20.
Therefore, I believe we must define the specific versions of every package in a machine where it all works.
What do you think?

**Comment by miguelriemoliveira** [comment]
I think this was fixed in #650
