### ISSUE TITLE
Hand-eye evaluation metrics

### ISSUE THREAD

**Issue by manuelgitgomes** [lardemua/atom#656]
Hello @miguelriemoliveira!

To compare ATOM with other hand-eye calibration, some special metrics are needed.
They were already used on our paper "A General Approach to Hand–Eye Calibration Through the Optimization of Atomic Transformations".
Where are they? 
Should I create them?

**Comment by miguelriemoliveira** [comment]
Hi @manuelgitgomes ,

I do not think there are any special metrics. If you read through the paper you will see we only use the reprojection error and the translation and rotation errors, exactly what we typically use in ATOM.

**Comment by manuelgitgomes** [comment]
Hello @miguelriemoliveira 

But the error needed is the error between poses of one sensor, not between two sensors.
This is inter-collection for the same sensor, but this was not developed at the time of this article, right?
Or am I confusing everything?

**Comment by miguelriemoliveira** [comment]
Hi @manuelgitgomes ,

I think that for the reprojection errors we used two cameras. You are right, we did not have inter-collection errors at that time for sure.
