### ISSUE TITLE
Calibrate not deleting collections that do not have at least one RGB detection 

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#658]
When the calibration script starts running, it outputs

`Deleted collections: []: at least one detection by a camera should be present.`

Nevertheless, it is not deleting collections where there isn't RGB detections. 

In this dataset, collection 19 doesn't have any RGB detection:

![image](https://github.com/lardemua/atom/assets/47574905/3cb57b8f-caf7-4ea5-b623-092ff37fc097)

And the calibration script crashed with the following error 

`ValueError: Cannot set initial estimate for pattern at collection 019`

**Comment by danifpdra** [comment]
FYI @miguelriemoliveira

**Comment by miguelriemoliveira** [comment]
Hi @danifpdra ,

please give me the steps to reproduce so I can test a solution.

**Comment by danifpdra** [comment]
Hi @miguelriemoliveira,

Collection 19 has no RGB detection. 

To calibrate without 19

`rosrun atom_calibration calibrate -json /home/daniela/datasets/larcc_subset/real/train/dataset_corrected.json -v -uic -csf 'lambda x: int(x) not in [19]'`

To calibrate with 19

`rosrun atom_calibration calibrate -json /home/daniela/datasets/larcc_subset/real/train/dataset_corrected.json -v -uic`

Dataset is: https://we.tl/t-4bHBXWmhdv
And should be inside datasets/larcc_subset/train/
Please pull larcc

**Comment by miguelriemoliveira** [comment]
Hi @danifpdra ,

I looked into this. This is the expected behaviou, but the error message looked like a crash.

Now the output of the script it:

```terminal
ATOM Error: Cannot set initial estimate for pattern at collection 019. You must run the calibration without this collection. Check the csf flag.
```

That means that this collection does not have and rgb detection, and for that reason atom cannot create an initial estimate, which means it cannot carry out with the calibration.
