### ISSUE TITLE
Use depth annotations in lidar_to_depth_evaluation

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#661]
After #660, we should use the depth annotations in the evaluation scripts.

**Comment by miguelriemoliveira** [comment]
I think its working. 

![image](https://github.com/lardemua/atom/assets/11350998/782b9eae-8796-4617-830c-369f05e8e60e)

@danifpdra , can you try?

First annotate the depth sensor depth images using the **annotate_pattern_borders_in_rgb_or_depth**.

Then, use the **lidar_to_depth_evaluation** script with the --use-annotations flag.

**Comment by danifpdra** [comment]
Ok, I will try now. This also needs to be adapted for the depth_to_depth evaluation

**Comment by danifpdra** [comment]
The script works fine, thank you

**Comment by miguelriemoliveira** [comment]
> The script works fine, thank you

781433 + 1 coffees

**Comment by danifpdra** [comment]
> > The script works fine, thank you
> 
> 781433 + 1 coffees

Maybe I should start counting coffees for all the bugs I've found in ATOM......

**Comment by miguelriemoliveira** [comment]
Not sure what you are talking about ...

**Comment by danifpdra** [comment]
yes, yes... you should give me a position as ATOM's quality control engineer
