### ISSUE TITLE
Use depth annotations in depth_to_depth_evaluation

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#662]
#661

**Comment by miguelriemoliveira** [comment]
@danifpdra did this already, without any reference to any issue, completely under the radar, right Daniela ? : - )

**Comment by danifpdra** [comment]
I did this, yes. It's pushed

**Comment by miguelriemoliveira** [comment]
> I did this, yes. It's pushed

I was just looking at the code now and could not find it anywhere ... thanks.
