### ISSUE TITLE
Is the depth modality error during calibration in meters or pixels

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#668]
Here it says meters, but I am not sure about this

![image](https://github.com/lardemua/atom/assets/11350998/796dc179-1496-487c-b174-6132d1df1fc1)

**Comment by manuelgitgomes** [comment]
Hello! This is for calibration, right? I tried finding this in evaluation and could not find it.

If it is, I believe they are meters, as their cost functions is the same one for lidars, which is in meters.

If this is for evaluation, it should be pixels yes.

**Comment by miguelriemoliveira** [comment]
Yes, its during calibration.

In that case the table is correct. Thanks @manuelgitgomes
