### ISSUE TITLE
List known calibration procedures

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#67]
https://github.com/ethz-asl/kalibr

https://github.com/mikeferguson/robot_calibration

**Comment by eupedrosa** [comment]
@miguelriemoliveira take a look at https://github.com/tudelft-iv/multi_sensor_calibration

**Comment by miguelriemoliveira** [comment]
Gravilla is a huge name in autonomous driving, I think he is the guy from Mercedes ...

**Comment by eupedrosa** [comment]
Should this be closed?

**Comment by miguelriemoliveira** [comment]
Yes. Its too old.
