### ISSUE TITLE
Fixing rgb to rgb evaluation

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#671]
RGB to RGB evaluation was wrong

When we evaluate a calibration, we need two datasets: a train dataset, where we get the transformations between the links and a test dataset, where we get the data to evaluate. 

The problem is that in this script, we were evaluating were using the test dataset transformations to evaluate the script, which caused big problems specially with real data... I fixed this and will investigate further on other scripts to make sure this didn't happen in others.

**Comment by danifpdra** [comment]
FIY @manuelgitgomes @miguelriemoliveira

**Comment by miguelriemoliveira** [comment]
This was a great catch @danifpdra . Congratulations!

**Comment by miguelriemoliveira** [comment]
@danifpdra , don't forget to check if all other evaluation script have a similar problem.

Thanks again for finding this big bug.

**Comment by danifpdra** [comment]
Getting weirdly high translation errors for real data... will investigate

![image](https://github.com/lardemua/atom/assets/47574905/b2b708a6-86ef-4143-9003-b18924f6d91b)

**Comment by miguelriemoliveira** [comment]
Closing this one.
