### ISSUE TITLE
Place pattern link in calibration configuration transformation tree PDF

### ISSUE THREAD

**Issue by Kazadhum** [lardemua/atom#676]
What the title says. I think it would be useful to spot mistakes in the calibration configuration that wouldn't cause an error when running the script (such as poorly defined pattern parent links).

Tagging @miguelriemoliveira, @manuelgitgomes and @danifpdra for visibility.

**Comment by miguelriemoliveira** [comment]
Here's an example of what we have now.

![image](https://github.com/lardemua/atom/assets/11350998/604d62aa-52b9-4ea0-a25f-2bc4debad92b)

The goal is to also represent the calibration pattern and the transformation from it to its parent coordinate frame.

**Comment by miguelriemoliveira** [comment]
@Kazadhum , when creating new issues always add them to project Ongoing work on general calibration (the only existing one) please.

**Comment by miguelriemoliveira** [comment]
Implemented. Here's the new look:

![image](https://github.com/lardemua/atom/assets/11350998/3475a317-0d5f-49ec-a46e-d9eb5d30d28b)

also works for additional_tfs, here's an example with an additional transform from the tripod to the tripod_plate:

![image](https://github.com/lardemua/atom/assets/11350998/15c14f3b-e3f5-4520-97dc-7b84b9fb59d6)

and when the pattern is fixed, the text changes:

![image](https://github.com/lardemua/atom/assets/11350998/548f541c-1008-4154-ac0a-d5d16f12989d)

**Comment by Kazadhum** [comment]
> @Kazadhum , when creating new issues always add them to project Ongoing work on general calibration (the only existing one) please.

@miguelriemoliveira will do!
