### ISSUE TITLE
Use of XACRO to retrieve robot name

### ISSUE THREAD

**Issue by manuelgitgomes** [lardemua/atom#679]
Hello @miguelriemoliveira,

In this block of code:
https://github.com/lardemua/atom/blob/b673399dd6850a0c4ac2f7f53a2177274b06c8d6/atom_calibration/src/atom_calibration/collect/data_collector_and_labeler.py#L361-L362

We load and parse the robot description file defined in the configuration.
This is done to retrieve the robot name to add to metadata of dataset.

I have two problems with this:
Firstly, we are parsing xacros as URDF.
In xacro, we can have values mapped to properties, which URDF does not support and it creates error while parsing these specific cases.

Secondly, we are loading and parsing the robot description for each collection.
Since the robot name does not change between collections, this should only be done once.

My suggestion is to have the robot name as a parameter in the configuration yaml.

**Comment by miguelriemoliveira** [comment]
Hi @manuelgitgomes ,

thanks for the comments. I understand the limitations you point out. They make sense.

I do not like your suggestion so much, because it brakes all datasets we have collected before.
Also, couldn't we retrieve the name of the robot by parsing the xacro when configuring the calibration package?

**Comment by manuelgitgomes** [comment]
Hello @miguelriemoliveira,

Yes, good point.
We can see if there is a python library that parses it, if not, we can convert the xacro to urdf beforehand and parse the urdf

**Comment by manuelgitgomes** [comment]
Hello @miguelriemoliveira!

I did not find anything to parse xacros on python.
We now have two options.

Firstly, we can convert the xacro to urdf and store it in one of the calibration package directories.
This, to me, is not optimal, as we add an unwanted file and this removes the cleanness ATOM has.
Another option is to use the option `from_parameter_server()` from the `urdf_parser_py`.
This involves setting the robot_description parameter when running `collect_data.launch` or using the bag file description.
Then the python script reads the description from the parameter server.
I believe this might be the best option and I can start working on this now.

**Comment by miguelriemoliveira** [comment]
Hi @manuelgitgomes ,

My suggestion would be to convert the xacro to an urdf and put that urdf in the /tmp folder. 
Then analyse the urdf. 

We do this already somewhere in ATOM.

**Comment by manuelgitgomes** [comment]
Closed with #682
