### ISSUE TITLE
playbag.launch has wrong path to optimized URDF

### ISSUE THREAD

**Issue by manuelgitgomes** [lardemua/atom#681]
In the playback template:

https://github.com/lardemua/atom/blob/b673399dd6850a0c4ac2f7f53a2177274b06c8d6/atom_calibration/templates/playbag.launch#L42-L43

The optimized path should be `package_name/urdf/optimized/optimized.urdf.xacro`

**Comment by miguelriemoliveira** [comment]
I remember @danifpdra was doing something here, but I never like the solution much. @danifpdra , can you explain please?

**Comment by danifpdra** [comment]
Hummm that is wrong because the file was being saved in the wrong folder... later on I fixed that but I must've not change the playbag.launch...

**Comment by miguelriemoliveira** [comment]
Ok, thanks @danifpdra . Will you fix it then?

**Comment by miguelriemoliveira** [comment]
Fixed. Now we can calibrate and after we run 

roslaunch rgb_hand_eye_system_calibration playbag.launch optimized:=true

and can see how well things overlay. For example, running without a good calibration, we get:

![image](https://github.com/lardemua/atom/assets/11350998/bc7d7fc3-1504-41e8-b924-b12464385cb2)


and after a good calibration the overlay is perfect.

![image](https://github.com/lardemua/atom/assets/11350998/e2e457c1-f4f5-47eb-a0d7-14e96db77682)
