### ISSUE TITLE
Use jinja to render config.yml in create_calibration_pkg

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#684]
Right now we are just copying the config,yml template file from the template folder.

https://github.com/lardemua/atom/blob/d5685b1a715e340b6ec9f88cebd68aba5c3bf9b6/atom_calibration/scripts/create_calibration_pkg#L80-L84

We should use jinja to render the file, which opens the possibility of configuring the config.yml  rendered for each package.

**Comment by manuelgitgomes** [comment]
Closed with #682
