### ISSUE TITLE
Simulate motor encoder angular offset 

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#691]
In the sequence of #689, we decided not to include the joint states in the atom datasets, and continue to use the transformations exclusively.

We do use joint states. The joint states are in the bagfiles, and they are used in ATOM (when we are not using --use-tfs ).

These messages are read by the robot state publisher to generate the transformations, so if we want to simulate an angular error in the measurement of a motor encoder we could develop a script to add noise to these messages before they reach the robot state publisher.

From this it should be easy:

https://github.com/miguelriemoliveira/rosbag_tools

What do you think @manuelgitgomes ?

**Comment by manuelgitgomes** [comment]
Yes, this might be the best way to do this without storing the joint states in atom datasets.

**Comment by miguelriemoliveira** [comment]
This is operational.

Created a new bag file with noise on the elbow joint using:

    rosrun atom_calibration add_noise_to_joint_state_in_bag -bfi train.bag -bfo train_with_noise.bag -jn elbow_joint -jd 0.3

so the new bag file should have the joint_states, joint "elbow", a 0.3 radians of error. 

When running playbag, the /tf topic (produced by the robot state publisher from the incorrect joints states) should now have a value which is different from the tf_ground_truth.

The following print shows this: The top terminal is listening to the /tf topic, which the bottom to the /tf_ground_truth topic. They are different!


![image](https://github.com/lardemua/atom/assets/11350998/ed12a1c0-6487-49a3-8f02-c24ed2fa896f)
