### ISSUE TITLE
Explicitly save the ground truth on the atom datasets

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#692]
Right now we have the ground truth when using simulated systems, but it is stored in a strange way.

We have first guess transformations, **which we know are the ground truth** when we used a simulation to produce the bag file, and we also know that we did not change anything either using the set initial position, the --nig flag during calibration, or what will eventually come from #691.

This is not a very good way of storing the information. Right now, the atom datasets are like this:

![image](https://github.com/lardemua/atom/assets/11350998/97b136ae-373e-4543-a165-c71a8526e2bf)

 It would be better to have something like: 

![image](https://github.com/lardemua/atom/assets/11350998/ad30d2ee-e387-41f1-9278-9ba4470f1701)

For real system the ground_truth_transforms would not exist, and when we ran a ground truth evaluation with a real bag it would abort saying there is no ground truth data.

@manuelgitgomes , what do you think?

**Comment by miguelriemoliveira** [comment]
Working on branch https://github.com/lardemua/atom/tree/miguelriemoliveira/issue692

**Comment by manuelgitgomes** [comment]
Yes, this change is a long time coming, as I remember having discussions about this in the past.

One thing to take into account is either to document this so that the user knows this is an option, or to add a parameters to the config.yml for simulation or gt transformations.

**Comment by miguelriemoliveira** [comment]
Hi @manuelgitgomes ,

I am already half way through the implementation. I am using a flag in the configure script.

**Comment by miguelriemoliveira** [comment]
Implemented. We now can get atom datasets with ground truth data.

![image](https://github.com/lardemua/atom/assets/11350998/762e5d9b-4b23-4245-b52a-98cbe279f759)

Here's a dataset example which contains ground truth.

[my_dataset.zip](https://github.com/lardemua/atom/files/13420217/my_dataset.zip)
