### ISSUE TITLE
Add tams small chessboard dae to atom

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#709]
To make some experiments related with #706 I need this. 

@manuelgitgomes can you please add it to atom?

**Comment by miguelriemoliveira** [comment]
When running 

    rosrun tams_pr2_atom_calibration configure

I get

```terminal
_______________________________________________________

           █████╗ ████████╗ ██████╗ ███╗   ███╗ 
          ██╔══██╗╚══██╔══╝██╔═══██╗████╗ ████║ 
          ███████║   ██║   ██║   ██║██╔████╔██║ 
          ██╔══██║   ██║   ██║   ██║██║╚██╔╝██║ 
   __     ██║  ██║   ██║   ╚██████╔╝██║ ╚═╝ ██║    _  
 / _|    ╚═╝  ╚═╝   ╚═╝    ╚═════╝ ╚═╝     ╚═╝   | |    
 | |_ _ __ __ _ _ __ ___   _____      _____  _ __| | __ 
 |  _| '__/ _` | '_ ` _ \ / _ \ \ /\ / / _ \| '__| |/ / 
 | | | | | (_| | | | | | |  __/\ V  V / (_) | |  |   <  
 |_| |_|  \__,_|_| |_| |_|\___| \_/\_/ \___/|_|  |_|\_\ 
 https://github.com/lardemua/atom

Configuring calibration package tams_pr2_atom_calibration
_______________________________________________________

Loading config_file /home/mike/workspaces/catkin_ws/src/calibration/robots/tams_pr2/tams_pr2_atom_calibration/calibration/config.yml

Traceback (most recent call last):
  File "/home/mike/workspaces/catkin_ws/devel/lib/atom_calibration/configure_calibration_pkg", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/mike/workspaces/catkin_ws/src/calibration/atom/atom_calibration/scripts/configure_calibration_pkg", line 108, in <module>
    config = atom_core.config_io.loadConfig(args['config_file'])
  File "/home/mike/workspaces/catkin_ws/src/calibration/atom/atom_core/src/atom_core/config_io.py", line 151, in loadConfig
    fullpath, name, uri = uriReader(config['calibration_pattern']['mesh_file'])
  File "/home/mike/workspaces/catkin_ws/src/calibration/atom/atom_core/src/atom_core/config_io.py", line 93, in uriReader
    assert (os.path.exists(fullpath)), Fore.RED + fullpath + ' does not exist.'
AssertionError: /home/mike/workspaces/catkin_ws/src/calibration/atom/atom_worlds/pattern/models/chessboard_200x214_5x4_25/chessboard_200x214_5x4_25.dae does not exist.
```

**Comment by manuelgitgomes** [comment]
Hello!

Yes, I have but I need to make some changes to the pattern configuration.

Also, can you briefly explain to me how you apply a texture to a mesh?
I tried doing it and could not achieve it, if you could help me, that would be great.

**Comment by miguelriemoliveira** [comment]
zoom?

**Comment by manuelgitgomes** [comment]
@miguelriemoliveira yes!

**Comment by miguelriemoliveira** [comment]
Ok, I am there now.

**Comment by miguelriemoliveira** [comment]
Using blender for adding texture 

https://www.youtube.com/watch?v=mURA2g1rOSc

**Comment by manuelgitgomes** [comment]
Hello @miguelriemoliveira 

I have done it, however the orientation is still incorrect. I will try to correct it!

**Comment by manuelgitgomes** [comment]
@miguelriemoliveira  well, I tried changing this is blender and it did not seem to change in rviz. Did you change it in meshlab?

**Comment by miguelriemoliveira** [comment]
Orientation what do you mean? Where the reference system is? That I know how ti do in meshlab.

I have family at home now, so only tonight I can get back to this.

**Comment by miguelriemoliveira** [comment]
Can you push the pattern with texture. I can then use meshlab to correct its origin ...

**Comment by manuelgitgomes** [comment]
> Can you push the pattern with texture. I can then use meshlab to correct its origin ...

It is already pushed!

**Comment by miguelriemoliveira** [comment]
To run I need #720  fixed.

I need to see the detections of the pattern in the images to figure out where the reference system should be.

**Comment by miguelriemoliveira** [comment]
Fixed. I imagine this is the coordinate system, but I need #720 to be sure.

![image](https://github.com/lardemua/atom/assets/11350998/20c919f7-2e0f-47a3-9a3b-48e0efe48da6)

@manuelgitgomes , can you describe how you added texture?

**Comment by manuelgitgomes** [comment]
> @manuelgitgomes , can you describe how you added texture?

I followed this:

https://blender.stackexchange.com/questions/36401/how-do-i-add-material-textures-to-only-one-face-of-an-object

**Comment by miguelriemoliveira** [comment]
I was able to run the tams_pr2_atom_calibration playbag.launch and test the labeler. It is confirmed that the reference frame is the one I thought before.

![image](https://github.com/lardemua/atom/assets/11350998/d295145e-d830-42a0-b2e4-2d0d0c3a09dc)

**Comment by miguelriemoliveira** [comment]
BTW, to create a box with the correct size I used this

https://blender.stackexchange.com/questions/31367/how-to-set-object-dimension
