### ISSUE TITLE
collect data crashes due to automatic data collector

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#710]
When running:

    roslaunch rgb_hand_eye_system_calibration collect_data.launch output_folder:=$ATOM_DATASETS/rgb_hand_eye_system/train_with_noise overwrite:=true

I get:

```terminal
Traceback (most recent call last):
  File "/home/mike/workspaces/catkin_ws/src/calibration/atom/atom_calibration/scripts/automatic_data_collector", line 163, in <module>
    main()
  File "/home/mike/workspaces/catkin_ws/src/calibration/atom/atom_calibration/scripts/automatic_data_collector", line 159, in main
    automatic_data_collector = AutomaticDataCollector(config)
  File "/home/mike/workspaces/catkin_ws/src/calibration/atom/atom_calibration/scripts/automatic_data_collector", line 78, in __init__
    atom_msgs.srv.ToggleAutomaticDataCollector,
AttributeError: module 'atom_msgs.srv' has no attribute 'ToggleAutomaticDataCollector'
```

I have git pulled atom, and compiled. Service seems to be defined in ros, as the command:

     rossrv list | grep atom

```terminal
atom_msgs/DeleteCollection
atom_msgs/GetAdditionalTfsInteractiveMarker
atom_msgs/GetDataset
atom_msgs/GetSensorInteractiveMarker
atom_msgs/SaveCollection
atom_msgs/SetAdditionalTfsInteractiveMarker
atom_msgs/SetSensorInteractiveMarker
atom_msgs/ToggleAutomaticDataCollector
```

@manuelgitgomes , can you take a look at this? I can't advance without collecting a dataset ...

**Comment by miguelriemoliveira** [comment]
Got it. You forgot to add the file ToggleAutomaticDataCollector.srv in the CMakeLists.txt of atom_msgs, so the service was not being compiled.

I guess the  **rossrv list** is not checking for compiled services, rather for *.srv files in atom packages.

**Comment by miguelriemoliveira** [comment]
In any case this change breaks the data collector and a new package configuration is needed. 

@manuelgitgomes , if we can we should avoid having to force all atom users to reconfigure their packages, but I think in this case it is unavoidable. We should have a mechanism to communicate this tough ... any ideas?

**Comment by manuelgitgomes** [comment]
> Got it. You forgot to add the file ToggleAutomaticDataCollector.srv in the CMakeLists.txt of atom_msgs, so the service was not being compiled.

I have no idea how this was not in here, as I remember adding it to my CMakeLists.txt and compiling everything.



> In any case this change breaks the data collector and a new package configuration is needed.

How come?
With the old `collect_data.launch` the automatic data collector is not used.
Are you saying it should?
If so, I can try and add this to the normal collect data script.

**Comment by miguelriemoliveira** [comment]
> I have no idea how this was not in here, as I remember adding it to my CMakeLists.txt and compiling everything.

Yeah, it is strange because you had to compile to use it. Anyways, problem solved. 


> > In any case this change breaks the data collector and a new package configuration is needed.
> 
> How come? With the old `collect_data.launch` the automatic data collector is not used. Are you saying it should? If so, I can try and add this to the normal collect data script.

I am not sure anymore why I said this. With all the changes with the joint calibration, people will have to re-configure anyway, so I would not worry so much about this.
