### ISSUE TITLE
Verify if joints to be calibrated do not collide with transformations to be calibrated

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#712]
In configure_calibration_pkg

**Comment by manuelgitgomes** [comment]
Shouldn't this be covered by stating that we cannot calibrate dynamics transformations?

Or is this a safe way to restrict joint calibration for revolute/prismatic joints?

**Comment by miguelriemoliveira** [comment]
Hi @manuelgitgomes ,

you are right, possibly the calibration of transformations and joints will not collide.

However, there are several nuances, and also we don't know how this is going to evolve, so I am of the opinion that it is better to explicitly test if we are simultaneously calibrating a transformation and a corresponding joint, and throw an error if so.

Note for example that we  calibrate the world to pattern transformation, which is not static. 
Also, for now we can only calibrate revolute joints, but we could in theory calibrate static joints.

**Comment by miguelriemoliveira** [comment]
Implemented.
