### ISSUE TITLE
resource not found: tams_motorhand_description

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#720]
Hi @manuelgitgomes ,

To complete #709, I needed to run the tams_pr2_atom_calibration from my side and this occurs

     resource not found: tams_motorhand_description

Where is this package?

**Comment by manuelgitgomes** [comment]
Hello @miguelriemoliveira 


Sorry, try [this rosinstall](https://github.com/TAMS-Group/rosinstalls/blob/master/noetic-tams-pr2.rosinstall).

There are one that are not public, but we don't need those for calibration.
So, be careful and remove the one from `git@git.crossmodal-learning.org` from the rosinstall.

To run it, [the repo](https://github.com/TAMS-Group/rosinstalls) has instructions on it.

**Comment by miguelriemoliveira** [comment]
Got it. Thanks. 

I am now able to run the tams_pr2_atom_calibration scripts from my side.
