### ISSUE TITLE
Can you share tams_pr2 bag file train_2023-11-09-09-53-17.bag

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#721]
That way I don't have to constantly change the config.yml in your tams_pr2_atom_calibration

Also, the robotic system name is **tams_pr2** right?

Thus, I think the bagfiles should be in 

$ROS_BAGS/tams_pr2

also for the datasets ...

Does it make sense for you, Can we change?

**Comment by miguelriemoliveira** [comment]
Trying to push to you tams_pr2 fork but could not do it. Can you give me permission?

**Comment by manuelgitgomes** [comment]
> That way I don't have to constantly change the config.yml in your tams_pr2_atom_calibration

Haven't I sent this to you already?



> $ROS_BAGS/tams_pr2

Done

> Trying to push to you tams_pr2 fork but could not do it. Can you give me permission?

Done

**Comment by miguelriemoliveira** [comment]
> Haven't I sent this to you already?

You sent me train_2023-11-09-09-53-17.bag. It has a different date ...

**Comment by manuelgitgomes** [comment]
> You sent me train_2023-11-09-09-53-17.bag

This is the bagfile you are asking me to send, right?

**Comment by miguelriemoliveira** [comment]
Ooops. Sorry. I mean 

"$ROS_BAGS/pr2/train_2023-11-16-08-49-46.bag"

This is the one you have on your config.yml

**Comment by manuelgitgomes** [comment]
I sent you with a different name: `tmp_2023-11-16-08-49-46.bag`

Nevertheless, I use the other as default now, as it is smaller.
This is changed in config.yml.

**Comment by miguelriemoliveira** [comment]
Ok, thanks.
