### ISSUE TITLE
Adding multiple pattern to calibration visualization for fixed pattern w.r.t. some robot part.

### ISSUE THREAD

**Issue by manuelgitgomes** [lardemua/atom#726]
Calibration visualization for cases with a fixed pattern only show a single pattern.
This makes sense if the pattern is fixed w.r.t. the world frame.
When the pattern is fixed to a part of the robot, we would want to see various patterns.

**Comment by manuelgitgomes** [comment]
Sorry, gave a wrong issue number in the commit message.
Nevertheless, on commit 4ac1fe345e47b0a3e07468ae0792e4ff4002cfa0, I solved this and now the visualization on the PR2 is much better:

![image](https://github.com/lardemua/atom/assets/58152228/5b1870a4-4612-46f3-b439-a18c036e624a)

**Comment by miguelriemoliveira** [comment]
looks really nice! Perhaps we could change the atom logo to it ...
