### ISSUE TITLE
not sure how to solve this one well ... if at least one is fixed?

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#734]
```
        # TODO not sure how to solve this one well ... if at least one is fixed?
```

https://github.com/lardemua/atom/blob/234402379ca3f290aa3efb6a43dbef80b25afa17/atom_calibration/scripts/configure_calibration_pkg#L765

**Comment by manuelgitgomes** [comment]
Well, supposing evaluation would be done w.r.t. various patterns, we would have to run an evaluation script for each combination of sensors + pattern.

Therefore, I think this block of code:

https://github.com/lardemua/atom/blob/234402379ca3f290aa3efb6a43dbef80b25afa17/atom_calibration/scripts/configure_calibration_pkg#L725-L789

Should run inside a for loop, for each pattern defined.

**Comment by manuelgitgomes** [comment]
I applied the suggestion I gave above and corrected the launch file for the atom_examples

**Comment by miguelriemoliveira** [comment]
Great. Thanks.
