### ISSUE TITLE
rgb_depth_system bag file link goes to rgb_rgb_system

### ISSUE THREAD

**Issue by manuelgitgomes** [lardemua/atom#735]
Hello @miguelriemoliveira.

The link for the bagfile for the `rgb_depth_system` goes to the bagfile of the rgb_rgb_system.
Can you fix it?

**Comment by miguelriemoliveira** [comment]
OK, But I must either create a new dataset, or use your conversion script. Can I do it with the conversion script? How?

**Comment by manuelgitgomes** [comment]
How come? 
You don't have the original bagfile?

I think my dataset converter already works for the changes we have applied.
There might be more changes that are not yet implemented and so it might be soon outdated.
To run it, just use:

`rosrun atom_calibration update_dataset_from_version_2_to_3 -json path/to/dataset -pn package_name`

**Comment by miguelriemoliveira** [comment]
Sorry, I understood dataset and not bagfile. I will fix the link soon,

Also, I will use your script to update the datasets and update those links as well.

**Comment by miguelriemoliveira** [comment]
Done.
