### ISSUE TITLE
now sure why this sorting is here so I am removing it

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#740]
https://github.com/lardemua/atom/blob/9fbc47643cd75302dbf9222c6c8a380135e4f2d1/atom_calibration/src/atom_calibration/calibration/patterns_config.py#L228

**Comment by manuelgitgomes** [comment]
Neither do I, but it is present in more parts of the code (possibly due to copying and pasting)

**Comment by miguelriemoliveira** [comment]
I think it was intended to use the same sensor always ...  @danifpdra do you remember this?

**Comment by miguelriemoliveira** [comment]
Removed.
