### ISSUE TITLE
Moving the pattern pose estimation from calibrate into dataset_collect

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#741]
Hi @manuelgitgomes ,

just an idea I had for discussion.

You know that in the calibrate script, we run the pattern pose estimation from an rgb camera that is in the dataset.

https://github.com/lardemua/atom/blob/9fbc47643cd75302dbf9222c6c8a380135e4f2d1/atom_calibration/src/atom_calibration/calibration/patterns_config.py#L40

This creates a patterns key in the dataset, which is then used to optimize. This approach has the problem of having to have an rgb sensor in the system, otherwise we cannot estimate a first guess for the pattern pose. Moreover, it creates those intricate dependencies in the filtering of collections that you solved in #727 .

My suggestion is: Move initial estimation of pattern poses to the dataset_collector and labeler. The advantages are:

1. We can show during collection the estimated patter pose
2. We can manually correct the estimated pattern pose, either during the collect stage or in the dataset_playback
3. We would loose those intricate dependencies in the filtering of dataset
4. We can drop the requirement of having an rgb sensor to create a first guess pattern pose:
4.1  If there are no cameras we can set the pattern's pose random, and ask the user to fix it.
4.2 We could even develop a pattern pose estimation based on lidar. If it fails, the user should fix it.

What do you think about this?

This would be a big change, but we are in the moment to carry out all the big changes we can remember...

**Comment by miguelriemoliveira** [comment]
Your comment disappeared? I received an email but now its now here ... did you delete?

**Comment by manuelgitgomes** [comment]
Honestly, seems a great idea.

I have some questions though.
Would we still have a fixed estimated pose or would it be different during the collection stage?
I.e., would you capture the estimated pattern pose from a camera in the beginning and keep it constant during the collection (adding the option for the user to manually change it)?
Or would this be changing whenever new images reach the sensors?
If so, how would we choose which sensor to prioritize?
Should we average the estimated poses?


And how would this alter the dataset?
Will we have a new parameters for each collection that is the pose of the pattern?
Would we add this to the transforms dictionary using the parent_link and pattern_link used on config?

If we have different transformations for each collection but the pattern is fixed, which one would we choose?
Would it be random? Would we average them? Would we calculate the residuals for all and chose the one with the lowest residuals?

Nevertheless, I fully agree with this change, but it sparks a lot of questions in me, and a lot of work.


> Your comment disappeared? I received an email but now its now here ... did you delete?

Regarding this, I left my comment in the middle, so I deleted it.

**Comment by miguelriemoliveira** [comment]
> I have some questions though.
> Would we still have a fixed estimated pose or would it be different during the collection stage?
> I.e., would you capture the estimated pattern pose from a camera in the beginning and keep it constant during the collection (adding the option for the user to manually change it)?
> Or would this be changing whenever new images reach the sensors?
> If so, how would we choose which sensor to prioritize?
> Should we average the estimated poses?

I think it should be handled like the labels are. We are continuously labeling sensor data, and when the user decides to save a collection we record the most recent label (which should be the one with the closest timestamp to the timestamp of the collection).

The problem of selecting which sensor to use we already have it now, and solve it trivially by selecting the first rgb sensor that appears on the list.

> And how would this alter the dataset?
> Will we have a new parameters for each collection that is the pose of the pattern?

Right now we detect the pattern and produce this:

![image](https://github.com/lardemua/atom/assets/11350998/0c579b8d-0609-4a81-b60c-c2a7b83137c3)

The idea is to produce the same information but during the collect stage. In sum, the dataset.json will be similar to the atom_calibration.json, as it will also have the key patterns.

> Would we add this to the transforms dictionary using the parent_link and pattern_link used on config?

I think we already take care of this. Just do like we did so far.

> If we have different transformations for each collection but the pattern is fixed, which one would we choose?
> Would it be random? Would we average them? Would we calculate the residuals for all and chose the one with the lowest residuals?

That's a good question. Right now, from what I saw in the code, we compute an initial_transform for each collection.
Then, if we have a fixed pattern, we use the initial_transformation of the selected_collection_key. So we use a single collection.

https://github.com/lardemua/atom/blob/9fbc47643cd75302dbf9222c6c8a380135e4f2d1/atom_calibration/scripts/calibrate#L328-L345

It is a trivial solution, but its only one to come up with a first guess, and we've seen that it has been good enough for now.

> Nevertheless, I fully agree with this change, but it sparks a lot of questions in me, and a lot of work.

Actually, the more I think of it, the easier I think it will be. Let me give it a shot this afternoon and get back to you.

**Comment by manuelgitgomes** [comment]
> The problem of selecting which sensor to use we already have it now, and solve it trivially by selecting the first rgb sensor that appears on the list.

Ok, it seems easier.
It would also be interesting to eventually test if averaging them would be better.



> It is a trivial solution, but its only one to come up with a first guess, and we've seen that it has been good enough for now.

The same comment for here, I agree it is easier to just use the first one.
However, it would also be interesting to eventually test if we can average it or find the one with lowest residuals.



> Actually, the more I think of it, the easier I think it will be. Let me give it a shot this afternoon and get back to you.

Great!

**Comment by miguelriemoliveira** [comment]
This is operational. Just calibrated eye_in_world_system after a collect data which computes the pattern poses.
Here's the dataset produced by collect _data.

![image](https://github.com/lardemua/atom/assets/11350998/bc463348-a4a6-432a-88ed-e74f9648de45)

The problem now is that all our datasets are deprecated, since they do not contain the patterns key.
To solve that, as we discussed, the dataset update script should be able to create this information when updating.

I opened #746 for that and will work on it. I know more or less what to do, since I did it just now in collect_data...

**Comment by miguelriemoliveira** [comment]
Messed up the commit message. Here's the commit,

https://github.com/lardemua/atom/commit/2e321656632f4a6fcec985ff966722e6ff90e1b6

**Comment by miguelriemoliveira** [comment]
Removing pattern pose estimation from calibrate script ...

**Comment by manuelgitgomes** [comment]
Great job!
