### ISSUE TITLE
Error in overwrite for collect data

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#742]
When running:

    roslaunch eye_in_world_system_calibration collect_data.launch output_folder:=~/eye_in_world_system/train overwrite:=false

```
Error: Dataset /home/mike/eye_in_world_system/train exists.
If you want to replace it add a "--overwrite" flag.

Traceback (most recent call last):
  File "/home/mike/workspaces/catkin_ws/devel/lib/atom_calibration/collect_data", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/mike/workspaces/catkin_ws/src/calibration/atom/atom_calibration/scripts/collect_data", line 154, in <module>
    data_collector = DataCollectorAndLabeler(args, server, menu_handler)
  File "/home/mike/workspaces/catkin_ws/src/calibration/atom/atom_calibration/src/atom_calibration/collect/data_collector_and_labeler.py", line 49, in __init__
    rospy.signal_shutdown()
TypeError: signal_shutdown() missing 1 required positional argument: 'reason'
================================================================================REQUIRED process [collect_data-6] has died!
process has died [pid 75236, exit code 1, cmd /home/mike/workspaces/catkin_ws/devel/lib/atom_calibration/collect_data -s 0.5 -o ~/eye_in_world_system/train -c /home/mike/workspaces/catkin_ws/src/calibration/atom/atom_examples/eye_in_world_system/eye_in_world_system_calibration/calibration/config.yml -ssl lambda sensor_name: False __name:=collect_data __log:=/home/mike/.ros/log/7080ec7e-905a-11ee-9402-cfc1d9b26e3c/collect_data-6.log].
log file: /home/mike/.ros/log/7080ec7e-905a-11ee-9402-cfc1d9b26e3c/collect_data-6*.log
Initiating shutdown!
```

**Comment by miguelriemoliveira** [comment]
With the new version I am getting this error. @manuelgitgomes you know why?

**Comment by manuelgitgomes** [comment]
Error: Dataset /home/mike/eye_in_world_system/train exists.
If you want to replace it add a "--overwrite" flag.

You need to define overwrite as true!

**Comment by miguelriemoliveira** [comment]
But its a launch file. It should be **overwrite:=false**

**Comment by miguelriemoliveira** [comment]
Sorry, sorry, stupid me. Forget it.

**Comment by miguelriemoliveira** [comment]
Hi @manuelgitgomes ,

did you change this part?

![image](https://github.com/lardemua/atom/assets/11350998/06c6845f-54b7-498d-ae33-1ff74de4180d)

Before I had a 

collections[collection_key]['labels'][sensor_key][pattern_key]

but now it is:

collections[collection_key]['labels'][pattern_key][sensor_key]

**Comment by manuelgitgomes** [comment]
> did you change this part?


Yes, because I said before that I would do

> collections[collection_key]['labels'][pattern_key][sensor_key]

But instead I did 






> collections[collection_key]['labels'][sensor_key][pattern_key]

So to keep the code consistent with my comment, I changed it. Do you prefer the other way around?
If so, tell me and I will revert the commit.

**Comment by miguelriemoliveira** [comment]
No, I can adjust from my side. Why would this way be more consistent?

**Comment by manuelgitgomes** [comment]
> No, I can adjust from my side. Why would this way be more consistent?

Because on my comment in issue #731 I say I would make it `collections[collection_key]['labels'][pattern_key][sensor_key]`.
So I changed my code to go with my words.

**Comment by miguelriemoliveira** [comment]
> So I changed my code to go with my words.

You mean what you say? That is really old fashioned :)
