### ISSUE TITLE
How to use atomPrintOk

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#748]
Hi @manuelgitgomes ,

you added the usage of atomPrintOk to the dataset update script, which is great. 
Just a matter of style we should agree upon, so that everything is consistent.

Your script prints this

![image](https://github.com/lardemua/atom/assets/11350998/5e1ca501-6a78-4e68-8bf4-862e90effd10)

Whereas configure_calibration_package prints this:

![image](https://github.com/lardemua/atom/assets/11350998/cc2a246b-ff59-4fdd-8f6e-c9342f95a66a)

The header with ATOM is missing. Use the 

    atomStartupPrint('Configuring calibration package ' + Fore.BLUE + package_name + Style.RESET_ALL)

for that.

About the [OK], I prefer the 

Starting to do this ... [OK]

but if your think 

Starting to do this[OK]

Looks better we can go with it. What do you say?

**Comment by manuelgitgomes** [comment]
> Starting to do this ... [OK]

This does look better.

I honestly implemented as I did because it was how it was done in the config update script.
I can change them both.

**Comment by miguelriemoliveira** [comment]
> I can change them both.

Great.

**Comment by manuelgitgomes** [comment]
Done, fully refactored on updaters (config and dataset)
