### ISSUE TITLE
Dataset v3.0, config.yml v2.0

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#749]
Wouldn't it be better to have a single version number for both, i.e. 3.0 for all?

**Comment by miguelriemoliveira** [comment]
@manuelgitgomes  what do you say?

**Comment by manuelgitgomes** [comment]
Hello @miguelriemoliveira 

I thought about that and I don't know.

We have the benefits of not introducing confusion by using different numbers for config and dataset.
And whenever there is a config update, there must be a dataset update.

The only thing that bothers me is that there might a dataset update that does not require a config update, and then we would have to change the config version without actually changing anything about it.

What do you think?

**Comment by miguelriemoliveira** [comment]
I think its better to have both with the same number. Less confusing. Think of it as an ATOM configuration version. 

Sometimes its caused by a change in the config, others by a change in the dataset.

**Comment by manuelgitgomes** [comment]
Ok, I can change the config, as I am working in #748

**Comment by manuelgitgomes** [comment]
Changed config version, as well as script names that mentioned conversion to version 2.
