### ISSUE TITLE
Create an atom_examples readme and a script to download all datasets at once.

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#755]

**Comment by miguelriemoliveira** [comment]
All done. Atom examples has a nice readme now:

![image](https://github.com/lardemua/atom/assets/11350998/eb274776-e018-4287-8dd6-ba6bfa07b86e)

Also, the download script is operational.

**Comment by manuelgitgomes** [comment]
Hello @miguelriemoliveira

Solved a bug where the program would because, for each system, a parent folder is needed.
Because I did not have them, it crashed.
Now the program creates the folder if needed.

Another problem, I download the rgb_rgb_system dataset first of the system's read me, and the dataset was not updated!

**Comment by miguelriemoliveira** [comment]
> Solved a bug where the program would because, for each system, a parent folder is needed. Because I did not have them, it crashed. Now the program creates the folder if needed.

Thanks!


> Another problem, I download the rgb_rgb_system dataset first of the system's read me, and the dataset was not updated!

Did you try using the overwrite flag?

**Comment by manuelgitgomes** [comment]
> Did you try using the overwrite flag?

Using the script, I had no problem, but I tried using the links of the readme and those were not correct.

**Comment by miguelriemoliveira** [comment]
The readme is still under construction.

In any case if you can let me know which links do not work. Its easier than searching for all of them ...

**Comment by manuelgitgomes** [comment]
This one:

https://github.com/lardemua/atom/blob/e47d4ad5605a2b63702ef30d1ea8f6bf81caeab2/atom_examples/rgb_rgb_system/README.md?plain=1#L85

**Comment by miguelriemoliveira** [comment]
> This one:
> 
> https://github.com/lardemua/atom/blob/e47d4ad5605a2b63702ef30d1ea8f6bf81caeab2/atom_examples/rgb_rgb_system/README.md?plain=1#L85

Fixed, thanks.
