### ISSUE TITLE
How to name atom examples

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#760]
rgb_hand_eye_system should be changed.

The logic for naming atom examples has been: 

\<modality\>_\<modality\>_\<configuration\>_system_\<pattern\>

which is a bit sluggish. Better to use :

\<modality\>_\<modality\>_\<configuration\>_\<pattern\>_system

or even:

\<modality\>_\<modality\>_\<additional distinctive characteristic\>_system

That means renaming the following atom examples:

rgb_hand_eye_system -\> rgb_in_hand_system

rgb_rgb_system_chessboard -\> rgb_rgb_chessboard_system

... -\> ...

but that results in very large names. So my decision is to go with smaller names, in the spirit of softbot and mmtbot. In this case, we define a name for the system, i.e.

Multi-modal test robot

and extract the acronym mmtbot. This is perhaps the best way, as it is the one we used successfully in the past.
We define the full name using the rules above, but then extract the acronym in mmtbot fashion.

Under this the examples would become:

Old name | Full new name | acronym
:---:|:---:|:---:
rgb_rgb_system | rgb_rgb_test_robot | rrtbot
rgb_depth_system |rgb_depth_test_robot | rdtbot
rgb_rgb_system_chessboard | rgb_rgb_chessboard_test_robot | rrctbot
rgb_hand_eye_system | rgb_in_hand_test_robot | rihtbot
eye_in_world_system | rgb_in_world_test_robot | riwtbot

This should be well defined as we plan to develop more examples in the future. I will wait for feedback before advancing since this is a large endeavor.

**Comment by miguelriemoliveira** [comment]
Actually, I think its better to drop the **test_robot** and keep only the **robot**, i.e.:

New examples we foresee in the near future are also in the table.

Old name | Full new name | acronym
:---:|:---:|:---:
rgb_rgb_system | rgb_rgb_robot | rrbot
rgb_depth_system |rgb_depth_robot | rdbot
rgb_rgb_system_chessboard | rgb_rgb_chessboard_robot | rrcbot
rgb_hand_eye_system | rgb_in_hand_robot | rihbot
eye_in_world_system | rgb_in_world_robot | riwbot
------- | rgb_in_hand_joint_optimization_robot | rihjobot
------- | rgb_in_world_joint_optimization_robot | riwjobot
------- | lidar_robot | lbot
------- | rgb_lidar_robot | rlbot
------- | rgb_multiple_patterns_robot | rmpbot

I think it looks cool. @manuelgitgomes ? @danifpdra, @Kazadhum ? Any ideas?

**Comment by Kazadhum** [comment]
Hello @miguelriemoliveira ! I think it's a good idea to have a standardized naming convention for these systems. I also agree with you that the current names are a bit too long.

I think the acronyms are a great idea, as long as we have this table (or something equivalent that shows the full name and corresponding acronym) in the documentation for users to easily find the correct packages.

The new convention looks good to me and I think it's worth doing the conversion, overall.

**Comment by miguelriemoliveira** [comment]
Thanks @Kazadhum .

**Comment by manuelgitgomes** [comment]
Agree with @Kazadhum.

This table (or something similar) should be on the atom examples readme!

**Comment by miguelriemoliveira** [comment]
> This table (or something similar) should be on the atom examples readme!

We have a better one (with the wrong names still : -) )

https://github.com/lardemua/atom/tree/noetic-devel/atom_examples

**Comment by miguelriemoliveira** [comment]
Thanks to all. I will move forward with the proposed renaming.
