### ISSUE TITLE
Improve summary.pdf display of joints

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#761]
Right now for the rgb_hand_eye_system we get

![image](https://github.com/lardemua/atom/assets/11350998/1d6b4c4e-302d-44ee-af02-ae007ab5356d)

**Comment by miguelriemoliveira** [comment]
Created a view_calibration_config script which produces a better (I think) schematic of a calibration configuration.

![image](https://github.com/lardemua/atom/assets/11350998/46059e1a-c8fd-48e9-9a15-483e0fc747d1)


Will integrate with configure_calibration_pkg asap.

**Comment by miguelriemoliveira** [comment]
@manuelgitgomes , @Kazadhum , @danifpdra , any comments? Any information missing? Any color to be changed?

I will convert this into a library and start using it in configure_calibration_pkg.

**Comment by manuelgitgomes** [comment]
Seems way better!

**Comment by Kazadhum** [comment]
I agree with @manuelgitgomes, it looks great, I think. I just have one question which is more on the theoretical side, @miguelriemoliveira, why is it called a 'position_bias' and not just a 'position'?

**Comment by danifpdra** [comment]
Seems good to me. Although the colors don't seem to catch a person's attention so much as the previous ones

**Comment by danifpdra** [comment]
> Seems good to me. Although the colors don't seem to catch a person's attention so much as the previous ones

**Comment by manuelgitgomes** [comment]
> I agree with @manuelgitgomes, it looks great, I think. I just have one question which is more on the theoretical side, @miguelriemoliveira, why is it called a 'position_bias' and not just a 'position'?

This is due to the way that joint_states are calculated in ROS.
They are read from the motor's encoders that might have different 0 positions than the joints.
This "position_bias" is the estimation of the bias in this position-
Is it more clear now?

**Comment by Kazadhum** [comment]
Yes, that makes sense, thank you @manuelgitgomes !

**Comment by miguelriemoliveira** [comment]
> why is it called a 'position_bias' and not just a 'position'?

Because it is a bias, meaning a constant compensation on the measured joint position.

**Comment by miguelriemoliveira** [comment]
Hi @danifpdra ,

can you try to improve the colors? Just change this

https://github.com/lardemua/atom/blob/d98a2af925a1c0200ace62f26e551d9ff54050b3/atom_calibration/scripts/utilities/view_calibration_config#L237-L244

and then run:

    roscd rgb_hand_eye_system_calibration && rosrun atom_calibration view_calibration_config -cfg config.yml -n rgb_hand_eye_system_calibration && evince summary.pdf


and see if you can propose a better solution ...

**Comment by miguelriemoliveira** [comment]
I am closing this one. @danifpdra if you find time to work on this reopen.

**Comment by miguelriemoliveira** [comment]
I will reopen this to push these aesthetic changes into the summary.pdf produced by the configure calibration pkg script.

**Comment by miguelriemoliveira** [comment]
Done. Configure calibration pkg now uses these colors as well. Also, passed the code to a library in atom_core.
