### ISSUE TITLE
Add instructions on how to run ATOM in ROS2

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#762]
Hi @dimaxano ,

I have just setup the documentation page where to put the instructions for running ATOM in ROS.

The atom documentation is hosted in this repository 

https://github.com/lardemua/atom_documentation

and there are instructions on how to run the compilation locally [here](https://github.com/lardemua/atom_documentation#usage).

I have set up a page to contain the instructions on how to use atom in ROS2.

Can I ask you to write the instructions in file [atom_in_ros2.md](https://github.com/lardemua/atom_documentation/blob/main/docs/atom_in_ros2.md)?

You do not have permissions to deploy, so the idea is to test locally and when you think everything is ok create a PR. I will accept and deploy to the public site.

If you don't have time let me know and I will try to do it when I have some spare time.

Thanks in advance,
Miguel

**Comment by dimaxano** [comment]
Hi, @miguelriemoliveira!

Sure, no problem!
I'll add instructions in the next 2-3 days

**Comment by miguelriemoliveira** [comment]
This is complete. Thanks again to @dimaxano .
