### ISSUE TITLE
estimatePatternPosesForCollection only works for charuco

### ISSUE THREAD

**Issue by manuelgitgomes** [lardemua/atom#763]
The new function estimatePatternPosesForCollection only works for charuco, not chessboards.
Will try to fix.

**Comment by miguelriemoliveira** [comment]
Right, thanks.

**Comment by manuelgitgomes** [comment]
Turns out it was just a warning.
The code was defining a CharucoPattern, even if the pattern was a chessboard.
Created a simple if clause to only create it if the pattern type is a charuco.
