### ISSUE TITLE
How will evaluation run when multiple patterns are present?

### ISSUE THREAD

**Issue by manuelgitgomes** [lardemua/atom#764]
Hello @miguelriemoliveira.

I want to know your opinion on how to run evaluation for multiple patterns.
Will you continue to run for a pair of sensors and we would retrieve the values for all patterns?
Or should it be for only one pattern with a flag that chooses the pattern to be used?

This is because I am changing things in evaluation files, might as well add this...

**Comment by miguelriemoliveira** [comment]
Hi @manuelgitgomes ,

I would say that right now we are producing N tables per sensor pair in the evaluation.

Now we have X patterns, so we will produce N*X tables per sensor pair.

Does it make sense?

**Comment by manuelgitgomes** [comment]
> Does it make sense?

Yes, but should all patterns be in a single run of the same script?
Or should they be in separate runs with the flag `--pattern_name` so that the user can choose which pattern to evaluate next?

Obviously this last option would be covered by full_evaluation.

**Comment by miguelriemoliveira** [comment]
> Yes, but should all patterns be in a single run of the same script?
> Or should they be in separate runs with the flag `--pattern_name` so that the user can choose which pattern to evaluate next?

Use the flag to name the pattern, if flag is not given show for all available patterns.

**Comment by miguelriemoliveira** [comment]
Hi @manuelgitgomes ,

I have completed #781 . Now we have a running example of a multi-pattern calibration. 

When you have time you can work on this. Just use the rihmpbot example readme.

**Comment by miguelriemoliveira** [comment]
This is an old one, despite being opened on December 4th. It shows how much we've advanced in a month. Closing.
