### ISSUE TITLE
Dataset playback crashes

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#771]
Hi @manuelgitgomes ,

I was trying to advance with #769. Because we have a lidar I need to use the dataset playback.

It crashes when we change the collection.  I thought it could be the lidar but then I tried  playing back the train dataset for teh rgb_rgb_system and it also crashes. 

Can you take a look?

BTW, the crash is strange. The script does not abort, it just hangs and after we change from the first to another collection, we can't do anything else.

**Comment by manuelgitgomes** [comment]
Hello @miguelriemoliveira.

I tried to replicate this with softbot2 and with rgb_rgb_system and all seemed to work...
What can we do?

**Comment by miguelriemoliveira** [comment]
Fixed. It was a problem of the path of the config file. It occurred only when we used 

    clear && rosrun atom_calibration dataset_playback -json dataset.json -ow

but not when we used 

    clear && rosrun atom_calibration dataset_playback -json ./dataset.json -ow

Now it works in both cases.
