### ISSUE TITLE
Depth camera cannot detect chessboard

### ISSUE THREAD

**Issue by afonsocastro** [lardemua/atom#78]

**Comment by afonsocastro** [comment]
Tried to calibrate according to http://wiki.ros.org/openni_launch/Tutorials/IntrinsicCalibration . 
Here is the calibrator:

![Screenshot from 2019-12-04 01-28-14](https://user-images.githubusercontent.com/47828797/70106269-12a66e00-163b-11ea-9f39-b2e308c49976.png)

It never detected the chessboard.
I tried without any light source, but also nothing... Tried with only the car presence lights (cover with paper, to diffuse the speckles), but still didn't detected the chessboard.

After that, and following the calibration tutorial, i only launched the rgb-d camera driver. In that way, there weren't any other nodes subscribing to RGB images besides the 3d camera. It also didn't solved the problem

**Comment by miguelriemoliveira** [comment]
Hi @afonsocastro , which command do you use?

Also, did you cover the IR projector as stated here "The simplest solution is to cover the projector (lone opening on the far left) with one or two Post-it notes, mostly diffusing the speckles"

**Comment by eupedrosa** [comment]
@afonsocastro, I think that you are using the wrong image. You should use the `/camera_name/ir/image` topic (or something similar).

**Comment by miguelriemoliveira** [comment]
Too old. Closing.
