### ISSUE TITLE
Create an atom example rgb rgb with multiple patterns (rihmpbot)

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#781]

**Comment by miguelriemoliveira** [comment]
Its better to have an example with a camera on a manipulator. Changing the name to rihmpbot ...

**Comment by miguelriemoliveira** [comment]
Drawing all patterns in the calibrate script

![image](https://github.com/lardemua/atom/assets/11350998/8e140a02-e9f3-4390-a695-7c4968faa7e0)

**Comment by miguelriemoliveira** [comment]
Also able to draw images with projections for when only a single pattern is detected

![image](https://github.com/lardemua/atom/assets/11350998/0b86d8a5-a1f8-44fa-ac31-03af25b49c32)



or in collections where all patterns are detected

![image](https://github.com/lardemua/atom/assets/11350998/002f281d-18dd-4822-bb98-c7380ab7fe47)

**Comment by miguelriemoliveira** [comment]
Calibration using multiple patterns works fine:

Here's the system

![system](https://github.com/lardemua/atom/assets/11350998/14dc6a74-bf10-4a97-936c-48a20678e08f)

and calibration results:

![calibration_output_final](https://github.com/lardemua/atom/assets/11350998/7a566aa9-c7b3-41c6-8f5d-b1da5aff2126)

**Comment by manuelgitgomes** [comment]
These are great news! Happy to see atom advancing with such strength

**Comment by miguelriemoliveira** [comment]
Now we have more time to work on it ...
