### ISSUE TITLE
Split data_collector into several ros nodes

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#789]
In #788, we had the idea before of splitting the collector node into several ros nodes, instead of using different threads.
We also thought about this some years ago. The reason was because we had some traffic problems in the ros message (#36), which were solved not very well. 

The idea we had was to put make each labeler  a different ros node which publishes to the new, much more simple data collector.

To synchronize the labels with the raw data, I think we should have label messages that contain both the raw data and the labels.

This will simplify the code before moving on to adding multiple pattern support #788.

**Comment by miguelriemoliveira** [comment]
RGB labeling node complete.

**Comment by miguelriemoliveira** [comment]
![image](https://github.com/lardemua/atom/assets/11350998/d5659356-725f-45f7-89bf-82aa9b1e4e70)

**Comment by miguelriemoliveira** [comment]
Works for rrcbot 

![image](https://github.com/lardemua/atom/assets/11350998/f3378883-2d38-4d7d-b290-274ba6b1e444)

**Comment by miguelriemoliveira** [comment]
Fails for rrbot for some reason

Despite have good marker detections

![image](https://github.com/lardemua/atom/assets/11350998/866c5273-52cd-404c-8ad3-f406e4eb505e)


The charuco corners are not well interpolated, which leads to failure in estimating the pattern pose.

![image](https://github.com/lardemua/atom/assets/11350998/fc93bb7f-7246-4c45-97be-c4280aa44863)

**Comment by miguelriemoliveira** [comment]
Ahh, for this pattern in particular the m*_*#$"ther fu***#"$"er needs the board to be defined like this:

```python
# self.board = cv2.aruco.CharucoBoard_create(size["y"] + 1, size["x"] + 1, length, marker_length,
            #    self.dictionary)
self.board = cv2.aruco.CharucoBoard_create(size["x"] + 1, size["y"] + 1, length, marker_length,
                                                       self.dictionary)
```

and with it a perfect detection:

![image](https://github.com/lardemua/atom/assets/11350998/e80a0888-373f-48d9-ab3b-1fe9a72349b4)

**Comment by miguelriemoliveira** [comment]
Ok, got it. It was a problem with the config files. Now it works fine for all patterns

![image](https://github.com/lardemua/atom/assets/11350998/c8d7e7b1-70a1-4067-a28a-71c117efdae6)

**Comment by miguelriemoliveira** [comment]
lidar3d labeler on the way ... 

![image](https://github.com/lardemua/atom/assets/11350998/7c12632e-5d7d-4573-be92-c4a8cf1b38cc)

**Comment by miguelriemoliveira** [comment]
Lidar3d labeler already publishes a labels msg.

**Comment by miguelriemoliveira** [comment]
Depth labeling working fine as an standalone node. Will now work on expanding the atom msgs to include depth labels.

![image](https://github.com/lardemua/atom/assets/11350998/abefe088-a791-4dd2-9bf2-fdd114f77e5d)

**Comment by miguelriemoliveira** [comment]
Now publishing the labels as ros messages.

**Comment by miguelriemoliveira** [comment]
Now I need to tweak the data collector to subscribe these labels messages ...

**Comment by miguelriemoliveira** [comment]
Actually, first I will work on making the configure calibration package script create a launch file that calls the well configured labelers ...

**Comment by miguelriemoliveira** [comment]
Done. We are launching the labelers automatically upon calibration package configuration.

**Comment by miguelriemoliveira** [comment]
Now we need to change the data collector to:

1. subscribe the labels topic published by the labelers, instead of the raw data streaming from the sensors
2. Receive the labels messages and convert those to an atom dataset format.

**Comment by miguelriemoliveira** [comment]
I think this is complete. 

I changed a lot in the **data_collector_and_labeler.py**, now **collect data_collector.py** as it does not label anything anymore.

Subscribed to the label messages produced by the labelers.

Converted the atom_msgs containing the labels to the atom dataset format.

Tested producing a dataset and then calibrating with that dataset in rrbot, rlbot and rdbot.

All seems to be working fine. 

Furthermore, the compatibility of datasets is maintained, so we do not have to delete previous datasets.

**Comment by miguelriemoliveira** [comment]
@manuelgitgomes , since I did extensive tests with the atom examples I am confident this should be working.
Also, I don't want to ask you to try this out during Christmas.

So, I  will merge the PR right away. If some problem appears I will be on it in no time.

To use the new version a reconfiguration of the calibration packages is necessary.

**Comment by manuelgitgomes** [comment]
Hello @miguelriemoliveira!

Great job, I will be testing this soon enough so I can create new issues with bugs. :-)

**Comment by miguelriemoliveira** [comment]
> Great job, I will be testing this soon enough so I can create new issues with bugs. :-)

Right. To be expected ...
