### ISSUE TITLE
Should we have position_bias and origin_yaw parameters?

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#803]
@manuelgitgomes FYI

They seem to do the same, so we could remove the position_bias.

I did an experiment that is to run a bagfile and look at the coordinate frame of the forearm link

The thick. short ref frame in the image.

Them I used this code to subscribe to joint state messages and produce the corresponding transformations according to the joint angles.  I did this with a change in the angle in two methods:

1. Added 45 degrees more to the position_bias parameter (the medium thickness, medium length coordinate frame in the image)
2.  Added 45 degrees to the value of the origin_yaw (the thin thickness, longer frame in the image)

![image](https://github.com/lardemua/atom/assets/11350998/c3abc792-f236-4141-95e5-64cd13534182)

As expected, both methods 1 and 2 are 45 degrees deviated from the original frame. Also, as expected, both methods result in the coincident  coordinate frames ... So it seems indeed both parameters will do the same. 

The question is why did the optimizer does not work as well when using the origin_yaw instead of the position_bias ...

**Comment by miguelriemoliveira** [comment]
Got it. In the shoulder method 1 gives what was expected, but method 2 does not.

The problem occurs in the shoulder, not the elbow. I think it has to do with the values of origin_xyz and origin roll pitch different from 0. 


![image](https://github.com/lardemua/atom/assets/11350998/d2735b44-e344-45ed-b4f8-5b361d86c54b)

![image](https://github.com/lardemua/atom/assets/11350998/c4102680-0862-4cac-b763-2b7baae4ea79)

Will investigate later.

**Comment by miguelriemoliveira** [comment]
Found the problem. We were using euler angle axis **sxyz**  and it should be **rxyz**.

Now everything makes sense:

![image](https://github.com/lardemua/atom/assets/11350998/92e08f6e-3df3-4ed0-b118-d2ca6b50e5cf)

**Comment by miguelriemoliveira** [comment]
Now we go back to the experiment of trying to calibrate using position bias vs using origin_yaw ...

**Comment by miguelriemoliveira** [comment]
So the calibration experiments turned out to show what we already expected: Using position bias or using origin_z (for revolute joints in which the axis is 0 0 1) gives exactly the same result.

So I think that we should remove the position_bias parameter from the optimization, and instead use the origin_yaw.

@manuelgitgomes you agree? Should I proceed with this change?

**Comment by manuelgitgomes** [comment]
Hello @miguelriemoliveira!

Great news.
I think we can proceed then!

**Comment by miguelriemoliveira** [comment]
Thanks @manuelgitgomes . I will proceed.
