### ISSUE TITLE
Create an example of a prismatic joint calibration

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#804]
For this we'll need to create a scara robot.

**Comment by miguelriemoliveira** [comment]
![image](https://github.com/lardemua/atom/assets/11350998/3cb3b29c-772a-4ef8-89bb-4fec230e3c68)

Scara robotic system is online. Inspired in the FANUC SR-6iA 

https://www.fanuc.eu/sk/en/robots/robot-filter-page/scara-series/scara-sr-6ia

**Comment by manuelgitgomes** [comment]
Great @miguelriemoliveira, but we would need the sensor to be on the end-effector, correct?

**Comment by miguelriemoliveira** [comment]
> but we would need the sensor to be on the end-effector, correct?

I did it already. Check it out:

![image](https://github.com/lardemua/atom/assets/11350998/7017ae73-2115-49e1-96e4-636e55d3ba01)
