### ISSUE TITLE
Calibration visualization crashes when a collection has no pattern detected

### ISSUE THREAD

**Issue by manuelgitgomes** [lardemua/atom#806]
When running calibration with visualization on a single sensor, this error appears:

```bash
 File "atom/atom_calibration/src/atom_calibration/calibration/visualization.py", line 732, in visualizationFunction
    graphics['collections'][collection_key][sensor_key]['publisher'].publish(msg)
KeyError: 'azure_rgb_camera'

```

I think this because of this block of code:
https://github.com/lardemua/atom/blob/6082bcc1ad3a98baab8475a3a9c54974ec12f4e5/atom_calibration/src/atom_calibration/calibration/visualization.py#L206-L220

This does not create the key-value pair for the sensor.

**Comment by manuelgitgomes** [comment]
Removing the # from this block of code everything ran smoothly.
Was there a reason for this to be commented @miguelriemoliveira?

https://github.com/lardemua/atom/blob/6082bcc1ad3a98baab8475a3a9c54974ec12f4e5/atom_calibration/src/atom_calibration/calibration/visualization.py#L685-L693

**Comment by miguelriemoliveira** [comment]
> Was there a reason for this to be commented @miguelriemoliveira?

Not sure why I commented. Perhaps I thought that collections where no sensors detected at least one pattern should be filtered. In any case, my suggestion is to put it back in there, and then we can find a better solution.
