### ISSUE TITLE
Generate train and test dataset from a single dataset

### ISSUE THREAD

**Issue by manuelgitgomes** [lardemua/atom#808]
In ATOM, we usually take two different datasets (at least) for each robotic system: a train dataset to generate the calibrated dataset, and a test dataset to run evaluations.

Sometimes, personally, it would be handy to have a script that splits a big dataset into these two, similarly to how it is done in ML/DL approaches. 
The user could give a percentage split (80/20, 90/10, 50/50, etc...) to generate each dataset.
They would be on the same folder but with two different json files `train_dataset.json` and `test_dataset.json`.

I need this right now for convenience, so I will start developing.
Tagging @miguelriemoliveira  for ideas to add to this.

**Comment by miguelriemoliveira** [comment]
I like the idea. I think you know how to do it, right?

**Comment by manuelgitgomes** [comment]
Yes, this is done!
