### ISSUE TITLE
Remove joint_position_bias parameter from calibration

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#809]
After the analysis in #803 we came to the conclusion that the joint_position_bias parameter is redundant with one other joint parameter, depending on the type and axis configuration of the joint.

For example, for a revolute joint that rotates around the z axis (i.e. axis = 0 0 1), the origin_yaw parameter does exactly the same as the joint_position_parameter. The same occurs for prismatic joints. 

The decision is to remove the joint_position_bias parameter from the optimization.

The atom examples **jcpbbot** (#811),  **rihbot** (#812), **riwmpbot** (#813)

must be revised.

**Comment by miguelriemoliveira** [comment]
How to change the production of xacro at

https://github.com/lardemua/atom/blob/4022f412d06c16235f5903c22d9e4a0094458398/atom_core/src/atom_core/xacro_io.py#L70-L88

Not really sure. I think it should be removed. I will remove.

**Comment by miguelriemoliveira** [comment]
@manuelgitgomes I think you will have to rerun your joint based calibrations. Sorry!

**Comment by manuelgitgomes** [comment]
Great job @miguelriemoliveira!

The latest calibration on #706 was done without position bias already!
