### ISSUE TITLE
Update evaluators to operate with joint optimization

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#816]
Hi @manuelgitgomes ,

please put here the command to run to produce evaluation, so we can test.

**Comment by manuelgitgomes** [comment]
This is already done, right?

https://github.com/lardemua/atom/blob/7459d8336e1aa2725f08793ebc4b112fd289bf0f/atom_core/src/atom_core/dataset_io.py#L897-L922

**Comment by miguelriemoliveira** [comment]
Yeah, its done. I forgot I has done it already. Sorry.
