### ISSUE TITLE
Improve inspect atom datasets to provide statistics of the observed joint positions.

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#825]
In #821 it came up the idea of understanding the distribution of the positions of each joints in a robotic system.

**Comment by manuelgitgomes** [comment]
I tried to do something similar in https://github.com/lardemua/atom/blob/ed2a3fee82edbfd3b12c3678ac5e3bc8844ce356/atom_calibration/scripts/utilities/generate_joint_space_tsne

In there, we generate a tsne plot for the joint spaces, don't know if that is interesting to you.

**Comment by miguelriemoliveira** [comment]
> don't know if that is interesting to you.

Sounds interesting. I will try it.

**Comment by miguelriemoliveira** [comment]
Implemented .

**Comment by miguelriemoliveira** [comment]
An example:

![image](https://github.com/lardemua/atom/assets/11350998/f1f3bc24-d959-4b95-8272-41473bae4446)
