### ISSUE TITLE
Merge -utf and not -utf into a single mechanism

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#838]
This would be helpful to avoid the user having to insert the -utf flag, and to solve inconsistency issues derived from having two alternatives (#836 ).

**Comment by miguelriemoliveira** [comment]
Will start working on this, using softbot as an example.

FYI @brunofavs and @manuelgitgomes

**Comment by miguelriemoliveira** [comment]
So  the files that use flag use_tfs are:

configure_calibration_pkg 
config_visualization

**Comment by brunofavs** [comment]
Ok,
Im doing the softbot example for atom examples today too :)

**Comment by miguelriemoliveira** [comment]
The idea is to use the xacro for providing information about the joints. If the transformation is not found in the xacro, search in the bagfile for the tf that contains the that transformation.

**Comment by miguelriemoliveira** [comment]
> Im doing the softbot example for atom examples today too :)

Great. Put it in a separate issue.

**Comment by miguelriemoliveira** [comment]
Use a PR for that please. Its a big change.

**Comment by miguelriemoliveira** [comment]
Looked into this with @manuelgitgomes.  

There is a problem on how to create a hybrid of using both tfs generated by the xacro/joint_states/robot_state_publisher and tfs recorded to the bagfile.

The solution seems to be, in the cases where the xacro is not sufficient, to record a new bagfile which contains only the tfs that do not exist in the xacro.

**Comment by miguelriemoliveira** [comment]
Running the softbot calibration without the --use_tfs results in error:

> Traceback (most recent call last):
>   File "/home/mike/workspaces/catkin_ws/devel/lib/atom_calibration/configure_calibration_pkg", line 15, in <module>
>     exec(compile(fh.read(), python_script, 'exec'), context)
>   File "/home/mike/workspaces/catkin_ws/src/calibration/atom/atom_calibration/scripts/configure_calibration_pkg", line 378, in <module>
>     raise ValueError('TF tree is not connected. Aborting.')
> ValueError: TF tree is not connected. Aborting.
> 
> exit status: 1

The code is this:

https://github.com/lardemua/atom/blob/17629406d9c80b5494c47a9511b18df8bd5391e0/atom_calibration/scripts/configure_calibration_pkg#L369-L378

The graph shows the world and pattern link disconnected from the rest of the tree.

![image](https://github.com/lardemua/atom/assets/11350998/ad6ae344-fe04-442a-9710-1838d20296c7)

**Comment by miguelriemoliveira** [comment]
The question is how to find that what were missing in the tree is the world->base_link transform in the bagfile.

Or perhaps we do not need to find, we just need to add all the transforms in the bagfile that do not exist in the xacro ...

**Comment by miguelriemoliveira** [comment]
I think this is working better. Here's the result of configuring hte softbot

![image](https://github.com/lardemua/atom/assets/11350998/0632e100-7e3b-4200-a5fc-f075902182ad)

The left branch (back_camera) was not in the xacro, so it was added from the tf with static transforms. 
The world to base_link was also added.

**Comment by miguelriemoliveira** [comment]
Producing the bagfile seems to be working fine.

The original softbot bagfile has frames above. However, after filtering the bagfile to have only the frames that do not exist in the xacro, we get:

![image](https://github.com/lardemua/atom/assets/11350998/be6a8345-df19-42b2-b0a7-f164cd07d15b)

**Comment by miguelriemoliveira** [comment]
Should be working fine. --use_tfs is gone.
