### ISSUE TITLE
Bug when running rgb_to_rgb_evaluation related to the loadResultsJSON() function

### ISSUE THREAD

**Issue by Kazadhum** [lardemua/atom#840]
When running:

`rosrun atom_evaluation rgb_to_rgb_evaluation -train_json /home/diogo/atom_datasets/zau2/real/dataset1/results/atom_calibration.json -test_json /home/diogo/atom_datasets/zau2/real/dataset1/atom_calibration.json -ss hand_camera -st camera_mb
`
I get the following error:

```
Traceback (most recent call last):
  File "/home/diogo/catkin_ws/src/atom/atom_evaluation/scripts/rgb_to_rgb_evaluation", line 172, in <module>
    train_dataset, train_json_file = loadResultsJSON(args["train_json_file"], args["collection_selection_function"])
ValueError: too many values to unpack (expected 2)
```

I've traced the problem to the following. When the `loadResultsJSON()` function is called, it is supposed to return two values: the name of the dataset JSON file and the actual dataset.

https://github.com/lardemua/atom/blob/cf0b0e488ea2833f92c3ae6e7fa10e9f7cf0545a/atom_evaluation/scripts/rgb_to_rgb_evaluation#L168-L175

However, the function only returns the dataset:

https://github.com/lardemua/atom/blob/cf0b0e488ea2833f92c3ae6e7fa10e9f7cf0545a/atom_core/src/atom_core/dataset_io.py#L42-L160

Tagging @miguelriemoliveira and @manuelgitgomes for visibility.

**Comment by miguelriemoliveira** [comment]
Great! Thanks @Kazadhum .
