### ISSUE TITLE
riwbot examples data fails to download

### ISSUE THREAD

**Issue by brunofavs** [lardemua/atom#842]
There seems to be a issue downloading riwbot example data when executing:

`rosrun atom_calibration download_atom_examples_data`

![download_examples_bug](https://github.com/lardemua/atom/assets/31831043/e450a90d-a267-4ff1-93cf-3531765a28b2)

All other examples downloaded with any issue.

I reckon it has something to do the drive yet I can't be sure.

**Comment by manuelgitgomes** [comment]
Hello @brunofavs.
Can you show your downloaded atom_examples?

The error comes from wanting to unzip a zipped dataset but not being able to.

**Comment by brunofavs** [comment]
Hey @manuelgitgomes 

Here is my tree structure for the bagfiles and datasets folders:

[datasets_tree.txt](https://github.com/lardemua/atom/files/14279454/datasets_tree.txt)
[bagfile_tree.txt](https://github.com/lardemua/atom/files/14279457/bagfile_tree.txt)

This zipfile  `$ROS_BAGS/riwbot/train.zip` seems to be the issue, as I cannot open it.

![image](https://github.com/lardemua/atom/assets/31831043/b1bdacaf-8c4c-4c41-b154-054f8c820fc2)

I tried to download multiple times already and this behavior was consistent

**Comment by manuelgitgomes** [comment]
Strange, might be something corrupted in that specific file?

But I have downloaded it as you did and nothing was wrong.
Here it is, see if this works.
[train.zip](https://github.com/lardemua/atom/files/14279510/train.zip)

**Comment by brunofavs** [comment]
This file seems to be good.

I don't know what it might be, odds are it's something on my end.

**Comment by manuelgitgomes** [comment]
I have this downloaded a long time ago, I will test this further on a newly downloaded copy.

**Comment by miguelriemoliveira** [comment]
Thanks @brunofavs for posting the issue.

I had the wrong link, not sure why. Can you test again please?

**Comment by miguelriemoliveira** [comment]
... you can use the flag --overwrite to make sure you redownload everything ...

**Comment by brunofavs** [comment]
This time everything worked as expected, without any errors.

I'm also having some trouble launching the calibration studio because the charuco model isn't loading in but I'll try to figure it out and if I can't will post a issue later.

Meanwhile I think this issue is solved, I'm closing it now
