### ISSUE TITLE
Bag files in atom examples corrupted

### ISSUE THREAD

**Issue by brunofavs** [lardemua/atom#845]
Hey,

I noticed that a lot of the bagfiles in atom examples seem to be corrupted and unplayable when I was learning rdbot.

Here attached you can see a view of all the bagfiles and their size, and every bagfile whose size is a few Kb's does not work properly.
 
[bag_bugs.txt](https://github.com/lardemua/atom/files/14346129/bag_bugs.txt)

The configure script bugs early when it doesn't recognize the bagfile.

```
Loading config_file /home/brunofavs/atom_ws/src/atom/atom_examples/rdbot/rdbot_calibration/calibration/config.yml
Loading bagfile /home/brunofavs/bagfiles/rdbot/train.bag ... 
Traceback (most recent call last):
  File "/home/brunofavs/atom_ws/devel/lib/atom_calibration/configure_calibration_pkg", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/brunofavs/atom_ws/src/atom/atom_calibration/scripts/configure_calibration_pkg", line 134, in <module>
    bag = rosbag.Bag(bag_file)
  File "/opt/ros/noetic/lib/python3/dist-packages/rosbag/bag.py", line 467, in __init__
    self._open(f, mode, allow_unindexed)
  File "/opt/ros/noetic/lib/python3/dist-packages/rosbag/bag.py", line 1428, in _open
    if   mode == 'r': self._open_read(f, allow_unindexed)
  File "/opt/ros/noetic/lib/python3/dist-packages/rosbag/bag.py", line 1456, in _open_read
    self._version = self._read_version()
  File "/opt/ros/noetic/lib/python3/dist-packages/rosbag/bag.py", line 1570, in _read_version
    raise ROSBagException('This does not appear to be a bag file')
rosbag.bag.ROSBagException: This does not appear to be a bag file
```

And this is the output of trying to playback the rosbag

```rosbag play -l $ROS_BAGS/rdbot/train.bag```

```
[ INFO] [1708441564.631153796]: Opening /home/brunofavs/bagfiles/rdbot/train.bag
[FATAL] [1708441564.655679147]: Error reading version line
```

Meanwhile I will try to record a bagfile of my own and learn it that way, it's also a great way to familiarize myself with atom and regain fluency in ROS.

**Comment by miguelriemoliveira** [comment]
Hi @brunofavs ,

how are you downloading the bag files? Using the script?

**Comment by miguelriemoliveira** [comment]
Also, can you run a 

    rosbag info <bagname>

**Comment by brunofavs** [comment]
Hi @miguelriemoliveira 

Yes, I used the script :

```
rosrun atom_calibration download_atom_examples_data
```

I did re-download with the overwrite flag due to prior struggles, however I find odd that for some robots' bagfiles are perfectly fine meanwhile others are not

This is the output of the rosbag info command : ( I forgot this existed)

`rosbag info train.bag`

`ERROR reading train.bag: This does not appear to be a bag file
`

The output doesn't add much though.

Also, what would happen if I were to record another bag file and change it in the configure yaml but still use the dataset recorded with the supposed corrupted bagfile? In other words, the dataset must be obtained through the bagfile specified in the config?

I tried to still use the rdbot dataset as it was ok but with a bagfile of my own and it seems to be working fine, I just wanted a confirmation to check if I'm not overlooking any possible  caveats.

Sorry if these last paragraphs were a little offtopic to the original issue, I feel they are, but I wasn't sure where to ask.

**Comment by miguelriemoliveira** [comment]
Hi @brunofavs ,

please let me know which bagfiles do not work so I can fix them.

> Also, what would happen if I were to record another bag file and change it in the configure yaml but still use the dataset recorded with the supposed corrupted bagfile? In other words, the dataset must be obtained through the bagfile specified in the config?

After a dataset is collected the bagfile is not used anymore, so you can calibrate using the dataset collected previously from another dataset.

> Sorry if these last paragraphs were a little offtopic to the original issue, I feel they are, but I wasn't sure where to ask.

Tipically that should go into a new issue with a propper title.

**Comment by brunofavs** [comment]
Hi @miguelriemoliveira 
I tested all bagfiles whose size was too low and all exhibited the same bad behavior.

Narrowing down the previous list I sent to just the corrupted ones results in : 

```                                                                          
./mrjbot:
2,4K test.bag
1,7K test_with_noise.bag
2,4K train.bag
1,7K train_with_noise.bag

./rdbot:
2,4K train.bag

./rihbot:
2,4K train.bag

./riwmpbot:
2,4K train.bag

./rlbot:
2,4K train.bag

./rrcbot:
167K test.bag

```

[bag_bugg_v2.txt](https://github.com/lardemua/atom/files/14349032/bag_bugg_v2.txt)

> After a dataset is collected the bagfile is not used anymore, so you can calibrate using the dataset collected previously from another dataset.

Ok, I think you meant _"from another bagfile"_ but I got it regardless, thanks :) 

> Tipically that should go into a new issue with a propper title.

Ok, I wasn't sure because it wasn't a problem on the project itself, it was just my lack of understanding

**Comment by miguelriemoliveira** [comment]
I confirm the issue.

**Comment by miguelriemoliveira** [comment]
I @brunofavs ,

I fixed the problem. Now we are using a program called gdown. You must install it using pip.
Its in the atom requirements.txt file.

From my side it now works fine. The downside is that since we are making a system call now we do not have the progress bar while the files are being downloaded.

Try to run the command with overwrite. All the bagfiles and datasets should be dowloade fine.

**Comment by brunofavs** [comment]
Hey @miguelriemoliveira 
Sorry for the late reply, I couldn't work yesterday.

I downloaded again with the overwrite flag, and all bags are working now apart from these 2:

```
./mrjbot:
total 216M
104M  test.bag
1,7K  test_with_noise.bag
112M  train.bag
1,7K  train_with_noise.bag
```

**Comment by miguelriemoliveira** [comment]
Hi @brunofavs ,

those two don't exist anymore. You had them corrupted from before, and they remained. 
If you delete them manually and them redownload, they should not appear. 

Please confirm ...

**Comment by brunofavs** [comment]
Hey
Yes I redownloaded and everything is in order.

That was my bad.
Closing the issue now
