### ISSUE TITLE
Implement calibration evaluation procedure to evaluate the riwmpbot real calibrationn

### ISSUE THREAD

**Issue by Kazadhum** [lardemua/atom#857]
The idea is to measure the error by projecting the pattern corners (based on the optimized urdfs after calibration) to the the actual camera image and measure the distance to where they're detected in the image.

@miguelriemoliveira is this correct? I don't know if I can explain it properly.

I think, since we're implementing a whole new feature, I'll create a new branch and then pull request once it's working.

Tagging @manuelgitgomes and @danifpdra for visibility.

**Comment by manuelgitgomes** [comment]
Hello @Kazadhum. I have already developed this in my private fork. I can pull request it if you want.

**Comment by miguelriemoliveira** [comment]
I accepted the PR. Me and @Kazadhum will test this next week.

**Comment by miguelriemoliveira** [comment]
> @miguelriemoliveira is this correct? I don't know if I can explain it properly.

That's it.

**Comment by miguelriemoliveira** [comment]
We tested and had to make some minor changes to accomodate for using multiple patterns.

**Comment by miguelriemoliveira** [comment]
Thansks @manuelgitgomes
