### ISSUE TITLE
Create script to merge datasets

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#861]
Hi @manuelgitgomes ,

I know you did a dataset split script . How  easy  would it be for you to do a merge?

Thanks

**Comment by manuelgitgomes** [comment]
Hello @miguelriemoliveira,

Sorry for the delayed response.

It already at:
https://github.com/lardemua/atom/blob/noetic-devel/atom_calibration%2Fscripts%2Futilities%2Fsplit_atom_dataset

**Comment by miguelriemoliveira** [comment]
Thanks @manuelgitgomes. Will test it now.

**Comment by miguelriemoliveira** [comment]
wait, @manuelgitgomes this is the split. The questions was about a merge tool ...

**Comment by miguelriemoliveira** [comment]
I was trying to implement but now that I think of it, perhaps its easier to merge the bagfiles and then create a single datasets.

**Comment by miguelriemoliveira** [comment]
workign on it ...

**Comment by miguelriemoliveira** [comment]
I think I got a first solution up and running ... will test later.

**Comment by manuelgitgomes** [comment]
Sorry, I have create a new PR #864 to solve this in a more general way (I hope so)

**Comment by miguelriemoliveira** [comment]
Hi @manuelgitgomes ,

but I also did it. I said above "working on it" to let you know not to worry about this.

**Comment by miguelriemoliveira** [comment]
Closing this one. The version we have is functional.
