### ISSUE TITLE
Problem with the riwmpbot URDF

### ISSUE THREAD

**Issue by Kazadhum** [lardemua/atom#862]
Hi @miguelriemoliveira ! When I try to bring up the riwmpbot system, it seems like the TF tree for the system has some problems. It seems disjointed. I can try to fix it but since it worked on your PC I thought maybe it's a fix you haven't pushed to GitHub?

![frames](https://github.com/lardemua/atom/assets/93128909/db22f660-4ee5-4c77-b8de-b102611dcda3)

**Comment by miguelriemoliveira** [comment]
Strange. How do you run this?

**Comment by Kazadhum** [comment]
@miguelriemoliveira hi! I just realized I wasn't launching Gazebo properly, so it was a mistake on my part!

**Comment by miguelriemoliveira** [comment]
OK, great.
