### ISSUE TITLE
riwmpbot dataset only has data regarding one joint in each collection

### ISSUE THREAD

**Issue by Kazadhum** [lardemua/atom#865]
Hi @miguelriemoliveira ! Each collection in the dataset for riwmpbot in atom_examples only has the data regarding one joint. Maybe the file needs to be updated?

![image](https://github.com/lardemua/atom/assets/93128909/dbdf6860-504c-4068-af49-da7480a9060f)

**Comment by miguelriemoliveira** [comment]
This occurs probably when the dataset was produced using  a calibration configuration where only the elbow joint was being optimized.

In any case I downloaded the train.zip  and I think  we have all the joints ...

**Comment by miguelriemoliveira** [comment]
How are you downloading the dataset?

**Comment by miguelriemoliveira** [comment]
The link should be 

https://drive.google.com/file/d/1bzgNoFnqLvJ0zE8bvWJjVV50w2bfkage/view?usp=sharing

**Comment by Kazadhum** [comment]
Hi! I downloaded the dataset from the link given here: https://github.com/lardemua/atom/blob/noetic-devel/atom_examples/riwmpbot/README.md#collecting-a-dataset

If you check the link there with the link you've sent, you can see they're different. The dataset you've just sent seems correct.

**Comment by miguelriemoliveira** [comment]
Hi @Kazadhum ,

ok, you were using the link in the readme. Those are hard to update. Can you please correct it.

I suggest you use this

https://github.com/lardemua/atom/tree/noetic-devel/atom_examples#download-bagfiles-and-datasets

**Comment by Kazadhum** [comment]
Ah I see. I'll update this one then, for anyone who tries to do the same as I did, but I'll do as you suggest in the future. Thank you!

**Comment by Kazadhum** [comment]
Done!
