### ISSUE TITLE
Possible to calibrate two robot arms base frame?

### ISSUE THREAD

**Issue by Ruthrash** [lardemua/atom#877]
Hey thanks so much for this awesome and comprehensive software tools for robot sensor calibration. I have a robot system with two robot arms with a camera on hand each and a fixed world lidar. I'm wondering if it will be possible to find the extrinsic transformation between the two robot base frames as well using the ATOM framework? Please let me know your thoughts. Thanks!

**Comment by miguelriemoliveira** [comment]
Hi @Ruthrash ,

We never tested a two arm system. Nonetheless, we are convinced it should work fine. My suggestion is that you first run some subset calibrations, like hand eye, then hand eye plus lidar, and only then the full two arm solution.

I recommend that you go through the documentation. Also, we recently added several examples where you can find hand-eye configurations close to what you want.

Let me know if you need some help.
