### ISSUE TITLE
configure calibration package prints only at the end

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#890]

**Comment by miguelriemoliveira** [comment]
Also it should not wait a lot for reading the bag

**Comment by manuelgitgomes** [comment]
Hello @miguelriemoliveira.
This was bothering me, so I decided to solve it with a solution I developed in the tactile calibration.

**Comment by miguelriemoliveira** [comment]
Ok. Does it work with batch execution?

**Comment by manuelgitgomes** [comment]
It could, but it is not implemented yet.
I can take care of that, should I create a new issue?.
Sorry for the poor explanation, but I created a function:
https://github.com/lardemua/atom/blob/cd5725ef506d9bb9dbf81509f3132186c8238ed0/atom_calibration/templates/configure#L27-L48

That does exactly what we intend.

**Comment by miguelriemoliveira** [comment]
Yes, if you can do it in the batch execution also that would be great. 
New issue makes sense.
