### ISSUE TITLE
Implement Astra Camera to prepare for data collection at INESC 2024 (zaubot)

### ISSUE THREAD

**Issue by Kazadhum** [lardemua/atom#902]
This is done, but just so it's documented, I created the launch files to launch the astra camera and record it's images, both RGB and Depth (for if it is needed). I've only tested with one Astra at a time yet, but I'll test with both at the same time once I can.

Regrettably, I've not recorded a video to show it, but now that I think about it I should have. Regardless, I use the `usb_cam` package to get the RGB image and the `astra_camera` package package to get the depth image. The instructions for launching are in the [readme](https://github.com/lardemua/zau/blob/main/README.md) for the [zau repo](https://github.com/lardemua/zau.git).

Tagging @miguelriemoliveira for visibility.

**Comment by miguelriemoliveira** [comment]
Hi @Kazadhum ,

that's the way to do it. Thanks.

@manuelgitgomes , @brunofavs , can you do similarly for your sensors.

@Kazadhum is it possible to change the frames per second and the resolution of the camera? What do we have now?

**Comment by Kazadhum** [comment]
Hi @miguelriemoliveira! I think these are all change-able, after searching online.

In terms of the RGB image, we have a resolution of 1280x720 and these parameters are given to `usb_cam` node. I assume these can be changed.

When it comes to the depth camera, the resolution we have is 640x480, also passed as a parameter to the `astra_pro` launch file.

So I think we can change these, but I'm not sure what resolution is the limit.

About the frames per second, the depth image has 30 fps specified in the parameters for the launch file, but the RGB image does not as of yet. I can add the parameter `framerate` to the launch file but I'm not going to be in Aveiro to test it. I can add it though, and test it once I get back.

**Comment by miguelriemoliveira** [comment]
OK, makes sense.

**Comment by manuelgitgomes** [comment]
Data collection done, closing this.
