### ISSUE TITLE
Implement Velodyne to prepare for data collection at INESC 2024 (zaubot)

### ISSUE THREAD

**Issue by manuelgitgomes** [lardemua/atom#904]
This issue serves for the implementation of a VLP-16 to collect data in Zau.

**Comment by manuelgitgomes** [comment]
Hello @miguelriemoliveira, @Kazadhum, and @brunofavs .
VLP-16 is now functional, with all instructions on the repo!

**Comment by miguelriemoliveira** [comment]
Great.
