### ISSUE TITLE
Replace placeholders with links in softbot example

### ISSUE THREAD

**Issue by brunofavs** [lardemua/atom#908]
Creating this issue as @miguelriemoliveira requested me to replace these placeholders in the softbot example : 

It's just here : 

https://github.com/lardemua/atom/blob/6d3e92d734c2a04ce7193fb59d2611e08ca6b3b7/README.md#L77-L83

and here : 

https://github.com/lardemua/atom/blob/6d3e92d734c2a04ce7193fb59d2611e08ca6b3b7/README.md#L116-L123

and here : 

https://github.com/lardemua/atom/blob/6d3e92d734c2a04ce7193fb59d2611e08ca6b3b7/README.md#L180-L187

~~With this [link](https://we.tl/t-etWHBKnye1)~~

Use this instead [updated link](https://github.com/lardemua/atom/issues/908#issuecomment-2026098693)

I do realize I forgot to update the test dataset.
I will do it shortly and comment this issue

**Comment by brunofavs** [comment]
Updated link with test and train dataset
https://we.tl/t-ssxiMUx4AV

**Comment by miguelriemoliveira** [comment]
Hi @brunofavs ,

here are the links you can use to update the readme:

train bagfile
https://gofile.me/7nlMj/PAmVjWhxy

test bagfile
https://gofile.me/7nlMj/czx2rL51T

train dataset
https://gofile.me/7nlMj/5XvOf6TS2

test dataset
https://gofile.me/7nlMj/P7BflqUVp

Do you need anything else?

**Comment by miguelriemoliveira** [comment]
Great. Thanks.
