### ISSUE TITLE
Implement Intel RealSense T265 to prepare for data collection at INESC 2024 (zaubot)

### ISSUE THREAD

**Issue by brunofavs** [lardemua/atom#909]
Related to #894

**Comment by brunofavs** [comment]
Hmm I'm getting these errors when running `roslaunch realsense2_camera rs_t265.launch` : 
``` 
03/04 10:37:16,023 ERROR [125105338922752] (handle-libusb.h:51) failed to open usb interface: 0, error: RS2_USB_STATUS_ACCESS
 03/04 10:37:16,023 ERROR [125105338922752] (tm-boot.h:42) Failed to open T265 zero interface
[ WARN] [1712137038.029745034]: No RealSense devices were found!
```

It might be related to be running it inside of a docker.
Trying this : 
https://github.com/IntelRealSense/realsense-ros/issues/1408#issuecomment-698128999

Did you encounter these @manuelgitgomes ?

**Comment by manuelgitgomes** [comment]
Hello @brunofavs.

I did not enconter such errors, however, I needed to add some udev rules to my host system, as is stated in the repo:
https://github.com/lardemua/zau

**Comment by brunofavs** [comment]
Ok , I added those to the docker system instead with no luck. Will try in the host system now.

**Comment by brunofavs** [comment]
> Ok , I added those to the docker system instead with no luck. Will try in the host system now.


Yep that worked. 


https://github.com/lardemua/atom/assets/31831043/eb556136-75ae-4f8e-bfe6-dec5f6c0909d

These are the topics published : 

```
/camera/accel/imu_info
/camera/accel/metadata
/camera/accel/sample
/camera/gyro/imu_info
/camera/gyro/metadata
/camera/gyro/sample
/camera/odom/metadata
/camera/odom/sample
/camera/realsense2_camera_manager/bond
/camera/tracking_module/parameter_descriptions
/camera/tracking_module/parameter_updates
/clicked_point
/diagnostics
/initialpose
/move_base_simple/goal
/rosout
/rosout_agg
/tf
/tf_static
```

I'm wondering why our camera isn't publishing these topics as stated [here](https://github.com/IntelRealSense/realsense-ros/tree/ros1-legacy#using-t265)
```
/camera/fisheye1/image_raw
/camera/fisheye2/image_raw
```

There is one **Warning** when the sensor moves too fast, which is interesting : 
`WARNING [125497602209536] (tm-device.cpp:1291) SLAM_ERROR Speed`

Tagging @miguelriemoliveira  for visibility.

**Comment by miguelriemoliveira** [comment]
Looks good. 

One question tough: This is done with a docker? How do you plan to run this with all other sensors toghether?
Run some sensors in different containers? Use one container for all sensors ?



About the missing topics I would not worry about those, as will will not use that information.

> There is one Warning when the sensor moves too fast, which is interesting :

This was expected and nothing to worry about for now.

**Comment by brunofavs** [comment]
I'm kinda new to dockers, I just started using Distrobox 1/2 weeks ago. I would say I plan to run everything in the same container but I really have no idea which benefits using multi containers would bring to the table.

But I think testing that wouldn't be hard, I would just need to clone the docker.
Granted I also don't know how to use ROS in a master/slaves configuration.

**Comment by miguelriemoliveira** [comment]
> Granted I also don't know how to use ROS in a master/slaves configuration.

That part I can cover, no problem.

I think we should target using a single docker container. That would be the easiest.

**Comment by brunofavs** [comment]
Ok, sounds easier to me too.

**Comment by manuelgitgomes** [comment]
Data collection done, closing this.
