### ISSUE TITLE
Modularize -ctgt from calibrate for easy integration in other scripts

### ISSUE THREAD

**Issue by Kazadhum** [lardemua/atom#916]

**Comment by Kazadhum** [comment]
It seems like this is done. In `atom_core.utilities`:

https://github.com/lardemua/atom/blob/73066893937065e2d79832197b18366924c45049/atom_core/src/atom_core/utilities.py#L138-L272

Tagging @miguelriemoliveira for visibility. I'll close it for now but open it back up if there's any issue in its implementation in #912 .

**Comment by miguelriemoliveira** [comment]
ah, who was the person that did this beautiful function :-) ?
