### ISSUE TITLE
Testing desync when sending ROS messages through mqtt

### ISSUE THREAD

**Issue by Kazadhum** [lardemua/atom#924]
- [x] Record a bag file in PC 1 (clock running $\Delta t$ minutes late)
- [x] Send it through mqtt to PC 2 and record it
- [x] Check message timestamps for desync
- [x] Test possible fixes

**Comment by Kazadhum** [comment]
Hi @miguelriemoliveira! Me and @manuelgitgomes just tested this and your flag on the mqqt-ros bridge seems to be working!

**Comment by miguelriemoliveira** [comment]
ok, great. Lets see how it goes on Monday.
