### ISSUE TITLE
Conclusions after day inesc 1

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#930]
FYI @Kazadhum @manuelgitgomes @brunofavs @rafaelarrais

**Comment by miguelriemoliveira** [comment]
- Manipulator base link should have smaller z value. Updated the xacro.
- We did not launch robot state publisher and that's the correct thing to do
- We had a wrong topic name for the lidar. Not points were recorded.
- We forgot to record the odometry message.
- renamed zau/base_footprint -> base_footprint and zau/odom -> world:

`./rename_tf_frames -bfi ~/bagfiles/zau/inesc_day1_1_cropped.bag -bfo ~/bagfiles/zau/inesc_day1_1_cropped_renamed.bag -ftr zau/odom zau/base_footprint -nfn world base_footprint`

- Had to delete several frames to make sure the bagfile is fully connected. Command was:
- 
`./delete_tfs -bfi ~/bagfiles/zau/inesc_day1_1_cropped_renamed.bag -bfo ~/bagfiles/zau/inesc_day1_1_cropped_renamed_without_vo.bag -ftd vo_body_odom_frame vo_body_pose_frame vo_body_link vo_body_fisheye1_frame vo_body_fisheye1_optical_frame vo_body_fisheye2_frame vo_body_fisheye2_optical_frame vo_body_gyro_frame vo_body_gyro_frame vo_body_gyro_optical_frame vo_body_accel_frame vo_body_accel_optical_frame`

- config.yml hand camera name is wrong. Now changed.
- Later on we must invert the top two tfs for the visual odometry sub tree
![image](https://github.com/lardemua/atom/assets/93128909/d3103769-3e5b-4742-ab70-918626db1245)

**Comment by brunofavs** [comment]
We must not forget the video/photo coverage tomorrow

**Comment by Kazadhum** [comment]
- [x] Check if all sensor messages are being recorded
- [x] Record a test bagfile to calibrate on the spot
- [ ] Record a "showcase" bagfile to show the robot model's "shadow"
- [ ] Test labelers for complete collections for calibration method comparison

**Comment by manuelgitgomes** [comment]
Hello all!

To try and automate the cumbersome task of editing the bagfiles, I have done some changes:

Firstly, I change `rosbag_tools` to a ros package, to allow for a more universal way to call the scritps.
https://github.com/miguelriemoliveira/rosbag_tools/commit/01938354e12b26c291b86b297e2318634b242591

Then, I created a bash script, that automatically edits the bagfile the way we want:

https://github.com/lardemua/zau/blob/main/zau_calibration/scripts/edit_bag_file.bash

**Comment by miguelriemoliveira** [comment]
Looks good.
