### ISSUE TITLE
Fore.BLACK is unintellible to black terminal users

### ISSUE THREAD

**Issue by manuelgitgomes** [lardemua/atom#941]
In a lot of informative prints in ATOM code, after the color of the characters is changed to something (blue, red, yellow, etc...), it usually is returned to normal with Style.RESET_ALL.
However, in some prints, it is returned to normal using Fore.BLACK.
This is not an optimal choice, as not all users have black as their default terminal character color.
Even worse, when users have black as their terminal background color, this becomes unintelligible.
Therefore, I suggest changing all Fore.BLACK to Style.RESET_ALL.

**Comment by miguelriemoliveira** [comment]
Yep. It should return to Style.RESET_ALL

**Comment by miguelriemoliveira** [comment]
No response ... closing
