### ISSUE TITLE
ATOM only capable of handling plumb_bob distortion model

### ISSUE THREAD

**Issue by manuelgitgomes** [lardemua/atom#944]
As I was trying to collect data (#935), the `rgb_labeler` crashes, as the distortion model of the T265 camera (`equidistant`) is not compatible with the assumptions used by this script.
As we have not tried to do anything with this type of camera, I think more errors along the pipeline are to be expected.
What would be the best way to add this to the dataset?
Should I add a new parameter to the camera_info, with the distortion model?
Then all calculations can be done according to the model?

Tagging @miguelriemoliveira and @Kazadhum for visibility.

**Comment by manuelgitgomes** [comment]
My bad, the dataset already has the full camera info.
However, some calculation might be at stake. 
I will keep an eye on this.

**Comment by miguelriemoliveira** [comment]
Hi @manuelgitgomes,

my opinion is that for now if you can skip this better. 

Even if the dataset for now does not contain the fisheye images.

**Comment by manuelgitgomes** [comment]
Hello.
I have done a small change and this does not crash anymore on data collection.
Let's see in calibration.
