### ISSUE TITLE
Implement Lidar to camera Dahll2017

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#954]
Paper is LiDAR-Camera Calibration using 3D-3D Point correspondences
https://arxiv.org/pdf/1705.09785

Code is https://github.com/ankitdhall/lidar_camera_calibration/tree/master

**Comment by miguelriemoliveira** [comment]
So now we have a tool for annotating lidar developed under #958 and the **rlbot**  lidar data has been annotated.

**Comment by miguelriemoliveira** [comment]
Now showing the camera corners (spheres) and the ones given by lidar annotation (cylinders)

![image](https://github.com/lardemua/atom/assets/11350998/69dd4a58-8af9-48d2-85d5-825b08c54e8e)

well aligned here because I am using the ground truth camera_T_lidar transform here.

**Comment by miguelriemoliveira** [comment]
Calibration using Dahll icp_based method

dark cylinders -> initial lidar corners
light cylinders -> lidar corners after calibration
spheres -> camera corners

![image](https://github.com/lardemua/atom/assets/11350998/f16642d4-e960-4fe5-9ce3-5351e0eb1ae0)

**Comment by miguelriemoliveira** [comment]
Implemented but I think it works very poorly... @Kazadhum  perhaps we can talk about this ?

**Comment by Kazadhum** [comment]
Hi @miguelriemoliveira! Sure, tomorrow at 10am?

**Comment by miguelriemoliveira** [comment]
Hi,

Perhaps later in the morning. I will call you ok?

**Comment by miguelriemoliveira** [comment]
I was not able to make the Kabsh algorithm work. Tried several implementations. 

For now only the icp_based method works.

**Comment by miguelriemoliveira** [comment]
Not working on this anymore.
