### ISSUE TITLE
Depth labels only save a single border point

### ISSUE THREAD

**Issue by manuelgitgomes** [lardemua/atom#959]
Hello @miguelriemoliveira,

Currently, the depth labeler seems to work as intended in data collection:

![image](https://github.com/lardemua/atom/assets/58152228/ba80d6f6-9fd0-4624-8cc1-8652c4cdbcb6)

However, when the same collection is saved, most of the border points labeled seem to disappear, with the exception of one:
![image](https://github.com/lardemua/atom/assets/58152228/2beabe86-14f7-45e2-b009-e70e2a48c513)

This happens in all collections.

**Comment by manuelgitgomes** [comment]
The same problem also applies to Lidars...
![image](https://github.com/lardemua/atom/assets/58152228/5a06b60c-7059-4cbc-8f3b-c5b4f455e8f3)

**Comment by manuelgitgomes** [comment]
The solution was way simpler than expected.
The commit diff is self-explanatory really.
You can see it in 3e06363fa4d050ea6f04b203a314a578eef07174.
Basically the for loop that should append the `idx_limit_point`, was appending the fixed `idx`.

**Comment by miguelriemoliveira** [comment]
Great that you solved it ...
