### ISSUE TITLE
Function to assert the modality of a sensor

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#961]
Useful for the verifications of the other calibration methods.

**Comment by miguelriemoliveira** [comment]
This is done.

@Kazadhum I already use it in cv_eye_in_hand and cv_eye_to_hand, if you want use the same for your other hand eye calibration methods.

https://github.com/lardemua/atom/blob/51fe96a65f8d0e76a30784a13159ae88cedfee6a/atom_evaluation/scripts/other_calibrations/cv_eye_to_hand.py#L100-L101

**Comment by Kazadhum** [comment]
Thank you @miguelriemoliveira! I'll add this once I take a break from writing.
