### ISSUE TITLE
Develop Odometry inspector

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#967]
Related to #935.

The idea is to create an odometry inspector to allow for the user to manually provide an estimate of the location of the vehicle, thus correction flawed odometry data.

This is useful for fixing the dataset from inesc. 

FYI @Kazadhum .

**Comment by miguelriemoliveira** [comment]
First step is done. To show the reference point cloud, so its easy to visually align the robot.

![image](https://github.com/lardemua/atom/assets/11350998/cb0ec029-9152-4c10-92c5-661908ebbad1)

![image](https://github.com/lardemua/atom/assets/11350998/7e21dcad-5bd0-4824-9ff4-f2504af9d597)

**Comment by miguelriemoliveira** [comment]
Next step should  be to create an interactive marker to move the robot around and fix the odometry data.

**Comment by miguelriemoliveira** [comment]
Hi @Kazadhum and @manuelgitgomes ,

I think I have the odometry inspector up and running.

See this:

https://youtu.be/pIIyoUb_iGE

and give me some feedback.

I will call after lunch.

**Comment by manuelgitgomes** [comment]
Looks great, good job!

I have one question that was not clear to be from the video.
What is the default behavior when changing collections?
Does it go to the original odom tf?
Does it change to the same on as the recently changed?
What happens here?

**Comment by miguelriemoliveira** [comment]
This is operational. Created a complete corrected dataset for zau in #968.

One nice bonus would be a menu that would run an icp calibration. Will work on it if I have time later ...

**Comment by miguelriemoliveira** [comment]
For now closing this one.
