### ISSUE TITLE
Is the camera in the correct place in the zau inesc datasets?

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#970]
FYI @manuelgitgomes and @Kazadhum ,

I don't think it is ... I mean when correcting the odometry I had strange projections like in these examples:

![image](https://github.com/user-attachments/assets/acac7734-1e58-4ecd-9048-ae078cb737ba)

from this one it seems that the robot arm is not correctly aligned 

![image](https://github.com/user-attachments/assets/87ccee25-8ede-4261-a832-205c9393295b)

This one is also strange

![image](https://github.com/user-attachments/assets/5986c813-e1fc-468a-99d3-24a3a7308378)

Here's the positioning of the camera

![image](https://github.com/user-attachments/assets/ab829fdc-404d-4284-a03d-fca87f1493ff)

**Comment by miguelriemoliveira** [comment]
I tried to calibrate with hand camera rgb + another rgb and the calibration does not converge.
I think this is the problem. Initial guess for the hand rg and hand depth is very wrong ...

**Comment by manuelgitgomes** [comment]
Hello @miguelriemoliveira!

I am fairly certain the hand camera is rotated 180º in roll.
That should be fairly easy to rotate hardcoded in the dataset.
But, if you have the will to work on #971, that would be nice as well.

**Comment by miguelriemoliveira** [comment]
> I am fairly certain the hand camera is rotated 180º in roll.
> That should be fairly easy to rotate hardcoded in the dataset.
> But, if you have the will to work on #971, that would be nice as well.

Thanks @manuelgitgomes . I think #971 is better because usually my 3 month long searches for the correct transformation always start like this: I am fairly certain that we need to rotate this x degrees ... :)

**Comment by Kazadhum** [comment]
Ah, it looks like I might have made a mistake when inserting the camera in the URDF when we were over at INESC... :sweat_smile:

**Comment by miguelriemoliveira** [comment]
> Ah, it looks like I might have made a mistake when inserting the camera in the URDF when we were over at INESC... 😅

Yeah, that happens to everyone. That's why we need #971

**Comment by miguelriemoliveira** [comment]
Correcting using transform_corrector.

![image](https://github.com/user-attachments/assets/ef4a0dca-fe37-4a99-8692-8397a80dbd6e)

![image](https://github.com/user-attachments/assets/7f7220c3-c916-4967-a17b-fcae4ee8f60e)

It's not perfect, but much better.

**Comment by miguelriemoliveira** [comment]
It was mostly about rotating the camera 180 degrees.

**Comment by miguelriemoliveira** [comment]
Closing.
