### ISSUE TITLE
Should getMixedDataset() copy the pattern's TFs from the train dataset?

### ISSUE THREAD

**Issue by Kazadhum** [lardemua/atom#972]
It makes sense to me that for a fixed pattern, we use the calibrated pattern TFs for evaluation. What do you think @miguelriemoliveira and @manuelgitgomes?

**Comment by miguelriemoliveira** [comment]
Hi @Kazadhum ,

I think this is not always true. Consider the softbot or the rihbot, for example. The pattern is fixed, but from one dataset to another it may be changed.

So I would not assume that the pattern transformations can always be copied for fixed patterns. 

Perhaps we can use a flag to activate this copy?

**Comment by Kazadhum** [comment]
Hi @miguelriemoliveira!

You're right. We can't and shouldn't make that assumption. The flag is already implemented I think, as that's exactly what `-cpt` does.

**Comment by miguelriemoliveira** [comment]
Close issue?
