### ISSUE TITLE
Adding noise to filtered out joint

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#979]
FYI @Kazadhum ,

**Comment by miguelriemoliveira** [comment]
We are changing the order to make sure we affect transforms by the joint noise, even when those transforms are filtered out by jsf

**Comment by Kazadhum** [comment]
Here is the command I used:

`cd experiments/riwmpbot/ctgt_stratified_k_fold && rosrun atom_batch_execution batch_execution -v -tf template.yml.j2 -df data.yml -of results/ -ow`
