### ISSUE TITLE
Update the contributors page

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#991]
Hey all. The initial README page should lits you as contributors.

Perhaps we could organize it stating the date in which each person was involved, or just the names.

What do you think?

**Comment by brunofavs** [comment]
Hey,

I think its just me and @Kazadhum missing, so maybe to avoid having to go ask all the contributors when they started we could just add our name and university.

![image](https://github.com/user-attachments/assets/1166971e-ca5a-4235-b965-3c94abaeb0d7)

**Comment by brunofavs** [comment]
Or there should surely be a way to see when was the first commit of everyone.

**Comment by brunofavs** [comment]
`git log --author "username" --reverse | awk '/^commit/ { x+=1 } x>1 {exit}; {print}'`
[Command source](https://stackoverflow.com/questions/29523370/how-to-get-first-and-last-commit-from-git-from-a-user)

This command is branch independent, but for some reason tiagomfmadeira and eupedrosa don't show. Maybe they didn't do a commit? I may be saying something ridiculous, but I don't know their history with ATOM :D

@brunofavs 

commit f9d0b932f2f07e04f0f93d745269acb5840d31f5
Author: brunofavs <bruno.favs@ua.pt>
Date:   Tue Feb 20 18:15:43 2024 +0000

    Fixed a few path inconsistencies and a lack of use of env vars

@Kazadhum 

commit 9213b66b5581c75883919287d9b9fe326d6e3261
Author: Kazadhum <diogoscsv@gmail.com>
Date:   Fri Oct 20 15:43:22 2023 +0100

    fixed error string mistake #652

@miguelriemoliveira 

commit 63ae798557b6797c9e57f77c5f54a36bde2c88ef
Author: miguelriemoliveira <m.riem.oliveira@gmail.com>
Date:   Wed Apr 17 10:54:08 2019 +0100

    #4 urdf_domparser.py seems to work but not for sensors

@manuelgitgomes 

commit e1503a37fd7648e3e9fd205e15aca7bf7b2dde7e
Merge: 96943f8 4b9ffb4
Author: Manuel Gomes <58152228+manuelgitgomes@users.noreply.github.com>
Date:   Tue Dec 14 10:36:19 2021 +0000

    Merge pull request #334 from manuelgitgomes/noetic-devel

    Data set play bag first attempt

afonsocastro 

commit c995dcf5329b518c42cc8cdcc1c5a67d8600ee2e
Author: afonsocastro <47828797+afonsocastro@users.noreply.github.com>
Date:   Tue Mar 19 11:03:03 2019 +0000

    Initial commit

eupedrosa does not show :c 

danifpdra 

commit 275b55db8d1d3e1ae358fadc01c9a0160a25ced1
Author: danifpdra <danielarato@hotmail.com>
Date:   Thu Mar 11 13:45:18 2021 +0000

    added requirements


tiagomfmadeira doesn't show :C 

@aaguiar96 

commit 66f9a149848078014fea32044c62ffb5eb4d4216
Author: aaguiar96 <up201403474@fe.up.pt>
Date:   Fri Mar 6 10:02:07 2020 +0000

    Added rviz configuration file and playback launch file for AgRob V16 robot

**Comment by brunofavs** [comment]
I left extra information about each contributor to be nostalgic. Now we can add the dates each person started.

**Comment by Kazadhum** [comment]
Hello @miguelriemoliveira! I think just including the names would be fine, but the starting dates could be interesting as well!

**Comment by miguelriemoliveira** [comment]
Hey there,

Thanks @brunofavs for the commands.

One thing your command does not return is the first and last commit. Is it only the first?
If you can get the first and last I will add the dates, otherwise we just add the names.

BTW @Kazadhum and @brunofavs you should add the names already.

**Comment by Kazadhum** [comment]
Just added myself! Thank you for reminding us @miguelriemoliveira!

**Comment by brunofavs** [comment]
Hey @miguelriemoliveira 

I can get the date of the last commit as well.

When I get back to the pc I will do it

**Comment by brunofavs** [comment]
Last commits

`git log --author "username" -n 1`

brunofavs
Date:   Sat Oct 5 20:14:35 2024 +0100

Kazadhum
Date:   Tue Sep 10 14:50:10 2024 +0100

miguelriemoliveira
Date:   Tue Oct 1 23:55:42 2019 +0100

manuelgitgomes
Date:   Wed May 15 11:12:42 2024 +0100

afonsocastro
Date:   Fri Apr 3 02:35:40 2020 +0100

danifpdra
Date:   Wed Nov 8 11:24:36 2023 +0000

aaguiar96
Date:   Wed Aug 26 14:28:29 2020 +0100

eupedrosa, tiagomfmadeira don't show anything again.

**Comment by miguelriemoliveira** [comment]
Just added dates for all contributors. Also added @brunofavs .

Thanks for the input.
