### ISSUE TITLE
Calibration package configuration should allow for user-defined extra data to be stored during data collection

### ISSUE THREAD

**Issue by Kazadhum** [lardemua/atom#998]
When working on ribot, a simple simulated robot consisting of a floating bar with an IMU and RGB camera, I eneded up publishing the ground truth world-to-IMU tf to a topi separate from /tf.

The goal of this is to "skip" IMU data integration and use the simulation's TF outright. When generating the dataset for calibration, I would like to store this TF somewhere. So, I thought I could integrate an extra field in the `config.yaml` file. Something like "additional_data" where the user could define extra data to store.

Alternatively, I can implement a sensor modality to do the same thing. `imu_tf`, perhaps. It would have to be different from `imu` though, since this data is already integrated.

**Comment by Kazadhum** [comment]
Which avenue do you think I should take @miguelriemoliveira?

**Comment by miguelriemoliveira** [comment]
Hi @Kazadhum,

I think I did something similar at some point, creating a topic called something like ground truth tf.
In the end I deleted this because it was very dificult to use multiple tf messages.

In your case I think its just a matter of writting the tf in the usual collections[0]['transforms]?
Why can't you write them here directly?

**Comment by Kazadhum** [comment]
Hi @miguelriemoliveira! I thought of that and I do think it is the simpler solution.

I think I was thinking a bit forward to when I would actually record sensor data for the IMU. But perhaps you're right and for now it would be best to keep it as is and not worry about this too much.

**Comment by Kazadhum** [comment]
I will close this for now and will also delete the branch, since we decided to go through a different path.
